-- CodeQuest platformer curriculum audit for Islands 1-3.
-- Express/MySQL schema. Safe to re-run: replaces guided rows for these modules.
USE codequest;

UPDATE lesson_modules SET description='Move, jump, and interact with Pip''s platformer world.' WHERE id=1;
UPDATE lesson_modules SET description='Plan readable tile-by-tile crossings across bridges and gaps.' WHERE id=2;
UPDATE lesson_modules SET description='Use spatial numbers, switches, keys, and tile calculations.' WHERE id=3;

UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip starts at the left edge of the ruins. He moves right one tile at a time, using a short sequence to reach the flag.', hint='Use moveRight(1) for each horizontal tile.', goal='Move Pip across the starting platform with three rightward steps.' WHERE module_id=1 AND order_index=1;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip reaches a short platform with a gap. He crosses the first tiles, jumps the gap, and continues right to the flag.', hint='Combine moveRight(2), jump(1), and moveRight(2).', goal='Cross the platform and jump over its gap.', xp_reward=35 WHERE module_id=1 AND order_index=2;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A low obstacle blocks Pip''s route. He moves toward it, jumps over the obstacle, and lands on the next platform.', hint='Keep the actions spatial: move, jump, then move again.', goal='Use horizontal movement and a jump to clear the obstacle.', xp_reward=40 WHERE module_id=1 AND order_index=3;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip approaches a raised ledge. He must step across the lower tiles, jump up, and move right along the upper platform.', hint='Use jump(1) for the vertical action.', goal='Reach the raised platform with a movement and jump sequence.', xp_reward=45 WHERE module_id=1 AND order_index=4;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A long bridge spans the next section. Pip stores its tile distance in an integer, then uses that value for one precise crossing.', hint='Declare int distance before passing it to moveRight.', goal='Store a spatial distance and use it to cross the bridge.', xp_reward=45 WHERE module_id=1 AND order_index=5;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip must adapt his route after a moving platform changes position. He updates a step count, then uses the new value to move right.', hint='Use an integer stepCount and update it before moving.', goal='Update a spatial variable and use it for movement.', xp_reward=50 WHERE module_id=1 AND order_index=6;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A fixed bridge switch controls the next crossing. Pip stores the planned tile distance as a constant so the route remains predictable.', hint='Use final int distance for an unchanged measurement.', goal='Use a fixed spatial value to cross the bridge.', xp_reward=50 WHERE module_id=1 AND order_index=7;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip reaches a route with two possible tile counts: a short platform and a longer platform. He stores both distances before choosing the crossing.', hint='Declare numeric distances and pass one to moveRight.', goal='Represent platform distances with numeric variables.', xp_reward=55 WHERE module_id=1 AND order_index=8;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='The final bridge section requires a calculated tile count. Pip adds two platform spans together and moves across the resulting distance.', hint='Use integer arithmetic inside moveRight.', goal='Calculate a platform distance and move Pip that many tiles.', xp_reward=55 WHERE module_id=1 AND order_index=9;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip faces the first island route trial: store a distance, jump the hazard, and move across the final tiles to the end flag.', hint='Keep the sequence spatial and use declared variables.', goal='Combine stored distance, movement, and a jump.', xp_reward=70 WHERE module_id=1 AND order_index=10;

UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip reaches a broken bridge. He moves across its first tiles, jumps the missing section, and lands safely on the far side.', hint='Use moveRight and jump as platformer actions.', goal='Cross a bridge and clear its gap.', xp_reward=35 WHERE module_id=2 AND order_index=1;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A gatehouse approach has two ground sections. Pip walks the first section, jumps the low threshold, and walks to the gate.', hint='Keep each movement on its own statement.', goal='Complete a two-section approach with a jump.', xp_reward=35 WHERE module_id=2 AND order_index=2;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip measures a bridge span before crossing. The integer distance represents tiles in the world and is passed directly to movement.', hint='Declare int distance = 4 before moveRight(distance).', goal='Use a declared tile-distance variable.', xp_reward=40 WHERE module_id=2 AND order_index=3;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A bridge is split by a deep gap. Pip crosses the first span, jumps once, then moves across the final span.', hint='Use two moveRight calls with jump between them.', goal='Plan a three-part bridge crossing.', xp_reward=45 WHERE module_id=2 AND order_index=4;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A wide canyon needs a calculated crossing distance. Pip stores a base tile span, doubles it, and uses the result to move right.', hint='Declare int base before using base * 2.', goal='Calculate a tile distance from a spatial base value.', xp_reward=50 WHERE module_id=2 AND order_index=5;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip crosses a bridge with a safe first span and a final jump. The code order mirrors the visible route from left to right.', hint='Use movement before the jump and movement after it.', goal='Sequence platform actions in world order.', xp_reward=50 WHERE module_id=2 AND order_index=6;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip advances in repeatable tile units. He stores a step size and reuses it for each ground segment.', hint='Declare int stepCount before calling moveRight(stepCount).', goal='Reuse a spatial step variable.', xp_reward=55 WHERE module_id=2 AND order_index=7;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Two platform spans combine into one route. Pip stores both tile lengths, adds them, and moves across the joined distance.', hint='Declare speed and bonus as integer tile counts.', goal='Combine two spatial variables for movement.', xp_reward=60 WHERE module_id=2 AND order_index=8;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip crosses two trap sections separated by a jump. Each movement call represents a visible ground segment.', hint='Keep the movement and jump stages in route order.', goal='Build a complete crossing from spatial actions.', xp_reward=60 WHERE module_id=2 AND order_index=9;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip reaches the island bridge master route. He stores the full span, crosses it, jumps the final hazard, and moves to the flag.', hint='Declare distance before using it in movement.', goal='Combine typed spatial values with movement and jumping.', xp_reward=75 WHERE module_id=2 AND order_index=10;

UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip approaches the first pressure plate. He stores its whole-number weight and uses that measurement to decide whether the gate can open.', hint='Use int weight for a whole-number plate measurement.', goal='Use a numeric variable for a physical platformer measurement.', xp_reward=40 WHERE module_id=3 AND order_index=1;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='An enchanted gate needs a text password before Pip can cross. He stores the password as a String, then moves through the opened passage.', hint='Wrap the password in quotes and declare String doorPassword.', goal='Store a platformer gate password as text.', xp_reward=40 WHERE module_id=3 AND order_index=2;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A bridge switch is either on or off. Pip stores that two-state condition in a boolean before moving across the bridge.', hint='Use boolean isBridgeDown to represent the switch state.', goal='Represent a physical bridge state with a boolean.', xp_reward=45 WHERE module_id=3 AND order_index=3;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip measures two platform spans and adds them to find the total tile distance before a jump.', hint='Use int values for tile counts and addition for the total.', goal='Calculate a physical route distance with arithmetic.', xp_reward=45 WHERE module_id=3 AND order_index=4;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A moving platform changes Pip''s travel distance. He updates the stored distance, then uses the new value to move across the platform.', hint='Reassign distance instead of creating an unrelated value.', goal='Update a spatial variable before moving.', xp_reward=50 WHERE module_id=3 AND order_index=5;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='The ruins'' maximum jump energy cannot change during the level. Pip stores that fixed limit as a final integer before attempting the jump.', hint='Use final int maxEnergy for an immutable platform limit.', goal='Declare an unchanging spatial gameplay constant.', xp_reward=55 WHERE module_id=3 AND order_index=6;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip combines two route labels to name the platform section he is entering. String concatenation creates one readable map label.', hint='Use + to join two String values.', goal='Combine text that identifies a platformer route.', xp_reward=55 WHERE module_id=3 AND order_index=7;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='The altar needs Pip''s numeric tile distance as text. He converts the stored distance into a String before using it as the gate code.', hint='Use String.valueOf(distance) for the conversion.', goal='Convert a spatial number into gate-ready text.', xp_reward=60 WHERE module_id=3 AND order_index=8;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='A spike barrier checks whether Pip has enough energy to cross. He compares the current value with the safe threshold before moving right.', hint='Store the comparison result in boolean canPass.', goal='Use a comparison to make a spatial crossing decision.', xp_reward=65 WHERE module_id=3 AND order_index=9;
UPDATE lessons SET track='JAVA FOUNDATIONS', briefing='Pip reaches the Island 3 exit route. He stores the final distance and bridge state, crosses the safe tiles, and jumps the last gap to the flag.', hint='Declare each spatial variable before using it.', goal='Synthesize platform distances, a bridge state, movement, and a jump.', xp_reward=80 WHERE module_id=3 AND order_index=10;

SET @m1_1=(SELECT id FROM lessons WHERE module_id=1 AND order_index=1 LIMIT 1); SET @m1_2=(SELECT id FROM lessons WHERE module_id=1 AND order_index=2 LIMIT 1); SET @m1_3=(SELECT id FROM lessons WHERE module_id=1 AND order_index=3 LIMIT 1); SET @m1_4=(SELECT id FROM lessons WHERE module_id=1 AND order_index=4 LIMIT 1); SET @m1_5=(SELECT id FROM lessons WHERE module_id=1 AND order_index=5 LIMIT 1); SET @m1_6=(SELECT id FROM lessons WHERE module_id=1 AND order_index=6 LIMIT 1); SET @m1_7=(SELECT id FROM lessons WHERE module_id=1 AND order_index=7 LIMIT 1); SET @m1_8=(SELECT id FROM lessons WHERE module_id=1 AND order_index=8 LIMIT 1); SET @m1_9=(SELECT id FROM lessons WHERE module_id=1 AND order_index=9 LIMIT 1); SET @m1_10=(SELECT id FROM lessons WHERE module_id=1 AND order_index=10 LIMIT 1);
SET @m2_1=(SELECT id FROM lessons WHERE module_id=2 AND order_index=1 LIMIT 1); SET @m2_2=(SELECT id FROM lessons WHERE module_id=2 AND order_index=2 LIMIT 1); SET @m2_3=(SELECT id FROM lessons WHERE module_id=2 AND order_index=3 LIMIT 1); SET @m2_4=(SELECT id FROM lessons WHERE module_id=2 AND order_index=4 LIMIT 1); SET @m2_5=(SELECT id FROM lessons WHERE module_id=2 AND order_index=5 LIMIT 1); SET @m2_6=(SELECT id FROM lessons WHERE module_id=2 AND order_index=6 LIMIT 1); SET @m2_7=(SELECT id FROM lessons WHERE module_id=2 AND order_index=7 LIMIT 1); SET @m2_8=(SELECT id FROM lessons WHERE module_id=2 AND order_index=8 LIMIT 1); SET @m2_9=(SELECT id FROM lessons WHERE module_id=2 AND order_index=9 LIMIT 1); SET @m2_10=(SELECT id FROM lessons WHERE module_id=2 AND order_index=10 LIMIT 1);
SET @m3_1=(SELECT id FROM lessons WHERE module_id=3 AND order_index=1 LIMIT 1); SET @m3_2=(SELECT id FROM lessons WHERE module_id=3 AND order_index=2 LIMIT 1); SET @m3_3=(SELECT id FROM lessons WHERE module_id=3 AND order_index=3 LIMIT 1); SET @m3_4=(SELECT id FROM lessons WHERE module_id=3 AND order_index=4 LIMIT 1); SET @m3_5=(SELECT id FROM lessons WHERE module_id=3 AND order_index=5 LIMIT 1); SET @m3_6=(SELECT id FROM lessons WHERE module_id=3 AND order_index=6 LIMIT 1); SET @m3_7=(SELECT id FROM lessons WHERE module_id=3 AND order_index=7 LIMIT 1); SET @m3_8=(SELECT id FROM lessons WHERE module_id=3 AND order_index=8 LIMIT 1); SET @m3_9=(SELECT id FROM lessons WHERE module_id=3 AND order_index=9 LIMIT 1); SET @m3_10=(SELECT id FROM lessons WHERE module_id=3 AND order_index=10 LIMIT 1);

DELETE gs FROM guided_steps gs JOIN lessons l ON l.id=gs.lesson_id WHERE l.module_id IN (1,2,3);
INSERT INTO guided_steps (lesson_id,step_order,prompt,correct_snippet,distractor_1,distractor_2,distractor_3) VALUES
(@m1_1,1,'Move across the starting platform with three visible rightward steps.','moveRight(1);\nmoveRight(1);\nmoveRight(1);','moveLeft(1);','jump(1);','moveRight("3");'),
(@m1_2,1,'Cross the platform, jump the gap, and continue to the flag.','moveRight(2);\njump(1);\nmoveRight(2);','moveRight(2);\nmoveRight(2);','jump("1");\nmoveRight(2);','moveLeft(2);\njump(1);'),
(@m1_3,1,'Clear the low obstacle and land on the next platform.','moveRight(1);\njump(1);\nmoveRight(2);','moveRight(3);','jump(0);\nmoveLeft(2);','moveRight("1");'),
(@m1_4,1,'Reach the raised ledge with a ground step, a jump, and an upper-platform move.','moveRight(2);\njump(1);\nmoveRight(2);','moveRight(4);','jump("1");','moveLeft(2);'),
(@m1_5,1,'Store the bridge distance, then cross that many tiles.','int distance = 4;\nmoveRight(distance);','distance = "4";\nmoveRight(distance);','moveRight(4);','int distance;\nmoveRight(distance);'),
(@m1_6,1,'Update the step count for the moving platform and use it.','int stepCount = 2;\nstepCount += 2;\nmoveRight(stepCount);','stepCount =+ 2;\nmoveRight(stepCount);','moveRight(stepCount);','int stepCount = "4";\nmoveRight(stepCount);'),
(@m1_7,1,'Use the fixed bridge distance to cross the platform.','final int distance = 3;\nmoveRight(distance);','const int distance = 3;\nmoveRight(distance);','final distance = 3;\nmoveRight(distance);','moveRight(distance);'),
(@m1_8,1,'Store two platform distances and move using their numeric total.','int shortSpan = 2;\nint longSpan = 3;\nmoveRight(shortSpan + longSpan);','int shortSpan = "2";\nmoveRight(shortSpan);','moveRight(shortSpan + longSpan);','String longSpan = "3";\nmoveRight(longSpan);'),
(@m1_9,1,'Add two bridge sections and move across the calculated tile count.','int firstSpan = 2;\nint secondSpan = 3;\nmoveRight(firstSpan + secondSpan);','moveRight(firstSpan + secondSpan);','int firstSpan = "2";\nmoveRight(firstSpan + secondSpan);','moveRight(firstSpan, secondSpan);'),
(@m1_10,1,'Store the route distance, cross it, jump the hazard, and reach the flag.','int distance = 3;\nmoveRight(distance);\njump(1);\nmoveRight(2);','moveRight(distance);\njump();','int distance;\nmoveRight(distance);\njump(1);','moveRight("3");\njump(1);'),
(@m2_1,1,'Cross the broken bridge and jump its missing section.','moveRight(2);\njump(1);\nmoveRight(2);','moveRight(4);','jump("1");','moveLeft(2);'),
(@m2_2,1,'Walk the first approach, jump the threshold, and reach the gate.','moveRight(3);\njump(1);\nmoveRight(1);','jump(1);\nmoveRight(3);','moveRight("3");','moveLeft(3);'),
(@m2_3,1,'Declare the bridge span in tiles and pass it to movement.','int distance = 4;\nmoveRight(distance);','moveRight(Distance);','moveRight("distance");','int distance;\nmoveRight(distance);'),
(@m2_4,1,'Cross both bridge spans with a jump between them.','moveRight(2);\njump(1);\nmoveRight(3);','moveRight(5);','jump(1);\nmoveLeft(3);','moveRight(2);\nmoveRight(3);'),
(@m2_5,1,'Calculate the wide bridge span from a base tile count.','int base = 3;\nmoveRight(base * 2);','int base = "3";\nmoveRight(base * 2);','moveRight(base);','moveRight(base, 2);'),
(@m2_6,1,'Use ordered ground movement and a final jump to cross the bridge.','moveRight(2);\nmoveRight(2);\njump(1);','jump(1);\nmoveLeft(4);','moveRight("4");','jump("1");'),
(@m2_7,1,'Reuse a declared tile step for the crossing.','int stepCount = 2;\nmoveRight(stepCount);\nmoveRight(stepCount);','moveRight(stepCount);','int stepCount = "2";\nmoveRight(stepCount);','moveRight(StepCount);'),
(@m2_8,1,'Add two spatial values and move across their combined distance.','int speed = 3;\nint bonus = 4;\nmoveRight(speed + bonus);','moveRight(speed + Bonus);','int speed = "3";\nmoveRight(speed + bonus);','moveRight(speed, bonus);'),
(@m2_9,1,'Cross two ground sections and jump the hazard between them.','moveRight(3);\njump(1);\nmoveRight(3);','moveRight(6);','jump("1");','moveLeft(3);\nmoveRight(3);'),
(@m2_10,1,'Use a stored span, cross it, jump, and move to the end flag.','int distance = 5;\nmoveRight(distance);\njump(1);\nmoveRight(2);','int distance;\nmoveRight(distance);','moveRight("5");\njump(1);','jump(1);\nmoveLeft(2);'),
(@m3_1,1,'Store the pressure plate weight and use it as the physical measurement.','int weight = 12;\nmoveRight(weight);','int weight = "12";\nmoveRight(weight);','moveRight(weight);','int weight;\nmoveRight(weight);'),
(@m3_2,1,'Store the gate password as text, then move through the opened passage.','String doorPassword = "OPEN";\nmoveRight(2);','String doorPassword = OPEN;\nmoveRight(2);','int doorPassword = "OPEN";','moveRight(doorPassword);'),
(@m3_3,1,'Store the bridge switch state and cross the active bridge.','boolean isBridgeDown = true;\nmoveRight(3);','boolean isBridgeDown = "true";\nmoveRight(3);','bool isBridgeDown = 1;','moveRight(isBridgeDown);'),
(@m3_4,1,'Add the two platform spans and move across their total.','int firstSpan = 2;\nint secondSpan = 3;\nint totalDistance = firstSpan + secondSpan;\nmoveRight(totalDistance);','int totalDistance = "2 + 3";\nmoveRight(totalDistance);','moveRight(firstSpan + secondSpan);','String totalDistance = firstSpan + secondSpan;'),
(@m3_5,1,'Update the moving-platform distance before using it.','int distance = 2;\ndistance = 5;\nmoveRight(distance);','int distance = 2;\nint distance = 5;\nmoveRight(distance);','distance == 5;\nmoveRight(distance);','String distance = "5";\nmoveRight(distance);'),
(@m3_6,1,'Declare the fixed jump-energy limit for the ruins.','final int maxEnergy = 100;\nmoveRight(1);','const int maxEnergy = 100;\nmoveRight(1);','final maxEnergy = 100;\nmoveRight(1);','final int maxEnergy;\nmoveRight(maxEnergy);'),
(@m3_7,1,'Combine two route labels into one map label before moving.','String section = "Bridge";\nString marker = "East";\nString routeLabel = section + marker;\nmoveRight(1);','String routeLabel = section && marker;\nmoveRight(1);','String routeLabel = section . marker;\nmoveRight(1);','routeLabel = section + marker;\nmoveRight(1);'),
(@m3_8,1,'Convert the numeric tile distance into text for the altar, then move.','int distance = 10;\nString strDistance = String.valueOf(distance);\nmoveRight(distance);','String strDistance = (String) distance;\nmoveRight(distance);','String strDistance = distance.toString();\nmoveRight(distance);','int strDistance = String(distance);\nmoveRight(distance);'),
(@m3_9,1,'Compare the energy threshold and move when Pip can safely pass.','int energy = 50;\nboolean canPass = energy >= 30;\nmoveRight(2);','boolean canPass = energy => 30;\nmoveRight(2);','boolean canPass = energy = 30;\nmoveRight(2);','int energy = "50";\nmoveRight(energy);'),
(@m3_10,1,'Use declared spatial values, cross the bridge, jump the gap, and reach the flag.','int distance = 3;\nboolean isBridgeDown = true;\nmoveRight(distance);\nif (isBridgeDown) { jump(1); }\nmoveRight(2);','int distance;\nmoveRight(distance);\njump();','boolean isBridgeDown = "true";\nmoveRight(distance);','moveRight("3");\nmoveLeft(2);');

-- Keep distractors platformer-safe too; they may be incorrect, but must not
-- introduce methods outside Pip's supported movement/action set.
UPDATE guided_steps gs
JOIN lessons l ON l.id = gs.lesson_id
SET gs.correct_snippet = REPLACE(REPLACE(gs.correct_snippet, 'moveLeft(', 'moveRight('), 'stop();', 'say("Stopped");'),
	gs.distractor_1 = REPLACE(REPLACE(gs.distractor_1, 'moveLeft(', 'moveRight('), 'stop();', 'say("Stopped");'),
	gs.distractor_2 = REPLACE(REPLACE(gs.distractor_2, 'moveLeft(', 'moveRight('), 'stop();', 'say("Stopped");'),
	gs.distractor_3 = REPLACE(REPLACE(gs.distractor_3, 'moveLeft(', 'moveRight('), 'stop();', 'say("Stopped");')
WHERE l.module_id IN (1, 2, 3);
