-- ============================================================
-- ISLAND 7: LOOPS AND BRANCHING  (Chapter 11 + Chapter 12)
-- 20 levels. Lesson ids 199-218, module_id 7.
-- Levels 1-8   = Chapter 11 (Repetition Control Structures)
-- Levels 9-20  = Chapter 12 (Branching Statements)
-- ============================================================

-- 1) The lessons table has a foreign key to lesson_modules, so module 7 must exist first.
--    (Copy the column list from your own module 6 row. Example only, adjust the columns to match your table:)
-- INSERT INTO `lesson_modules` (`id`, `title`, ...) VALUES (7, 'Loops and Branching', ...);

-- If a run stops with "#1406 Data too long for column ...", check the column sizes with
--   SHOW COLUMNS FROM `lessons`;
-- and widen the short ones (keep NOT NULL if your table has it), for example:
-- ALTER TABLE `lessons` MODIFY `required_code_label` VARCHAR(255), MODIFY `required_code_pattern` VARCHAR(500), MODIFY `goal` VARCHAR(500), MODIFY `solution_code` VARCHAR(500);

-- 2) Clear any existing Island 7 rows so re-running this file never hits
--    "Duplicate entry '7-1' for key 'uq_lessons_module_order'".
--    First look at what is there:
--      SELECT id, module_id, order_index, title FROM lessons WHERE module_id = 7 OR id >= 199;
-- Removes the old Island 7 snippets, including any old rows that sit on ids 199-218
-- under a different module_id (those would otherwise cause a primary-key error).
DELETE FROM `lessons` WHERE `module_id` = 7 OR `id` BETWEEN 199 AND 218;

-- OPTIONAL: if players already have saved progress for the OLD lessons 199-218, the new
-- levels would show as already completed. Clear it with your progress table's real name, e.g.:
-- DELETE FROM `user_progress` WHERE `lesson_id` BETWEEN 199 AND 218;

-- 3) The lessons
INSERT INTO `lessons` (`id`, `module_id`, `level_label`, `track`, `title`, `briefing`, `hint`, `goal`, `xp_reward`, `target_tiles`, `order_index`, `is_active`, `created_at`, `min_moves`, `min_says`, `min_jumps`, `required_code_label`, `required_code_pattern`, `background_image`, `subtitle`, `description`, `grid_cols`, `grid_rows`, `mechanics_config`, `total_tiles`, `ground_fraction`, `initial_tile`, `flag_tile`, `solution_code`, `line_breakdown`) VALUES
(199, 7, 'Level 1', 'LOOPS AND BRANCHING', 'The Countdown Stairs', 'Pip reaches Spiral Isle, where a staircase repeats until a rule says stop. Repetition control structures are Java statements that execute a block of code a number of times, and there are three kinds: while, do-while and for. A while loop repeats its block as long as the boolean expression is true. In the guide, i starts at 4 and the loop prints 4321.

Declare int i = 4, then write a while loop that runs while i > 0, prints i with System.out.print, and decrements i with i--.', 'while ( condition ) { print; i--; }', 'int i = 4; while (i > 0) { System.out.print(i); i--; }', 50, 8, 1, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 4; while (i > 0) { System.out.print(i); i--; }', 'int\\s+i\\s+=\\s+4;\\s+while\\s*\\(\\s*i\\s+>\\s+0\\s*\\)\\s*\\{\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s+i--;\\s*\\}', '/assets/landscapes/oakheart1.png', 'The while Loop', 'Pip reaches Spiral Isle, where a staircase repeats until a rule says stop. Repetition control structures are Java statements that execute a block of code a number of times, and there are three kinds: while, do-while and for. A while loop repeats its block as long as the boolean expression is true. In the guide, i starts at 4 and the loop prints 4321.

Declare int i = 4, then write a while loop that runs while i > 0, prints i with System.out.print, and decrements i with i--.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 4; while (i > 0) { System.out.print(i); i--; }', '[{"part": "int i = 4;", "explanation": "The loop variable, which starts at 4."}, {"part": "while (i > 0)", "explanation": "The condition is checked before every pass. The loop runs while it is true."}, {"part": "System.out.print(i);", "explanation": "Prints the current value of i without a newline, so the output is 4321."}, {"part": "i--;", "explanation": "Decrements i so the condition eventually becomes false and the loop ends."}]'),
(200, 7, 'Level 2', 'LOOPS AND BRANCHING', 'The Endless Corridor', 'A corridor never ends for those who forget the rule. If the statement that changes the loop variable is missing, the loop never terminates. That is an infinite loop. Whenever you use a repetition control structure, add statements that let the loop end at some point.

Declare int count = 1, then loop while count <= 3, print count, and make the loop terminate by increasing count with count++.', 'The loop needs a statement that moves count toward the limit.', 'int count = 1; while (count <= 3) { System.out.print(count); count++; }', 50, 8, 2, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int count = 1; while (count <= 3) { System.out.print(count); count++; }', 'int\\s+count\\s+=\\s+1;\\s+while\\s*\\(\\s*count\\s+<=\\s+3\\s*\\)\\s*\\{\\s*System\\.out\\.print\\(\\s*count\\s*\\);\\s+count\\+\\+;\\s*\\}', '/assets/landscapes/oakheart2.png', 'Avoiding an Infinite Loop', 'A corridor never ends for those who forget the rule. If the statement that changes the loop variable is missing, the loop never terminates. That is an infinite loop. Whenever you use a repetition control structure, add statements that let the loop end at some point.

Declare int count = 1, then loop while count <= 3, print count, and make the loop terminate by increasing count with count++.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int count = 1; while (count <= 3) { System.out.print(count); count++; }', '[{"part": "int count = 1;", "explanation": "The loop variable."}, {"part": "while (count <= 3)", "explanation": "Keeps looping while count is 1, 2 or 3."}, {"part": "System.out.print(count);", "explanation": "Prints the current value."}, {"part": "count++;", "explanation": "Moves count toward the limit. Without it the loop would never end."}]'),
(201, 7, 'Level 3', 'LOOPS AND BRANCHING', 'The Run-First Door', 'A door opens first and asks questions later. The do-while loop is similar to while, but it runs the statements first and then evaluates the condition. If the condition is true, the statements run again. A common mistake is forgetting the semicolon after the while expression.

Declare int i = 0, then write a do-while loop that prints i, increments i, and repeats while i < 3.', 'do { ... } while ( condition );  Do not forget the final semicolon.', 'int i = 0; do { System.out.print(i); i++; } while (i < 3);', 50, 8, 3, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 0; do { System.out.print(i); i++; } while (i < 3);', 'int\\s+i\\s+=\\s+0;\\s+do\\s*\\{\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s+i\\+\\+;\\s*\\}\\s*while\\s*\\(\\s*i\\s+<\\s+3\\s*\\);', '/assets/landscapes/oakheart3.png', 'The do-while Loop', 'A door opens first and asks questions later. The do-while loop is similar to while, but it runs the statements first and then evaluates the condition. If the condition is true, the statements run again. A common mistake is forgetting the semicolon after the while expression.

Declare int i = 0, then write a do-while loop that prints i, increments i, and repeats while i < 3.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 0; do { System.out.print(i); i++; } while (i < 3);', '[{"part": "int i = 0;", "explanation": "The loop variable."}, {"part": "do {", "explanation": "Starts the block that always runs first."}, {"part": "System.out.print(i); i++;", "explanation": "Prints i, then moves it forward."}, {"part": "} while (i < 3);", "explanation": "The condition is checked after the block. The semicolon at the end is required."}]'),
(202, 7, 'Level 4', 'LOOPS AND BRANCHING', 'The Run-Once Door', 'The main difference between while and do-while is that the statements inside a do-while loop are executed at least once, even when the condition is false from the start. A while loop with the same false condition would never run at all.

Declare int i = 10, then write a do-while loop that prints Once with println and repeats while i < 5. The text prints one time.', 'The block runs once before the condition i < 5 is checked.', 'int i = 10; do { System.out.println("Once"); } while (i < 5);', 50, 8, 4, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 10; do { System.out.println("Once"); } while (i < 5);', 'int\\s+i\\s+=\\s+10;\\s+do\\s*\\{\\s*System\\.out\\.println\\(\\s*"Once"\\s*\\);\\s*\\}\\s*while\\s*\\(\\s*i\\s+<\\s+5\\s*\\);', '/assets/landscapes/oakheart4.png', 'do-while Runs At Least Once', 'The main difference between while and do-while is that the statements inside a do-while loop are executed at least once, even when the condition is false from the start. A while loop with the same false condition would never run at all.

Declare int i = 10, then write a do-while loop that prints Once with println and repeats while i < 5. The text prints one time.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 10; do { System.out.println("Once"); } while (i < 5);', '[{"part": "int i = 10;", "explanation": "A value that makes the condition false from the start."}, {"part": "do { System.out.println(\\"Once\\"); }", "explanation": "Runs one time before any check."}, {"part": "while (i < 5);", "explanation": "False for 10, so the loop stops after the first pass."}]'),
(203, 7, 'Level 5', 'LOOPS AND BRANCHING', 'The Counting Wheel', 'The for loop also repeats code, and it keeps its three controls in one place: for (InitializationExpression; LoopCondition; StepExpression). The initialization sets the loop variable, the condition compares it to a limit, and the step expression updates it. In the guide, the loop prints 0 to 9.

Declare int i, then write a for loop that sets i to 0, runs while i < 10, steps with i++, and prints i.', 'for ( i = 0; i < 10; i++ ) { ... } Use semicolons, not commas.', 'int i; for (i = 0; i < 10; i++) { System.out.print(i); }', 50, 8, 5, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int i; for (i = 0; i < 10; i++) { System.out.print(i); }', 'int\\s+i;\\s+for\\s*\\(\\s*i\\s+=\\s+0;\\s+i\\s+<\\s+10;\\s+i\\+\\+\\s*\\)\\s*\\{\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s*\\}', '/assets/landscapes/oakheart1.png', 'The for Loop', 'The for loop also repeats code, and it keeps its three controls in one place: for (InitializationExpression; LoopCondition; StepExpression). The initialization sets the loop variable, the condition compares it to a limit, and the step expression updates it. In the guide, the loop prints 0 to 9.

Declare int i, then write a for loop that sets i to 0, runs while i < 10, steps with i++, and prints i.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i; for (i = 0; i < 10; i++) { System.out.print(i); }', '[{"part": "int i;", "explanation": "Declares the loop variable."}, {"part": "i = 0;", "explanation": "The initialization expression. It runs once at the start."}, {"part": "i < 10;", "explanation": "The loop condition. It is checked before every pass."}, {"part": "i++", "explanation": "The step expression. It runs after each pass."}, {"part": "{ System.out.print(i); }", "explanation": "The body, which prints 0 to 9."}]'),
(204, 7, 'Level 6', 'LOOPS AND BRANCHING', 'The Mirror Staircase', 'Every for loop can be rewritten as a while loop. The initialization goes before the loop, the condition goes inside the while parentheses, and the step goes at the end of the body. The guide shows this for the 0 to 9 loop.

Declare int i = 0, then write a while loop that runs while i < 10, prints i, and increments i.', 'Initialization first, condition in while, step at the end of the body.', 'int i = 0; while (i < 10) { System.out.print(i); i++; }', 50, 8, 6, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 0; while (i < 10) { System.out.print(i); i++; }', 'int\\s+i\\s+=\\s+0;\\s+while\\s*\\(\\s*i\\s+<\\s+10\\s*\\)\\s*\\{\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s+i\\+\\+;\\s*\\}', '/assets/landscapes/oakheart2.png', 'A for Loop as a while Loop', 'Every for loop can be rewritten as a while loop. The initialization goes before the loop, the condition goes inside the while parentheses, and the step goes at the end of the body. The guide shows this for the 0 to 9 loop.

Declare int i = 0, then write a while loop that runs while i < 10, prints i, and increments i.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 0; while (i < 10) { System.out.print(i); i++; }', '[{"part": "int i = 0;", "explanation": "The for loop\'s initialization, moved before the loop."}, {"part": "while (i < 10)", "explanation": "The for loop\'s condition."}, {"part": "System.out.print(i);", "explanation": "The body of the loop."}, {"part": "i++;", "explanation": "The for loop\'s step, moved to the end of the body."}]'),
(205, 7, 'Level 7', 'LOOPS AND BRANCHING', 'The Falling Steps', 'The step expression can count down too. Start high, keep looping while the variable is above the limit, and use i-- as the step expression. This loop prints 54321.

Write a for loop that declares int i = 5, runs while i > 0, steps with i--, and prints i.', 'for ( int i = 5; i > 0; i-- )', 'for (int i = 5; i > 0; i--) { System.out.print(i); }', 50, 8, 7, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: for (int i = 5; i > 0; i--) { System.out.print(i); }', 'for\\s*\\(\\s*int\\s+i\\s+=\\s+5;\\s+i\\s+>\\s+0;\\s+i--\\s*\\)\\s*\\{\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s*\\}', '/assets/landscapes/oakheart3.png', 'Counting Down With for', 'The step expression can count down too. Start high, keep looping while the variable is above the limit, and use i-- as the step expression. This loop prints 54321.

Write a for loop that declares int i = 5, runs while i > 0, steps with i--, and prints i.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'for (int i = 5; i > 0; i--) { System.out.print(i); }', '[{"part": "int i = 5;", "explanation": "Starts the loop variable high."}, {"part": "i > 0;", "explanation": "Keeps looping while i is above 0."}, {"part": "i--", "explanation": "Counts down by one after each pass."}, {"part": "{ System.out.print(i); }", "explanation": "Prints 5, 4, 3, 2 and 1."}]'),
(206, 7, 'Level 8', 'LOOPS AND BRANCHING', 'The Double Steps', 'The step expression updates the loop variable, and it can change it by more than one. Using i += 2 moves two at a time, so the loop prints 0, 2, 4, 6 and 8.

Write a for loop that declares int i = 0, runs while i < 10, steps with i += 2, and prints i.', 'Use i += 2 as the step expression.', 'for (int i = 0; i < 10; i += 2) { System.out.print(i); }', 50, 8, 8, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: for (int i = 0; i < 10; i += 2) { System.out.print(i); }', 'for\\s*\\(\\s*int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+10;\\s+i\\s+\\+=\\s+2\\s*\\)\\s*\\{\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s*\\}', '/assets/landscapes/oakheart4.png', 'A Bigger Step', 'The step expression updates the loop variable, and it can change it by more than one. Using i += 2 moves two at a time, so the loop prints 0, 2, 4, 6 and 8.

Write a for loop that declares int i = 0, runs while i < 10, steps with i += 2, and prints i.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'for (int i = 0; i < 10; i += 2) { System.out.print(i); }', '[{"part": "int i = 0;", "explanation": "Starts at 0."}, {"part": "i < 10;", "explanation": "Stops once i reaches 10."}, {"part": "i += 2", "explanation": "Adds 2 to i after each pass."}, {"part": "{ System.out.print(i); }", "explanation": "Prints 0, 2, 4, 6 and 8."}]'),
(207, 7, 'Level 9', 'LOOPS AND BRANCHING', 'The Emergency Exit', 'Pip reaches the branching trails. Branching statements redirect the flow of program execution, and Java offers three: break, continue and return. The unlabeled break terminates the enclosing switch statement. You can also use it to terminate a for, while or do-while loop, and control then moves to the statement right after the loop.

Write a for loop with int i = 0, i < 10 and i++. Inside it, if i == 5, break.', 'if ( i == 5 ) { break; }', 'for (int i = 0; i < 10; i++) { if (i == 5) { break; } }', 60, 8, 9, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: for (int i = 0; i < 10; i++) { if (i == 5) { break; } }', 'for\\s*\\(\\s*int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+10;\\s+i\\+\\+\\s*\\)\\s*\\{\\s*if\\s*\\(\\s*i\\s+==\\s+5\\s*\\)\\s*\\{\\s*break;\\s*\\}\\s*\\}', '/assets/landscapes/oakheart1.png', 'The Unlabeled break', 'Pip reaches the branching trails. Branching statements redirect the flow of program execution, and Java offers three: break, continue and return. The unlabeled break terminates the enclosing switch statement. You can also use it to terminate a for, while or do-while loop, and control then moves to the statement right after the loop.

Write a for loop with int i = 0, i < 10 and i++. Inside it, if i == 5, break.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'for (int i = 0; i < 10; i++) { if (i == 5) { break; } }', '[{"part": "for (int i = 0; i < 10; i++)", "explanation": "A loop that would run ten times."}, {"part": "if (i == 5)", "explanation": "Checks for the moment to leave. Note the double equals sign."}, {"part": "break;", "explanation": "Terminates the loop immediately."}]'),
(208, 7, 'Level 10', 'LOOPS AND BRANCHING', 'The Name Hunt', 'A search loop should stop as soon as it finds what it wants. In the guide, the program searches a names array for searchName. When names[i].equals(searchName) is true, it sets foundName to true and breaks out of the for loop, so the remaining names are never checked.

Assume names, searchName and foundName already exist. Write a for loop over names.length that sets foundName = true and breaks when names[i].equals(searchName).', 'Set foundName = true; and then break; inside the if.', 'for (int i = 0; i < names.length; i++) { if (names[i].equals(searchName)) { foundName = true; break; } }', 60, 8, 10, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'for\\s*\\(\\s*int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+names\\.length;\\s+i\\+\\+\\s*\\)\\s*\\{\\s*if\\s*\\(\\s*names\\[i\\]\\.equals\\(\\s*searchName\\s*\\)\\s*\\)\\s*\\{\\s*foundName\\s+=\\s+true;\\s+break;\\s*\\}\\s*\\}', '/assets/landscapes/oakheart2.png', 'break When Found', 'A search loop should stop as soon as it finds what it wants. In the guide, the program searches a names array for searchName. When names[i].equals(searchName) is true, it sets foundName to true and breaks out of the for loop, so the remaining names are never checked.

Assume names, searchName and foundName already exist. Write a for loop over names.length that sets foundName = true and breaks when names[i].equals(searchName).', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'for (int i = 0; i < names.length; i++) { if (names[i].equals(searchName)) { foundName = true; break; } }', '[{"part": "for (int i = 0; i < names.length; i++)", "explanation": "Visits every index of the names array. Arrays use length without parentheses."}, {"part": "if (names[i].equals(searchName))", "explanation": "True when the current name matches the one being searched."}, {"part": "foundName = true;", "explanation": "Remembers that the name was found."}, {"part": "break;", "explanation": "Ends the loop so no more names are checked."}]'),
(209, 7, 'Level 11', 'LOOPS AND BRANCHING', 'The Endless Door', 'The unlabeled break works in while loops too. A loop whose condition is always true would run forever, so a break inside it provides the way out.

Declare int i = 0, then write a while (true) loop that increments i and breaks when i == 3.', 'while (true) { i++; if (...) { break; } }', 'int i = 0; while (true) { i++; if (i == 3) { break; } }', 60, 8, 11, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 0; while (true) { i++; if (i == 3) { break; } }', 'int\\s+i\\s+=\\s+0;\\s+while\\s*\\(\\s*true\\s*\\)\\s*\\{\\s*i\\+\\+;\\s+if\\s*\\(\\s*i\\s+==\\s+3\\s*\\)\\s*\\{\\s*break;\\s*\\}\\s*\\}', '/assets/landscapes/oakheart3.png', 'break in a while Loop', 'The unlabeled break works in while loops too. A loop whose condition is always true would run forever, so a break inside it provides the way out.

Declare int i = 0, then write a while (true) loop that increments i and breaks when i == 3.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 0; while (true) { i++; if (i == 3) { break; } }', '[{"part": "int i = 0;", "explanation": "The counter."}, {"part": "while (true)", "explanation": "A loop that never ends on its own."}, {"part": "i++;", "explanation": "Counts each pass."}, {"part": "if (i == 3) { break; }", "explanation": "Leaves the loop on the third pass."}]'),
(210, 7, 'Level 12', 'LOOPS AND BRANCHING', 'The Skipping Stone', 'The continue statement skips the current iteration of a for, while or do-while loop. The unlabeled form jumps to the end of the innermost loop\'s body and evaluates the boolean expression that controls the loop, skipping the rest of that iteration.

Write a for loop with int i = 0, i < 5 and i++. If i == 2, continue. Otherwise print i. The output is 0134.', 'Put continue; inside the if, and the print after it.', 'for (int i = 0; i < 5; i++) { if (i == 2) { continue; } System.out.print(i); }', 60, 8, 12, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: for (int i = 0; i < 5; i++) { if (i == 2) { continue; } System.out.print(i); }', 'for\\s*\\(\\s*int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+5;\\s+i\\+\\+\\s*\\)\\s*\\{\\s*if\\s*\\(\\s*i\\s+==\\s+2\\s*\\)\\s*\\{\\s*continue;\\s*\\}\\s*System\\.out\\.print\\(\\s*i\\s*\\);\\s*\\}', '/assets/landscapes/oakheart4.png', 'The Unlabeled continue', 'The continue statement skips the current iteration of a for, while or do-while loop. The unlabeled form jumps to the end of the innermost loop\'s body and evaluates the boolean expression that controls the loop, skipping the rest of that iteration.

Write a for loop with int i = 0, i < 5 and i++. If i == 2, continue. Otherwise print i. The output is 0134.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'for (int i = 0; i < 5; i++) { if (i == 2) { continue; } System.out.print(i); }', '[{"part": "for (int i = 0; i < 5; i++)", "explanation": "Visits 0, 1, 2, 3 and 4."}, {"part": "if (i == 2) { continue; }", "explanation": "When i is 2, skip the rest of this pass."}, {"part": "System.out.print(i);", "explanation": "Runs for every value except 2, so the output is 0134."}]'),
(211, 7, 'Level 13', 'LOOPS AND BRANCHING', 'The Beah Counter', 'continue can filter items out. In the guide, the loop counts the "Beah" entries in a names array. If the current name is not "Beah", continue skips the count++ line, so only the matching names are counted.

Assume names and count already exist. Write a for loop over names.length that continues when !names[i].equals("Beah"), and otherwise runs count++.', 'The ! flips the result of equals.', 'for (int i = 0; i < names.length; i++) { if (!names[i].equals("Beah")) { continue; } count++; }', 60, 8, 13, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: for (int i = 0; i < names.length; i++) { if (!names[i].equals("Beah")) { continue; } count++; }', 'for\\s*\\(\\s*int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+names\\.length;\\s+i\\+\\+\\s*\\)\\s*\\{\\s*if\\s*\\(\\s*!names\\[i\\]\\.equals\\(\\s*"Beah"\\s*\\)\\s*\\)\\s*\\{\\s*continue;\\s*\\}\\s*count\\+\\+;\\s*\\}', '/assets/landscapes/oakheart1.png', 'Counting With continue', 'continue can filter items out. In the guide, the loop counts the "Beah" entries in a names array. If the current name is not "Beah", continue skips the count++ line, so only the matching names are counted.

Assume names and count already exist. Write a for loop over names.length that continues when !names[i].equals("Beah"), and otherwise runs count++.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'for (int i = 0; i < names.length; i++) { if (!names[i].equals("Beah")) { continue; } count++; }', '[{"part": "for (int i = 0; i < names.length; i++)", "explanation": "Visits every name."}, {"part": "if (!names[i].equals(\\"Beah\\"))", "explanation": "The ! means not. This is true for every name that is not Beah."}, {"part": "continue;", "explanation": "Skips the count++ line for those names."}, {"part": "count++;", "explanation": "Only reached when the name is Beah."}]'),
(212, 7, 'Level 14', 'LOOPS AND BRANCHING', 'The Labeled Gate', 'The labeled break terminates an outer statement that is identified by a label. A label is a name followed by a colon, placed just before the outer loop. The break terminates the labeled statement, and it does not jump to the label: control continues with the statement right after the labeled loop. A plain break would only end the inner loop.

Write two nested for loops. Label the outer loop searchLabel:. Both use a limit of 3 with variables i and j. When i + j == 3, break searchLabel.', 'searchLabel: for (...) { for (...) { ... break searchLabel; } }', 'searchLabel: for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (i + j == 3) { break searchLabel; } } }', 60, 8, 14, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'searchLabel:\\s+for\\s*\\(int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+3;\\s+i\\+\\+\\)\\s*\\{\\s*for\\s*\\(int\\s+j\\s+=\\s+0;\\s+j\\s+<\\s+3;\\s+j\\+\\+\\)\\s*\\{\\s*if\\s*\\(i\\s+\\+\\s+j\\s+==\\s+3\\)\\s*\\{\\s*break\\s+searchLabel;\\s*\\}\\s*\\}\\s*\\}', '/assets/landscapes/oakheart2.png', 'The Labeled break', 'The labeled break terminates an outer statement that is identified by a label. A label is a name followed by a colon, placed just before the outer loop. The break terminates the labeled statement, and it does not jump to the label: control continues with the statement right after the labeled loop. A plain break would only end the inner loop.

Write two nested for loops. Label the outer loop searchLabel:. Both use a limit of 3 with variables i and j. When i + j == 3, break searchLabel.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'searchLabel: for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (i + j == 3) { break searchLabel; } } }', '[{"part": "searchLabel:", "explanation": "The label. It names the outer loop."}, {"part": "for (int i = 0; i < 3; i++)", "explanation": "The outer loop."}, {"part": "for (int j = 0; j < 3; j++)", "explanation": "The inner loop."}, {"part": "if (i + j == 3) { break searchLabel; }", "explanation": "Terminates the labeled outer loop, not just the inner one."}]'),
(213, 7, 'Level 15', 'LOOPS AND BRANCHING', 'The Outer Skip', 'The labeled continue skips the current iteration of an outer loop marked with a label. In the guide, whenever j == 2 the program jumps to the next iteration of the outer loop, so anything written after the inner loop never runs.

Write two nested for loops with limits of 5, using i and j. Label the outer loop outerLoop:. When j == 2, continue outerLoop.', 'continue outerLoop;  The label name is case sensitive.', 'outerLoop: for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { if (j == 2) { continue outerLoop; } } }', 60, 8, 15, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'outerLoop:\\s+for\\s*\\(int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+5;\\s+i\\+\\+\\)\\s*\\{\\s*for\\s*\\(int\\s+j\\s+=\\s+0;\\s+j\\s+<\\s+5;\\s+j\\+\\+\\)\\s*\\{\\s*if\\s*\\(j\\s+==\\s+2\\)\\s*\\{\\s*continue\\s+outerLoop;\\s*\\}\\s*\\}\\s*\\}', '/assets/landscapes/oakheart3.png', 'The Labeled continue', 'The labeled continue skips the current iteration of an outer loop marked with a label. In the guide, whenever j == 2 the program jumps to the next iteration of the outer loop, so anything written after the inner loop never runs.

Write two nested for loops with limits of 5, using i and j. Label the outer loop outerLoop:. When j == 2, continue outerLoop.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'outerLoop: for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { if (j == 2) { continue outerLoop; } } }', '[{"part": "outerLoop:", "explanation": "The label that names the outer loop."}, {"part": "for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { ... } }", "explanation": "The outer and inner loops."}, {"part": "if (j == 2) { continue outerLoop; }", "explanation": "Skips the rest of the inner loop and moves on to the next pass of the outer loop."}]'),
(214, 7, 'Level 16', 'LOOPS AND BRANCHING', 'The Return Gift', 'The return statement exits the current method, and control goes back to the statement that follows the method call. To return a value, put the value after the return keyword. The type of the value must match the return type in the method\'s declaration. The guide\'s example is return "Hello";. Methods are covered later, so the method header is provided here.

Write a method named greet with the return type String, whose body returns "Hello".', 'static String greet() { return "Hello"; }', 'static String greet() { return "Hello"; }', 60, 8, 16, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: static String greet() { return "Hello"; }', 'static\\s+String\\s+greet\\(\\s*\\s*\\)\\s*\\{\\s*return\\s+"Hello";\\s*\\}', '/assets/landscapes/oakheart4.png', 'return With a Value', 'The return statement exits the current method, and control goes back to the statement that follows the method call. To return a value, put the value after the return keyword. The type of the value must match the return type in the method\'s declaration. The guide\'s example is return "Hello";. Methods are covered later, so the method header is provided here.

Write a method named greet with the return type String, whose body returns "Hello".', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'static String greet() { return "Hello"; }', '[{"part": "static String greet()", "explanation": "A method that promises to return a String."}, {"part": "return \\"Hello\\";", "explanation": "Exits the method and hands back the value \\"Hello\\". Its type matches String."}]'),
(215, 7, 'Level 17', 'LOOPS AND BRANCHING', 'The Silent Exit', 'When a method is declared void, it returns no value, so you use the form of return that has none: return; It simply exits the method and gives control back to the caller.

Write a void method named stop whose body is just return;', 'A void method uses return; with nothing after it.', 'static void stop() { return; }', 60, 8, 17, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: static void stop() { return; }', 'static\\s+void\\s+stop\\(\\s*\\s*\\)\\s*\\{\\s*return;\\s*\\}', '/assets/landscapes/oakheart1.png', 'return Without a Value', 'When a method is declared void, it returns no value, so you use the form of return that has none: return; It simply exits the method and gives control back to the caller.

Write a void method named stop whose body is just return;', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'static void stop() { return; }', '[{"part": "static void stop()", "explanation": "A method that returns no value."}, {"part": "return;", "explanation": "Exits the method without handing back anything."}]'),
(216, 7, 'Level 18', 'LOOPS AND BRANCHING', 'The Counter Return', 'You can also return an expression that calculates the value. return ++count; first increments count and then returns the new value. The type of the expression must match the method\'s declared return type.

Write an int method named next with an int parameter named count, whose body returns ++count.', 'static int next(int count) { return ++count; }', 'static int next(int count) { return ++count; }', 60, 8, 18, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: static int next(int count) { return ++count; }', 'static\\s+int\\s+next\\(\\s*int\\s+count\\s*\\)\\s*\\{\\s*return\\s+\\+\\+count;\\s*\\}', '/assets/landscapes/oakheart2.png', 'Returning an Expression', 'You can also return an expression that calculates the value. return ++count; first increments count and then returns the new value. The type of the expression must match the method\'s declared return type.

Write an int method named next with an int parameter named count, whose body returns ++count.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'static int next(int count) { return ++count; }', '[{"part": "static int next(int count)", "explanation": "A method that takes an int and promises to return an int."}, {"part": "return ++count;", "explanation": "Adds 1 to count and returns the new value."}]'),
(217, 7, 'Level 19', 'LOOPS AND BRANCHING', 'The Number Grid', 'Pip reaches the final vault, which holds a grid of numbers. The guide searches a two-dimensional array with two nested loops. First comes the setup. A grid is an array of rows, written with double square brackets, int[][], and each row sits in its own pair of braces. Then searchNum holds the value to look for, and foundNum starts as false.

Declare int[][] numbers with the rows {1, 2, 3}, {4, 5, 6} and {7, 8, 9}. Then declare int searchNum = 5 and boolean foundNum = false.', 'int[][] numbers = {{...}, {...}, {...}};', 'int[][] numbers = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}; int searchNum = 5; boolean foundNum = false;', 60, 8, 19, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'int\\[\\]\\[\\]\\s+numbers\\s+=\\s*\\{\\{1,\\s*2,\\s*3\\},\\s*\\{4,\\s*5,\\s*6\\},\\s*\\{7,\\s*8,\\s*9\\}\\};\\s+int\\s+searchNum\\s+=\\s+5;\\s+boolean\\s+foundNum\\s+=\\s+false;', '/assets/landscapes/oakheart3.png', 'A Two-Dimensional Array', 'Pip reaches the final vault, which holds a grid of numbers. The guide searches a two-dimensional array with two nested loops. First comes the setup. A grid is an array of rows, written with double square brackets, int[][], and each row sits in its own pair of braces. Then searchNum holds the value to look for, and foundNum starts as false.

Declare int[][] numbers with the rows {1, 2, 3}, {4, 5, 6} and {7, 8, 9}. Then declare int searchNum = 5 and boolean foundNum = false.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int[][] numbers = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}; int searchNum = 5; boolean foundNum = false;', '[{"part": "int[][] numbers", "explanation": "A two-dimensional array: an array of int arrays."}, {"part": "{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}", "explanation": "Three rows, each in its own braces, all inside an outer pair of braces."}, {"part": "int searchNum = 5;", "explanation": "The value to look for."}, {"part": "boolean foundNum = false;", "explanation": "Becomes true once the value is found."}]'),
(218, 7, 'Level 20', 'LOOPS AND BRANCHING', 'The Vault Search', 'At the vault, two nested loops walk through every row and every column of the grid. When the value is found, the program sets foundNum to true and uses a labeled break to terminate the outer loop at once, instead of only the inner one. The guide labels the outer loop searchLabel.

Assume numbers, searchNum and foundNum already exist. Label the outer for loop searchLabel:, loop with i < numbers.length and j < numbers[i].length, and when searchNum == numbers[i][j], set foundNum = true and break searchLabel.', 'Outer loop over numbers.length, inner loop over numbers[i].length.', 'searchLabel: for (int i = 0; i < numbers.length; i++) { for (int j = 0; j < numbers[i].length; j++) { if (searchNum == numbers[i][j]) { foundNum = true; break searchLabel; } } }', 100, 8, 20, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'searchLabel:\\s+for\\s*\\(int\\s+i\\s+=\\s+0;\\s+i\\s+<\\s+numbers\\.length;\\s+i\\+\\+\\)\\s*\\{\\s*for\\s*\\(int\\s+j\\s+=\\s+0;\\s+j\\s+<\\s+numbers\\[i\\]\\.length;\\s+j\\+\\+\\)\\s*\\{\\s*if\\s*\\(searchNum\\s+==\\s+numbers\\[i\\]\\[j\\]\\)\\s*\\{\\s*foundNum\\s+=\\s+true;\\s+break\\s+searchLabel;\\s*\\}\\s*\\}\\s*\\}', '/assets/landscapes/oakheart4.png', 'A Labeled break Search', 'At the vault, two nested loops walk through every row and every column of the grid. When the value is found, the program sets foundNum to true and uses a labeled break to terminate the outer loop at once, instead of only the inner one. The guide labels the outer loop searchLabel.

Assume numbers, searchNum and foundNum already exist. Label the outer for loop searchLabel:, loop with i < numbers.length and j < numbers[i].length, and when searchNum == numbers[i][j], set foundNum = true and break searchLabel.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'searchLabel: for (int i = 0; i < numbers.length; i++) { for (int j = 0; j < numbers[i].length; j++) { if (searchNum == numbers[i][j]) { foundNum = true; break searchLabel; } } }', '[{"part": "searchLabel:", "explanation": "The label on the outer loop."}, {"part": "for (int i = 0; i < numbers.length; i++)", "explanation": "Goes through every row."}, {"part": "for (int j = 0; j < numbers[i].length; j++)", "explanation": "Goes through every column of the current row."}, {"part": "if (searchNum == numbers[i][j])", "explanation": "True when the current cell holds the number being searched."}, {"part": "foundNum = true; break searchLabel;", "explanation": "Records the result and terminates the labeled outer loop."}]');

-- 4) Guided-mode multiple choice (one step per lesson, like Islands 3 to 6).
--    Rows are cleared first so re-running this file never hits uq_guided_lesson_step.
DELETE FROM `guided_steps` WHERE `lesson_id` BETWEEN 199 AND 218;

INSERT INTO `guided_steps` (`lesson_id`, `step_order`, `prompt`, `correct_snippet`, `distractor_1`, `distractor_2`, `distractor_3`) VALUES
(199, 1, 'Which code prints 4321 with a while loop and then stops?', 'int i = 4; while (i > 0) { System.out.print(i); i--; }', 'int i = 4; while (i > 0) { System.out.print(i); }', 'int i = 4; while (i > 0) { System.out.print(i); i++; }', 'int i = 4; while i > 0 { System.out.print(i); i--; }'),
(200, 1, 'Which loop prints 123 and then terminates?', 'int count = 1; while (count <= 3) { System.out.print(count); count++; }', 'int count = 1; while (count <= 3) { System.out.print(count); }', 'int count = 1; while (count <= 3) { System.out.print(count); count--; }', 'int count = 1; while (count >= 3) { System.out.print(count); count++; }'),
(201, 1, 'Which do-while loop prints 012?', 'int i = 0; do { System.out.print(i); i++; } while (i < 3);', 'int i = 0; do { System.out.print(i); i++; } while (i < 3)', 'int i = 0; do { System.out.print(i); i++; } until (i < 3);', 'int i = 0; do while (i < 3) { System.out.print(i); i++; }'),
(202, 1, 'Which loop prints Once exactly one time even though i < 5 is false?', 'int i = 10; do { System.out.println("Once"); } while (i < 5);', 'int i = 10; while (i < 5) { System.out.println("Once"); }', 'int i = 10; do { System.out.println("Once"); } while (i > 5);', 'int i = 10; do { System.out.println("Once"); } while (i < 5)'),
(203, 1, 'Which for loop prints the numbers 0 to 9?', 'int i; for (i = 0; i < 10; i++) { System.out.print(i); }', 'int i; for (i = 0, i < 10, i++) { System.out.print(i); }', 'int i; for (i = 0; i < 10) { System.out.print(i); }', 'int i; for (i = 0; i > 10; i++) { System.out.print(i); }'),
(204, 1, 'Which while loop does the same as for (i = 0; i < 10; i++) printing i?', 'int i = 0; while (i < 10) { System.out.print(i); i++; }', 'int i = 0; while (i < 10) { i++; System.out.print(i); }', 'int i = 0; while (i < 10) { System.out.print(i); }', 'int i = 0; while (i <= 10) { System.out.print(i); i++; }'),
(205, 1, 'Which for loop prints 54321?', 'for (int i = 5; i > 0; i--) { System.out.print(i); }', 'for (int i = 5; i > 0; i++) { System.out.print(i); }', 'for (int i = 5; i < 0; i--) { System.out.print(i); }', 'for (int i = 5; i > 0; i--;) { System.out.print(i); }'),
(206, 1, 'Which for loop prints 02468?', 'for (int i = 0; i < 10; i += 2) { System.out.print(i); }', 'for (int i = 0; i < 10; i + 2) { System.out.print(i); }', 'for (int i = 0; i < 10; i =+ 2) { System.out.print(i); }', 'for (int i = 0; i < 10; i += 2;) { System.out.print(i); }'),
(207, 1, 'Which loop stops completely as soon as i is 5?', 'for (int i = 0; i < 10; i++) { if (i == 5) { break; } }', 'for (int i = 0; i < 10; i++) { if (i = 5) { break; } }', 'for (int i = 0; i < 10; i++) { if (i == 5) { stop; } }', 'for (int i = 0; i < 10; i++) { if (i == 5) { continue; } }'),
(208, 1, 'Which loop sets foundName to true and stops searching when the name is found?', 'for (int i = 0; i < names.length; i++) { if (names[i].equals(searchName)) { foundName = true; break; } }', 'for (int i = 0; i < names.length(); i++) { if (names[i].equals(searchName)) { foundName = true; break; } }', 'for (int i = 0; i < names.length; i++) { if (names[i].equals(searchName)) { foundName = true; continue; } }', 'for (int i = 0; i < names.length; i++) { if (names[i].equals(searchName)) { foundName = true; break } }'),
(209, 1, 'Which loop uses break to leave a while (true) loop when i reaches 3?', 'int i = 0; while (true) { i++; if (i == 3) { break; } }', 'int i = 0; while (true) { i++; if (i == 3) { } }', 'int i = 0; while (true) { i++; if (i == 3) { break } }', 'int i = 0; while (false) { i++; if (i == 3) { break; } }'),
(210, 1, 'Which loop prints 0134?', 'for (int i = 0; i < 5; i++) { if (i == 2) { continue; } System.out.print(i); }', 'for (int i = 0; i < 5; i++) { if (i == 2) { break; } System.out.print(i); }', 'for (int i = 0; i < 5; i++) { if (i == 2) { continue; System.out.print(i); } }', 'for (int i = 0; i < 5; i++) { if (i == 2) { continue } System.out.print(i); }'),
(211, 1, 'Which loop counts only the names equal to "Beah"?', 'for (int i = 0; i < names.length; i++) { if (!names[i].equals("Beah")) { continue; } count++; }', 'for (int i = 0; i < names.length; i++) { if (names[i].equals("Beah")) { continue; } count++; }', 'for (int i = 0; i < names.length; i++) { if (!names[i].equals("Beah")) { break; } count++; }', 'for (int i = 0; i < names.length(); i++) { if (!names[i].equals("Beah")) { continue; } count++; }'),
(212, 1, 'Which code ends both loops at once when i + j == 3?', 'searchLabel: for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (i + j == 3) { break searchLabel; } } }', 'searchLabel: for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (i + j == 3) { break; } } }', 'searchLabel: for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (i + j == 3) { break searchLabel: } } }', 'searchLabel for (int i = 0; i < 3; i++) { for (int j = 0; j < 3; j++) { if (i + j == 3) { break searchLabel; } } }'),
(213, 1, 'Which code jumps to the next pass of the outer loop when j == 2?', 'outerLoop: for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { if (j == 2) { continue outerLoop; } } }', 'outerLoop: for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { if (j == 2) { continue; } } }', 'outerLoop: for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { if (j == 2) { continue: outerLoop; } } }', 'outerLoop: for (int i = 0; i < 5; i++) { for (int j = 0; j < 5; j++) { if (j == 2) { continue outerloop; } } }'),
(214, 1, 'Which method correctly returns the String "Hello"?', 'static String greet() { return "Hello"; }', 'static String greet() { return Hello; }', 'static int greet() { return "Hello"; }', 'static String greet() { return "Hello" }'),
(215, 1, 'Which void method exits with a plain return statement?', 'static void stop() { return; }', 'static void stop() { return 0; }', 'static void stop() { return }', 'static stop() { return; }'),
(216, 1, 'Which method increments count first and then returns the new value?', 'static int next(int count) { return ++count; }', 'static int next(int count) { return count++; }', 'static void next(int count) { return ++count; }', 'static int next(int count) { return ++count }'),
(217, 1, 'Which code declares the 3 by 3 grid, the search number 5 and a flag that starts as false?', 'int[][] numbers = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}; int searchNum = 5; boolean foundNum = false;', 'int[] numbers = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}; int searchNum = 5; boolean foundNum = false;', 'int[][] numbers = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}; int searchNum = 5; boolean foundNum = true;', 'int[][] numbers = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]; int searchNum = 5; boolean foundNum = false;'),
(218, 1, 'Which search stops both loops as soon as searchNum is found?', 'searchLabel: for (int i = 0; i < numbers.length; i++) { for (int j = 0; j < numbers[i].length; j++) { if (searchNum == numbers[i][j]) { foundNum = true; break searchLabel; } } }', 'searchLabel: for (int i = 0; i < numbers.length; i++) { for (int j = 0; j < numbers[i].length; j++) { if (searchNum == numbers[i][j]) { foundNum = true; break; } } }', 'searchLabel: for (int i = 0; i < numbers.length; i++) { for (int j = 0; j < numbers[i].length(); j++) { if (searchNum == numbers[i][j]) { foundNum = true; break searchLabel; } } }', 'searchLabel: for (int i = 0; i < numbers.length; i++) { for (int j = 0; j < numbers[i].length; j++) { if (searchNum = numbers[i][j]) { foundNum = true; break searchLabel; } } }');

ALTER TABLE `lessons` AUTO_INCREMENT=219;
