-- ============================================================
-- ISLAND 5: GETTING INPUT  (Chapter 7 + Chapter 8)
-- 20 levels. Lesson ids 159-178, module_id 5.
-- Levels 1-6   = Chapter 7 (BufferedReader and Keyboard.java)
-- Levels 7-12  = Chapter 7 (JOptionPane)
-- Levels 13-18 = Chapter 8 (Utility Scanner)
-- Levels 19-20 = Chapter 8 (Reading from a Text File)
-- ============================================================

-- 1) The lessons table has a foreign key to lesson_modules, so module 5 must exist first.
--    (Copy the column list from your own module 4 row. Example only, adjust the columns to match your table:)
-- INSERT INTO `lesson_modules` (`id`, `title`, ...) VALUES (5, 'Getting Input', ...);

-- If a run stops with "#1406 Data too long for column ...", check the column sizes with
--   SHOW COLUMNS FROM `lessons`;
-- and widen the short ones (keep NOT NULL if your table has it), for example:
-- ALTER TABLE `lessons` MODIFY `required_code_label` VARCHAR(255), MODIFY `required_code_pattern` VARCHAR(500), MODIFY `goal` VARCHAR(500), MODIFY `solution_code` VARCHAR(500);

-- 2) Clear any existing Island 5 rows so re-running this file never hits
--    "Duplicate entry '5-1' for key 'uq_lessons_module_order'".
--    First look at what is there:
--      SELECT id, module_id, order_index, title FROM lessons WHERE module_id = 5 OR id >= 159;
-- Removes the old Island 5 snippets, including any old rows that sit on ids 159-178
-- under a different module_id (those would otherwise cause a primary-key error).
DELETE FROM `lessons` WHERE `module_id` = 5 OR `id` BETWEEN 159 AND 178;

-- OPTIONAL: if players already have saved progress for the OLD lessons 159-178, the new
-- levels would show as already completed. Clear it with your progress table's real name, e.g.:
-- DELETE FROM `user_progress` WHERE `lesson_id` BETWEEN 159 AND 178;

-- 3) The lessons
INSERT INTO `lessons` (`id`, `module_id`, `level_label`, `track`, `title`, `briefing`, `hint`, `goal`, `xp_reward`, `target_tiles`, `order_index`, `is_active`, `created_at`, `min_moves`, `min_says`, `min_jumps`, `required_code_label`, `required_code_pattern`, `background_image`, `subtitle`, `description`, `grid_cols`, `grid_rows`, `mechanics_config`, `total_tiles`, `ground_fraction`, `initial_tile`, `flag_tile`, `solution_code`, `line_breakdown`) VALUES
(159, 5, 'Level 1', 'GETTING INPUT', 'The Package Gate', 'Pip reaches Keystone Isle, where a stone gate is carved with the name java.io. Java uses an application programming interface (API), a set of predefined classes you can use in your programs. These classes are organized into packages, and the java.io package holds the classes that let programs input and output data, including BufferedReader. The import statement loads classes from a package, and java.io.* loads every class in it.

Import all the classes in the java.io package.', 'import, then java.io.* and a semicolon.', 'import java.io.*;', 50, 8, 1, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: import java.io.*;', 'import\\s+java\\.io\\.\\*;', '/assets/landscapes/oakheart1.png', 'Importing a Package', 'Pip reaches Keystone Isle, where a stone gate is carved with the name java.io. Java uses an application programming interface (API), a set of predefined classes you can use in your programs. These classes are organized into packages, and the java.io package holds the classes that let programs input and output data, including BufferedReader. The import statement loads classes from a package, and java.io.* loads every class in it.

Import all the classes in the java.io package.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'import java.io.*;', '[{"part": "import", "explanation": "The keyword that tells Java you want to use classes from another package."}, {"part": "java.io", "explanation": "The package that contains the classes for input and output."}, {"part": ".*", "explanation": "The wildcard that loads every class found in the package."}, {"part": ";", "explanation": "Ends the statement."}]'),
(160, 5, 'Level 2', 'GETTING INPUT', 'The Reader Rune', 'A glowing rune on the gate listens for the keyboard. To get input from the keyboard you need a BufferedReader, a class from the java.io package. The guide says not to worry about what every part of the syntax means yet, so copy the pattern: declare a variable named dataIn of the class type BufferedReader and connect it to System.in, which is the keyboard.

Declare a BufferedReader named dataIn that reads from System.in.', 'new BufferedReader(new InputStreamReader(System.in))', 'BufferedReader dataIn = new BufferedReader(new InputStreamReader(System.in));', 50, 8, 2, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: BufferedReader dataIn = new BufferedReader(new InputStreamReader(System.in));', 'BufferedReader\\s+dataIn\\s+=\\s+new\\s+BufferedReader\\(\\s*new\\s+InputStreamReader\\(\\s*System\\.in\\s*\\)\\s*\\);', '/assets/landscapes/oakheart2.png', 'Creating a BufferedReader', 'A glowing rune on the gate listens for the keyboard. To get input from the keyboard you need a BufferedReader, a class from the java.io package. The guide says not to worry about what every part of the syntax means yet, so copy the pattern: declare a variable named dataIn of the class type BufferedReader and connect it to System.in, which is the keyboard.

Declare a BufferedReader named dataIn that reads from System.in.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'BufferedReader dataIn = new BufferedReader(new InputStreamReader(System.in));', '[{"part": "BufferedReader dataIn", "explanation": "Declares a variable named dataIn with the class type BufferedReader."}, {"part": "=", "explanation": "Stores the new object in the variable."}, {"part": "new BufferedReader(", "explanation": "Creates a new BufferedReader object."}, {"part": "new InputStreamReader(System.in)", "explanation": "Connects the reader to System.in, the keyboard."}, {"part": ");", "explanation": "Closes both pairs of parentheses and ends the statement."}]'),
(161, 5, 'Level 3', 'GETTING INPUT', 'The Empty Scroll', 'The rune needs somewhere to keep what it hears. Declare a temporary String variable to store the input and initialize it to an empty String "". The coding guidelines say it is always good to initialize your variables as you declare them. Then ask the question with System.out.print, which shows the prompt and stays on the same line so the user types right after it.

Declare a String named name set to an empty String, then print the prompt Please Enter Your Name:', 'String name = ""; then System.out.print("Please Enter Your Name:");', 'String name = ""; System.out.print("Please Enter Your Name:");', 50, 8, 3, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: String name = ""; System.out.print("Please Enter Your Name:");', 'String\\s+name\\s+=\\s+"";\\s+System\\.out\\.print\\(\\s*"Please\\s+Enter\\s+Your\\s+Name:"\\s*\\);', '/assets/landscapes/oakheart3.png', 'A Variable for the Input', 'The rune needs somewhere to keep what it hears. Declare a temporary String variable to store the input and initialize it to an empty String "". The coding guidelines say it is always good to initialize your variables as you declare them. Then ask the question with System.out.print, which shows the prompt and stays on the same line so the user types right after it.

Declare a String named name set to an empty String, then print the prompt Please Enter Your Name:', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String name = ""; System.out.print("Please Enter Your Name:");', '[{"part": "String name = \\"\\";", "explanation": "Declares a String and initializes it to an empty String, ready to store the input."}, {"part": "System.out.print(", "explanation": "Prints without adding a newline, so the user types next to the prompt."}, {"part": "\\"Please Enter Your Name:\\"", "explanation": "The prompt text shown on screen."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(162, 5, 'Level 4', 'GETTING INPUT', 'The Catch Net', 'To read a line from the keyboard, call the readLine() method of the BufferedReader. It gets the input and returns a String. Reading can fail, so the call has to sit inside a try-catch block that catches the possible IOException. For now, just take note that you need this block to use readLine(). The returned String is saved in the name variable.

Inside a try block, store dataIn.readLine() in name. In the catch block for IOException e, print Error!', 'try { ... } catch (IOException e) { ... }', 'try { name = dataIn.readLine(); } catch (IOException e) { System.out.println("Error!"); }', 50, 8, 4, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: try { name = dataIn.readLine(); } catch (IOException e) { System.out.println("Error!"); }', 'try\\s*\\{\\s*name\\s+=\\s+dataIn\\.readLine\\(\\s*\\s*\\);\\s*\\}\\s*catch\\s*\\(\\s*IOException\\s+e\\s*\\)\\s*\\{\\s*System\\.out\\.println\\(\\s*"Error!"\\s*\\);\\s*\\}', '/assets/landscapes/oakheart4.png', 'try-catch and readLine()', 'To read a line from the keyboard, call the readLine() method of the BufferedReader. It gets the input and returns a String. Reading can fail, so the call has to sit inside a try-catch block that catches the possible IOException. For now, just take note that you need this block to use readLine(). The returned String is saved in the name variable.

Inside a try block, store dataIn.readLine() in name. In the catch block for IOException e, print Error!', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'try { name = dataIn.readLine(); } catch (IOException e) { System.out.println("Error!"); }', '[{"part": "try {", "explanation": "Starts the block of code that might cause an exception."}, {"part": "name = dataIn.readLine();", "explanation": "Reads one line typed on the keyboard and stores the returned String in name."}, {"part": "} catch (IOException e) {", "explanation": "If an IOException happens, Java jumps here instead of crashing."}, {"part": "System.out.println(\\"Error!\\");", "explanation": "The message shown when reading fails."}, {"part": "}", "explanation": "Closes the catch block."}]'),
(163, 5, 'Level 5', 'GETTING INPUT', 'The Greeting Gate', 'The gate swings open and greets Pip\'s helper by name. Now that name holds the user\'s input, one last statement joins the text "Hello ", the variable name and "!" together with the + operator and prints the greeting on its own line. If the user typed Pip, the screen shows Hello Pip!

Print Hello, then name, then an exclamation mark with System.out.println.', 'Join three pieces with +: "Hello ", name and "!".', 'System.out.println("Hello " + name + "!");', 50, 8, 5, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: System.out.println("Hello " + name + "!");', 'System\\.out\\.println\\(\\s*"Hello\\s+"\\s+\\+\\s+name\\s+\\+\\s+"!"\\s*\\);', '/assets/landscapes/oakheart1.png', 'Greeting the Player', 'The gate swings open and greets Pip\'s helper by name. Now that name holds the user\'s input, one last statement joins the text "Hello ", the variable name and "!" together with the + operator and prints the greeting on its own line. If the user typed Pip, the screen shows Hello Pip!

Print Hello, then name, then an exclamation mark with System.out.println.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'System.out.println("Hello " + name + "!");', '[{"part": "System.out.println(", "explanation": "Prints the value and then adds a newline."}, {"part": "\\"Hello \\"", "explanation": "A String literal. The space inside the quotes separates Hello from the name."}, {"part": "+ name", "explanation": "Joins the value stored in name. There are no quotes, so the value is used, not the word name."}, {"part": "+ \\"!\\"", "explanation": "Adds an exclamation mark at the end."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(164, 5, 'Level 6', 'GETTING INPUT', 'The Keyboard Relic', 'In a chest Pip finds a ready-made class, Keyboard.java, that hides the BufferedReader and the try-catch for you. Save Keyboard.java in the same folder as your program so it can load Keyboard.class. Then you can call readInt(), readLong(), readFloat(), readDouble(), readChar(), readString() and readBoolean(). In the sample program, the prompt Enter an integer: is printed and the answer is stored in an int named num.

Print the prompt Enter an integer: with println, then store Keyboard.readInt() in an int named num.', 'The method is readInt, and it needs empty parentheses.', 'System.out.println("Enter an integer: "); int num = Keyboard.readInt();', 50, 8, 6, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: System.out.println("Enter an integer: "); int num = Keyboard.readInt();', 'System\\.out\\.println\\(\\s*"Enter\\s+an\\s+integer:\\s+"\\s*\\);\\s+int\\s+num\\s+=\\s+Keyboard\\.readInt\\(\\s*\\s*\\);', '/assets/landscapes/oakheart2.png', 'Using Keyboard.java', 'In a chest Pip finds a ready-made class, Keyboard.java, that hides the BufferedReader and the try-catch for you. Save Keyboard.java in the same folder as your program so it can load Keyboard.class. Then you can call readInt(), readLong(), readFloat(), readDouble(), readChar(), readString() and readBoolean(). In the sample program, the prompt Enter an integer: is printed and the answer is stored in an int named num.

Print the prompt Enter an integer: with println, then store Keyboard.readInt() in an int named num.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'System.out.println("Enter an integer: "); int num = Keyboard.readInt();', '[{"part": "System.out.println(\\"Enter an integer: \\");", "explanation": "Asks the user to type a whole number."}, {"part": "int num", "explanation": "Declares an int variable to hold the answer."}, {"part": "=", "explanation": "Stores the returned value in num."}, {"part": "Keyboard.readInt()", "explanation": "Reads a line from the keyboard and returns it as an int."}, {"part": ";", "explanation": "Ends the statement."}]'),
(165, 5, 'Level 7', 'GETTING INPUT', 'The Swing Gate', 'Pip leaves the keyboard behind and finds a glass door that opens with pop-up windows. Another way to get input is the JOptionPane class, found in the javax.swing package. JOptionPane makes it easy to pop up a standard dialog box that prompts users for a value or informs them of something. Import the class before you use it.

Import JOptionPane from the javax.swing package.', 'The class name comes after javax.swing.', 'import javax.swing.JOptionPane;', 50, 8, 7, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: import javax.swing.JOptionPane;', 'import\\s+javax\\.swing\\.(JOptionPane|\\*);', '/assets/landscapes/oakheart3.png', 'Importing JOptionPane', 'Pip leaves the keyboard behind and finds a glass door that opens with pop-up windows. Another way to get input is the JOptionPane class, found in the javax.swing package. JOptionPane makes it easy to pop up a standard dialog box that prompts users for a value or informs them of something. Import the class before you use it.

Import JOptionPane from the javax.swing package.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'import javax.swing.JOptionPane;', '[{"part": "import", "explanation": "Tells Java you want to use a class from another package."}, {"part": "javax.swing", "explanation": "The package that contains JOptionPane."}, {"part": ".JOptionPane", "explanation": "Imports just this class. Writing javax.swing.* would load every class in the package."}, {"part": ";", "explanation": "Ends the statement."}]'),
(166, 5, 'Level 8', 'GETTING INPUT', 'The Dialog Door', 'A glass door asks its question in a pop-up window. JOptionPane.showInputDialog() displays a dialog with a message, a text field and an OK button. Whatever the user types is always returned as a String, so you save it in a String variable.

Store the result of an input dialog that asks Please enter your name in a String named name.', 'The message goes inside the parentheses, in double quotes.', 'String name = JOptionPane.showInputDialog("Please enter your name");', 50, 8, 8, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: String name = JOptionPane.showInputDialog("Please enter your name");', 'String\\s+name\\s+=\\s+JOptionPane\\.showInputDialog\\(\\s*"Please\\s+enter\\s+your\\s+name"\\s*\\);', '/assets/landscapes/oakheart4.png', 'Input Dialog Box', 'A glass door asks its question in a pop-up window. JOptionPane.showInputDialog() displays a dialog with a message, a text field and an OK button. Whatever the user types is always returned as a String, so you save it in a String variable.

Store the result of an input dialog that asks Please enter your name in a String named name.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String name = JOptionPane.showInputDialog("Please enter your name");', '[{"part": "String name", "explanation": "A String variable, because the dialog always returns a String."}, {"part": "=", "explanation": "Stores the returned value."}, {"part": "JOptionPane.showInputDialog(", "explanation": "Pops up a dialog with a text field and an OK button."}, {"part": "\\"Please enter your name\\"", "explanation": "The message shown above the text field."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(167, 5, 'Level 9', 'GETTING INPUT', 'The Message Bell', 'To show something to the player, use a message dialog. First build the greeting in a String named msg by joining "Hello ", name and "!". Then JOptionPane.showMessageDialog(null, msg) pops up a dialog with the message and an OK button. The null means no frame is given, so the program uses the default.

Assume name already holds the user\'s entry. Store the greeting in msg, then show it with showMessageDialog.', 'The first argument is null, then a comma, then msg.', 'String msg = "Hello " + name + "!"; JOptionPane.showMessageDialog(null, msg);', 50, 8, 9, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: String msg = "Hello " + name + "!"; JOptionPane.showMessageDialog(null, msg);', 'String\\s+msg\\s+=\\s+"Hello\\s+"\\s+\\+\\s+name\\s+\\+\\s+"!";\\s+JOptionPane\\.showMessageDialog\\(\\s*null,\\s*msg\\s*\\);', '/assets/landscapes/oakheart1.png', 'Message Dialog Box', 'To show something to the player, use a message dialog. First build the greeting in a String named msg by joining "Hello ", name and "!". Then JOptionPane.showMessageDialog(null, msg) pops up a dialog with the message and an OK button. The null means no frame is given, so the program uses the default.

Assume name already holds the user\'s entry. Store the greeting in msg, then show it with showMessageDialog.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String msg = "Hello " + name + "!"; JOptionPane.showMessageDialog(null, msg);', '[{"part": "String msg = \\"Hello \\" + name + \\"!\\";", "explanation": "Builds the greeting by joining text and the name variable."}, {"part": "JOptionPane.showMessageDialog(", "explanation": "Pops up a dialog that shows a message and an OK button."}, {"part": "null", "explanation": "No frame is given, so the default is used."}, {"part": "msg", "explanation": "The message to display."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(168, 5, 'Level 10', 'GETTING INPUT', 'The Conversion Altar', 'Whatever the user enters always comes back as a String. To keep it as text, do nothing. To use it as a number you must convert it first. Integer.parseInt() turns a String into an int. The same idea works for other types: Double.parseDouble(), Float.parseFloat() and Boolean.parseBoolean() convert to double, float and boolean. In the guide, the entry is saved in a String named userInput before it is converted.

Store an input dialog (message Enter) in a String named userInput, then convert it to an int named x.', 'Integer.parseInt(userInput)', 'String userInput = JOptionPane.showInputDialog("Enter"); int x = Integer.parseInt(userInput);', 50, 8, 10, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: String userInput = JOptionPane.showInputDialog("Enter"); int x = Integer.parseInt(userInput);', 'String\\s+userInput\\s+=\\s+JOptionPane\\.showInputDialog\\(\\s*"Enter"\\s*\\);\\s+int\\s+x\\s+=\\s+Integer\\.parseInt\\(\\s*userInput\\s*\\);', '/assets/landscapes/oakheart2.png', 'Converting a String to int', 'Whatever the user enters always comes back as a String. To keep it as text, do nothing. To use it as a number you must convert it first. Integer.parseInt() turns a String into an int. The same idea works for other types: Double.parseDouble(), Float.parseFloat() and Boolean.parseBoolean() convert to double, float and boolean. In the guide, the entry is saved in a String named userInput before it is converted.

Store an input dialog (message Enter) in a String named userInput, then convert it to an int named x.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String userInput = JOptionPane.showInputDialog("Enter"); int x = Integer.parseInt(userInput);', '[{"part": "String userInput = JOptionPane.showInputDialog(\\"Enter\\");", "explanation": "Saves whatever the user types as a String."}, {"part": "int x", "explanation": "An int variable to hold the converted number."}, {"part": "Integer.parseInt(userInput)", "explanation": "Converts the String into an int."}, {"part": ";", "explanation": "Ends the statement."}]'),
(169, 5, 'Level 11', 'GETTING INPUT', 'The Titled Dialog', 'A longer form of showInputDialog takes four arguments: a parent frame (null for the default), the message, a title for the title bar, and a dialog type. The dialog types are JOptionPane.ERROR_MESSAGE, INFORMATION_MESSAGE, PLAIN_MESSAGE, WARNING_MESSAGE and QUESTION_MESSAGE.

Show an input dialog with the message Enter your name, the title Entry Form and the INFORMATION_MESSAGE type.', 'Four arguments: null, message, title, JOptionPane.INFORMATION_MESSAGE.', 'JOptionPane.showInputDialog(null, "Enter your name", "Entry Form", JOptionPane.INFORMATION_MESSAGE);', 50, 8, 11, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'JOptionPane\\.showInputDialog\\(\\s*null,\\s*"Enter\\s+your\\s+name",\\s*"Entry\\s+Form",\\s*JOptionPane\\.INFORMATION_MESSAGE\\s*\\);', '/assets/landscapes/oakheart3.png', 'Input Dialog With a Title', 'A longer form of showInputDialog takes four arguments: a parent frame (null for the default), the message, a title for the title bar, and a dialog type. The dialog types are JOptionPane.ERROR_MESSAGE, INFORMATION_MESSAGE, PLAIN_MESSAGE, WARNING_MESSAGE and QUESTION_MESSAGE.

Show an input dialog with the message Enter your name, the title Entry Form and the INFORMATION_MESSAGE type.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'JOptionPane.showInputDialog(null, "Enter your name", "Entry Form", JOptionPane.INFORMATION_MESSAGE);', '[{"part": "null", "explanation": "No frame is given, so the default is used."}, {"part": "\\"Enter your name\\"", "explanation": "The message shown above the text field."}, {"part": "\\"Entry Form\\"", "explanation": "The text shown in the title bar."}, {"part": "JOptionPane.INFORMATION_MESSAGE", "explanation": "The dialog type, which picks the icon shown."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(170, 5, 'Level 12', 'GETTING INPUT', 'The Warning Bell', 'The message dialog also has a four-argument form: null, the message, a title and a dialog type. Choosing JOptionPane.ERROR_MESSAGE gives the dialog an error icon. Please note the three commas.

Show a message dialog with the message Wrong input, the title Error and the ERROR_MESSAGE type.', 'null, message, title, JOptionPane.ERROR_MESSAGE, separated by commas.', 'JOptionPane.showMessageDialog(null, "Wrong input", "Error", JOptionPane.ERROR_MESSAGE);', 50, 8, 12, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: JOptionPane.showMessageDialog(null, "Wrong input", "Error", JOptionPane.ERROR_MESSAGE);', 'JOptionPane\\.showMessageDialog\\(\\s*null,\\s*"Wrong\\s+input",\\s*"Error",\\s*JOptionPane\\.ERROR_MESSAGE\\s*\\);', '/assets/landscapes/oakheart4.png', 'Message Dialog With a Type', 'The message dialog also has a four-argument form: null, the message, a title and a dialog type. Choosing JOptionPane.ERROR_MESSAGE gives the dialog an error icon. Please note the three commas.

Show a message dialog with the message Wrong input, the title Error and the ERROR_MESSAGE type.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'JOptionPane.showMessageDialog(null, "Wrong input", "Error", JOptionPane.ERROR_MESSAGE);', '[{"part": "null", "explanation": "No frame is given, so the default is used."}, {"part": "\\"Wrong input\\"", "explanation": "The message inside the dialog."}, {"part": "\\"Error\\"", "explanation": "The text shown in the title bar."}, {"part": "JOptionPane.ERROR_MESSAGE", "explanation": "The dialog type, which shows an error icon."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(171, 5, 'Level 13', 'GETTING INPUT', 'The Scanner Summoning', 'Pip crosses to the second half of the isle, where the Alternative Methods of Input are kept. The utility Scanner, found in java.util, reads input from the keyboard. Import it, then create a Scanner named scan that reads from System.in.

Import java.util.Scanner and create a Scanner named scan that reads from System.in.', 'new Scanner(System.in)', 'import java.util.Scanner; Scanner scan = new Scanner(System.in);', 60, 8, 13, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: import java.util.Scanner; Scanner scan = new Scanner(System.in);', 'import\\s+java\\.util\\.Scanner;\\s+Scanner\\s+scan\\s+=\\s+new\\s+Scanner\\(\\s*System\\.in\\s*\\);', '/assets/landscapes/oakheart1.png', 'Importing and Creating a Scanner', 'Pip crosses to the second half of the isle, where the Alternative Methods of Input are kept. The utility Scanner, found in java.util, reads input from the keyboard. Import it, then create a Scanner named scan that reads from System.in.

Import java.util.Scanner and create a Scanner named scan that reads from System.in.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'import java.util.Scanner; Scanner scan = new Scanner(System.in);', '[{"part": "import java.util.Scanner;", "explanation": "Loads the Scanner class from the java.util package."}, {"part": "Scanner scan", "explanation": "Declares a variable named scan of the class type Scanner."}, {"part": "=", "explanation": "Stores the new object in the variable."}, {"part": "new Scanner(System.in)", "explanation": "Creates a Scanner that reads from the keyboard."}, {"part": ";", "explanation": "Ends the statement."}]'),
(172, 5, 'Level 14', 'GETTING INPUT', 'The First Number', 'The Scanner reads each data type with its own method. nextInt() reads an integer typed by the user. In the sample program, the prompt Input the first number to add: is printed and the answer is stored in an int named num1. Be careful: if the user types something other than an integer, nextInt() makes the program crash.

Print the prompt Input the first number to add: then store scan.nextInt() in an int named num1.', 'Use scan.nextInt() for a whole number.', 'System.out.println("Input the first number to add:"); int num1 = scan.nextInt();', 60, 8, 14, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: System.out.println("Input the first number to add:"); int num1 = scan.nextInt();', 'System\\.out\\.println\\(\\s*"Input\\s+the\\s+first\\s+number\\s+to\\s+add:"\\s*\\);\\s+int\\s+num1\\s+=\\s+scan\\.nextInt\\(\\s*\\s*\\);', '/assets/landscapes/oakheart2.png', 'Reading an int', 'The Scanner reads each data type with its own method. nextInt() reads an integer typed by the user. In the sample program, the prompt Input the first number to add: is printed and the answer is stored in an int named num1. Be careful: if the user types something other than an integer, nextInt() makes the program crash.

Print the prompt Input the first number to add: then store scan.nextInt() in an int named num1.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'System.out.println("Input the first number to add:"); int num1 = scan.nextInt();', '[{"part": "System.out.println(\\"Input the first number to add:\\");", "explanation": "Prompts the user for a number."}, {"part": "int num1", "explanation": "An int variable to hold the number."}, {"part": "scan.nextInt()", "explanation": "Reads the next integer the user types."}, {"part": ";", "explanation": "Ends the statement."}]'),
(173, 5, 'Level 15', 'GETTING INPUT', 'The Sum Bridge', 'With num1 and num2 both read, the bridge adds them. In the sample run the user enters 58 and 42, and the program prints The answer is 100.

Assume num1 and num2 already hold the scanned numbers. Store their sum in an int named sum, then print The answer is followed by sum.', 'Join the text and the variable with +.', 'int sum = num1 + num2; System.out.println("The answer is " + sum);', 60, 8, 15, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int sum = num1 + num2; System.out.println("The answer is " + sum);', 'int\\s+sum\\s+=\\s+num1\\s+\\+\\s+num2;\\s+System\\.out\\.println\\(\\s*"The\\s+answer\\s+is\\s+"\\s+\\+\\s+sum\\s*\\);', '/assets/landscapes/oakheart3.png', 'Adding Scanned Numbers', 'With num1 and num2 both read, the bridge adds them. In the sample run the user enters 58 and 42, and the program prints The answer is 100.

Assume num1 and num2 already hold the scanned numbers. Store their sum in an int named sum, then print The answer is followed by sum.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int sum = num1 + num2; System.out.println("The answer is " + sum);', '[{"part": "int sum = num1 + num2;", "explanation": "Adds the two scanned numbers and stores the result."}, {"part": "System.out.println(", "explanation": "Prints the value and then adds a newline."}, {"part": "\\"The answer is \\"", "explanation": "The text shown before the result."}, {"part": "+ sum", "explanation": "Joins the value stored in sum to the text."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(174, 5, 'Level 16', 'GETTING INPUT', 'The Many Methods', 'The Scanner has a method for each data type: nextLine() reads a String, nextDouble() reads a double and nextBoolean() reads a boolean. Pick the method that matches the type of the variable.

Read a String into line, a double into price and a boolean into ready, each with the matching Scanner method.', 'nextLine, nextDouble and nextBoolean.', 'String line = scan.nextLine(); double price = scan.nextDouble(); boolean ready = scan.nextBoolean();', 60, 8, 16, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'String\\s+line\\s+=\\s+scan\\.nextLine\\(\\s*\\s*\\);\\s+double\\s+price\\s+=\\s+scan\\.nextDouble\\(\\s*\\s*\\);\\s+boolean\\s+ready\\s+=\\s+scan\\.nextBoolean\\(\\s*\\s*\\);', '/assets/landscapes/oakheart4.png', 'Other Scanner Methods', 'The Scanner has a method for each data type: nextLine() reads a String, nextDouble() reads a double and nextBoolean() reads a boolean. Pick the method that matches the type of the variable.

Read a String into line, a double into price and a boolean into ready, each with the matching Scanner method.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String line = scan.nextLine(); double price = scan.nextDouble(); boolean ready = scan.nextBoolean();', '[{"part": "String line = scan.nextLine();", "explanation": "nextLine() reads a whole line as a String."}, {"part": "double price = scan.nextDouble();", "explanation": "nextDouble() reads a number with a decimal part."}, {"part": "boolean ready = scan.nextBoolean();", "explanation": "nextBoolean() reads true or false."}]'),
(175, 5, 'Level 17', 'GETTING INPUT', 'The Letter Pick', 'The Scanner has no method that reads a char directly. Read the text as a String, then use charAt(index number) to pick one character from it. Index numbers start at 0, so charAt(0) is the first character.

Read a line with scan.nextLine() and store its first character in a char named letter.', 'Chain .charAt(0) after scan.nextLine().', 'char letter = scan.nextLine().charAt(0);', 60, 8, 17, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: char letter = scan.nextLine().charAt(0);', 'char\\s+letter\\s+=\\s+scan\\.nextLine\\(\\s*\\s*\\)\\.charAt\\(\\s*0\\s*\\);', '/assets/landscapes/oakheart1.png', 'Reading a char', 'The Scanner has no method that reads a char directly. Read the text as a String, then use charAt(index number) to pick one character from it. Index numbers start at 0, so charAt(0) is the first character.

Read a line with scan.nextLine() and store its first character in a char named letter.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'char letter = scan.nextLine().charAt(0);', '[{"part": "char letter", "explanation": "A char variable holds a single character."}, {"part": "scan.nextLine()", "explanation": "Reads the typed text as a String."}, {"part": ".charAt(0)", "explanation": "Picks the character at index 0, the first one."}, {"part": ";", "explanation": "Ends the statement."}]'),
(176, 5, 'Level 18', 'GETTING INPUT', 'The Newline Trap', 'A trap lies on the path. The guide warns against scanning text with nextLine() right after nextInt() on the same scanner. nextInt() reads only the number and leaves the Enter key (the newline) behind, so the next nextLine() grabs that leftover and returns an empty String instead of the user\'s text. A common fix is to call scan.nextLine() once to throw away the leftover newline.

Read an int into age, discard the leftover newline with scan.nextLine(), then read a String into name.', 'Put an extra scan.nextLine(); between the two reads.', 'int age = scan.nextInt(); scan.nextLine(); String name = scan.nextLine();', 60, 8, 18, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int age = scan.nextInt(); scan.nextLine(); String name = scan.nextLine();', 'int\\s+age\\s+=\\s+scan\\.nextInt\\(\\s*\\s*\\);\\s+scan\\.nextLine\\(\\s*\\s*\\);\\s+String\\s+name\\s+=\\s+scan\\.nextLine\\(\\s*\\s*\\);', '/assets/landscapes/oakheart2.png', 'nextInt() Then nextLine()', 'A trap lies on the path. The guide warns against scanning text with nextLine() right after nextInt() on the same scanner. nextInt() reads only the number and leaves the Enter key (the newline) behind, so the next nextLine() grabs that leftover and returns an empty String instead of the user\'s text. A common fix is to call scan.nextLine() once to throw away the leftover newline.

Read an int into age, discard the leftover newline with scan.nextLine(), then read a String into name.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int age = scan.nextInt(); scan.nextLine(); String name = scan.nextLine();', '[{"part": "int age = scan.nextInt();", "explanation": "Reads the number but leaves the newline in the input."}, {"part": "scan.nextLine();", "explanation": "Throws away the leftover newline so it cannot be mistaken for the user\'s text."}, {"part": "String name = scan.nextLine();", "explanation": "Now reads the text the user really typed."}]'),
(177, 5, 'Level 19', 'GETTING INPUT', 'The File Gate', 'At the end of the isle Pip finds a scroll stored in a file. Reading a file takes three objects: a FileInputStream opens the file, a DataInputStream wraps it, and a BufferedReader reads it. In Java code a backslash in a path is typed twice, so the file C:\\hello.txt is written "C:\\\\hello.txt".

Open "C:\\\\hello.txt" with a FileInputStream named fstream, wrap it in a DataInputStream named in, then create a BufferedReader named br from in.', 'Three statements: fstream, then in, then br.', 'FileInputStream fstream = new FileInputStream("C:\\\\hello.txt"); DataInputStream in = new DataInputStream(fstream); BufferedReader br = new BufferedReader(new InputStreamReader(in));', 60, 8, 19, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'FileInputStream\\s+fstream\\s+=\\s+new\\s+FileInputStream\\("C:\\\\\\\\hello\\.txt"\\);\\s+DataInputStream\\s+in\\s+=\\s+new\\s+DataInputStream\\(fstream\\);\\s+BufferedReader\\s+br\\s+=\\s+new\\s+BufferedReader\\(new\\s+InputStreamReader\\(in\\)\\);', '/assets/landscapes/oakheart3.png', 'Opening a Text File', 'At the end of the isle Pip finds a scroll stored in a file. Reading a file takes three objects: a FileInputStream opens the file, a DataInputStream wraps it, and a BufferedReader reads it. In Java code a backslash in a path is typed twice, so the file C:\\hello.txt is written "C:\\\\hello.txt".

Open "C:\\\\hello.txt" with a FileInputStream named fstream, wrap it in a DataInputStream named in, then create a BufferedReader named br from in.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'FileInputStream fstream = new FileInputStream("C:\\\\hello.txt"); DataInputStream in = new DataInputStream(fstream); BufferedReader br = new BufferedReader(new InputStreamReader(in));', '[{"part": "FileInputStream fstream = new FileInputStream(\\"C:\\\\\\\\hello.txt\\");", "explanation": "Opens the file at that path."}, {"part": "DataInputStream in = new DataInputStream(fstream);", "explanation": "Wraps the file stream in a DataInputStream object."}, {"part": "BufferedReader br = new BufferedReader(new InputStreamReader(in));", "explanation": "Builds a reader that can read the file line by line."}]'),
(178, 5, 'Level 20', 'GETTING INPUT', 'The Final Scroll', 'The scroll unrolls across the sky. A while loop reads the file one line at a time: br.readLine() returns the next line, and when there are no more lines it returns null, so the loop stops. Each line is stored in strLine and printed on the console. When the loop is done, close the stream with in.close().

Assume br and in already exist. Declare a String named strLine, loop while strLine = br.readLine() is not null, print strLine inside the loop, then close in.', 'The assignment sits in its own parentheses: ((strLine = br.readLine()) != null)', 'String strLine; while ((strLine = br.readLine()) != null) { System.out.println(strLine); } in.close();', 100, 8, 20, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'String\\s+strLine;\\s+while\\s*\\(\\s*\\(\\s*strLine\\s+=\\s+br\\.readLine\\(\\s*\\s*\\)\\s*\\)\\s*!=\\s+null\\s*\\)\\s*\\{\\s*System\\.out\\.println\\(\\s*strLine\\s*\\);\\s*\\}\\s*in\\.close\\(\\s*\\s*\\);', '/assets/landscapes/oakheart4.png', 'Reading a File Line by Line', 'The scroll unrolls across the sky. A while loop reads the file one line at a time: br.readLine() returns the next line, and when there are no more lines it returns null, so the loop stops. Each line is stored in strLine and printed on the console. When the loop is done, close the stream with in.close().

Assume br and in already exist. Declare a String named strLine, loop while strLine = br.readLine() is not null, print strLine inside the loop, then close in.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String strLine; while ((strLine = br.readLine()) != null) { System.out.println(strLine); } in.close();', '[{"part": "String strLine;", "explanation": "Holds each line that is read."}, {"part": "while (", "explanation": "Starts a loop that repeats while the condition is true."}, {"part": "(strLine = br.readLine())", "explanation": "Reads the next line and stores it in strLine. The extra parentheses make the assigned value available for the comparison."}, {"part": "!= null", "explanation": "readLine() returns null at the end of the file, which ends the loop."}, {"part": "{ System.out.println(strLine); }", "explanation": "Prints each line on the console."}, {"part": "in.close();", "explanation": "Closes the input stream when reading is finished."}]');

-- 4) Guided-mode multiple choice (one step per lesson, like Islands 3 and 4).
--    Rows are cleared first so re-running this file never hits uq_guided_lesson_step.
DELETE FROM `guided_steps` WHERE `lesson_id` BETWEEN 159 AND 178;

INSERT INTO `guided_steps` (`lesson_id`, `step_order`, `prompt`, `correct_snippet`, `distractor_1`, `distractor_2`, `distractor_3`) VALUES
(159, 1, 'Which statement imports every class in the java.io package?', 'import java.io.*;', 'import java.io;', 'import java.io.*', 'include java.io.*;'),
(160, 1, 'Which statement creates a BufferedReader named dataIn that reads from the keyboard?', 'BufferedReader dataIn = new BufferedReader(new InputStreamReader(System.in));', 'BufferedReader dataIn = new BufferedReader(System.in);', 'BufferedReader dataIn = new InputStreamReader(System.in);', 'BufferedReader dataIn = new BufferedReader(new InputStreamReader(System.in))'),
(161, 1, 'Which code declares an empty String named name and prints the prompt Please Enter Your Name:?', 'String name = ""; System.out.print("Please Enter Your Name:");', 'string name = ""; System.out.print("Please Enter Your Name:");', 'String name = ""; System.out.print(Please Enter Your Name:);', 'String name = ""; System.out.print("Please Enter Your Name:")'),
(162, 1, 'Which code reads a line from dataIn into name inside a proper try-catch block?', 'try { name = dataIn.readLine(); } catch (IOException e) { System.out.println("Error!"); }', 'name = dataIn.readLine(); catch (IOException e) { System.out.println("Error!"); }', 'try { name = dataIn.readLine(); } catch { System.out.println("Error!"); }', 'try { name = dataIn.readLine; } catch (IOException e) { System.out.println("Error!"); }'),
(163, 1, 'Which statement prints a greeting such as Hello Pip! using the variable name?', 'System.out.println("Hello " + name + "!");', 'System.out.println("Hello " + "name" + "!");', 'System.out.println("Hello " + name + !);', 'System.out.println("Hello " name "!");'),
(164, 1, 'Which code prompts for an integer and stores it using Keyboard.java?', 'System.out.println("Enter an integer: "); int num = Keyboard.readInt();', 'System.out.println("Enter an integer: "); int num = Keyboard.readInteger();', 'System.out.println("Enter an integer: "); int num = Keyboard.readInt;', 'System.out.println("Enter an integer: "); String num = Keyboard.readInt();'),
(165, 1, 'Which statement imports the JOptionPane class?', 'import javax.swing.JOptionPane;', 'import java.swing.JOptionPane;', 'import javax.swing.JOptionPane', 'import javax.JOptionPane.swing;'),
(166, 1, 'Which statement shows an input dialog and stores what the user types in name?', 'String name = JOptionPane.showInputDialog("Please enter your name");', 'String name = JOptionPane.showMessageDialog("Please enter your name");', 'int name = JOptionPane.showInputDialog("Please enter your name");', 'String name = JOptionPane.showInputDialog(Please enter your name);'),
(167, 1, 'Which code builds a greeting in msg and shows it in a message dialog?', 'String msg = "Hello " + name + "!"; JOptionPane.showMessageDialog(null, msg);', 'String msg = "Hello " + name + "!"; JOptionPane.showMessageDialog(msg);', 'String msg = "Hello " + name + "!"; JOptionPane.showInputDialog(null, msg);', 'String msg = "Hello " + name + "!"; JOptionPane.showMessageDialog(null msg);'),
(168, 1, 'Which code reads a dialog entry and converts it to an int named x?', 'String userInput = JOptionPane.showInputDialog("Enter"); int x = Integer.parseInt(userInput);', 'String userInput = JOptionPane.showInputDialog("Enter"); int x = userInput;', 'String userInput = JOptionPane.showInputDialog("Enter"); int x = Integer.parseDouble(userInput);', 'String userInput = JOptionPane.showInputDialog("Enter"); int x = Integer.toInt(userInput);'),
(169, 1, 'Which statement shows an input dialog with a message, the title Entry Form and an information icon?', 'JOptionPane.showInputDialog(null, "Enter your name", "Entry Form", JOptionPane.INFORMATION_MESSAGE);', 'JOptionPane.showInputDialog("Enter your name", "Entry Form", JOptionPane.INFORMATION_MESSAGE);', 'JOptionPane.showInputDialog(null, "Enter your name", "Entry Form", INFORMATION_MESSAGE);', 'JOptionPane.showInputDialog(null, "Entry Form", "Enter your name", JOptionPane.INFORMATION_MESSAGE);'),
(170, 1, 'Which statement shows an error dialog with the message Wrong input and the title Error?', 'JOptionPane.showMessageDialog(null, "Wrong input", "Error", JOptionPane.ERROR_MESSAGE);', 'JOptionPane.showMessageDialog(null, "Wrong input", "Error" JOptionPane.ERROR_MESSAGE);', 'JOptionPane.showMessageDialog("Wrong input", "Error", JOptionPane.ERROR_MESSAGE);', 'JOptionPane.showMessageDialog(null, "Wrong input", "Error", JOptionPane.ERROR_MSG);'),
(171, 1, 'Which code imports Scanner and creates a Scanner named scan for keyboard input?', 'import java.util.Scanner; Scanner scan = new Scanner(System.in);', 'import java.util.Scanner; Scanner scan = new Scanner(System.out);', 'import java.util.Scanner; Scanner scan = Scanner(System.in);', 'import java.io.Scanner; Scanner scan = new Scanner(System.in);'),
(172, 1, 'Which code prompts for the first number and stores it as an int with a Scanner?', 'System.out.println("Input the first number to add:"); int num1 = scan.nextInt();', 'System.out.println("Input the first number to add:"); int num1 = scan.nextLine();', 'System.out.println("Input the first number to add:"); int num1 = scan.readInt();', 'System.out.println("Input the first number to add:"); int num1 = Scanner.nextInt();'),
(173, 1, 'Which code adds num1 and num2 and prints The answer is followed by the sum?', 'int sum = num1 + num2; System.out.println("The answer is " + sum);', 'int sum = num1 + num2; System.out.println("The answer is " + "sum");', 'int sum = num1 - num2; System.out.println("The answer is " + sum);', 'int sum = num1 + num2; System.out.println("The answer is " sum);'),
(174, 1, 'Which code reads a String, a double and a boolean with the matching Scanner methods?', 'String line = scan.nextLine(); double price = scan.nextDouble(); boolean ready = scan.nextBoolean();', 'String line = scan.nextLine(); double price = scan.nextDecimal(); boolean ready = scan.nextBoolean();', 'String line = scan.next(); double price = scan.nextDouble(); boolean ready = scan.nextBool();', 'String line = scan.nextLine(); double price = scan.nextDouble(); boolean ready = scan.nextLine();'),
(175, 1, 'Which statement stores the first character the user types in a char named letter?', 'char letter = scan.nextLine().charAt(0);', 'char letter = scan.nextChar();', 'char letter = scan.nextLine().charAt(1);', 'char letter = scan.nextLine();'),
(176, 1, 'Which code reads an int and then a String without falling into the newline trap?', 'int age = scan.nextInt(); scan.nextLine(); String name = scan.nextLine();', 'int age = scan.nextInt(); String name = scan.nextLine();', 'int age = scan.nextLine(); scan.nextInt(); String name = scan.nextLine();', 'int age = scan.nextInt(); scan.nextInt(); String name = scan.nextLine();'),
(177, 1, 'Which code opens hello.txt and builds a BufferedReader named br to read it?', 'FileInputStream fstream = new FileInputStream("C:\\\\hello.txt"); DataInputStream in = new DataInputStream(fstream); BufferedReader br = new BufferedReader(new InputStreamReader(in));', 'FileInputStream fstream = new FileInputStream("C:\\\\hello.txt"); DataInputStream in = new DataInputStream(fstream); BufferedReader br = new BufferedReader(in);', 'FileInputStream fstream = new FileInputStream(C:\\\\hello.txt); DataInputStream in = new DataInputStream(fstream); BufferedReader br = new BufferedReader(new InputStreamReader(in));', 'FileInputStream fstream = new FileInputStream("C:\\\\hello.txt"); DataInputStream in = new DataInputStream(fstream); BufferedReader br = new BufferedReader(new InputStreamReader(in))'),
(178, 1, 'Which code prints every line of the file and then closes the stream?', 'String strLine; while ((strLine = br.readLine()) != null) { System.out.println(strLine); } in.close();', 'String strLine; while (strLine = br.readLine() != null) { System.out.println(strLine); } in.close();', 'String strLine; while ((strLine = br.readLine()) == null) { System.out.println(strLine); } in.close();', 'String strLine; in.close(); while ((strLine = br.readLine()) != null) { System.out.println(strLine); }');

ALTER TABLE `lessons` AUTO_INCREMENT=179;
