-- Island 4: Control Flow & Conditional Logic
-- Express/MySQL schema migration. Safe to re-run.
USE codequest;

INSERT INTO lesson_modules (id, title, description, color, order_index, is_active)
VALUES (4, 'Control Flow and Conditional Logic', 'Choose actions with if, else if, else, and logical operators.', '#EF4444', 4, TRUE)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  description = VALUES(description),
  color = VALUES(color),
  order_index = VALUES(order_index),
  is_active = TRUE;

-- Update existing module 4 lessons by their relative order.
UPDATE lessons SET level_label='Level 1', track='JAVA CONTROL FLOW', title='The Pressure Plate', briefing='Pip must step on a weight plate. The gate opens only if the measured weight is sufficient, so he checks one condition before moving forward.', hint='Use if to run openGate only when weight is at least 10.', goal='Use a single if statement to open the gate when the weight is sufficient.', xp_reward=40, order_index=1 WHERE module_id=4 AND order_index=1;
UPDATE lessons SET level_label='Level 2', track='JAVA CONTROL FLOW', title='The Fork in the Path', briefing='Pip reaches a split bridge. If the left path is clear he takes it; otherwise, he crosses the right rope bridge.', hint='Use else for the path that runs when the first condition is false.', goal='Choose between the left and right bridge with if and else.', xp_reward=45, order_index=2 WHERE module_id=4 AND order_index=2;
UPDATE lessons SET level_label='Level 3', track='JAVA CONTROL FLOW', title='Health Inspection', briefing='Before entering toxic mist, Pip checks his shield points. Strong protection lets him cross; otherwise, he drinks a potion first.', hint='Compare shieldPoints with 50 inside the condition.', goal='Branch on a numeric shield threshold before entering the mist.', xp_reward=50, order_index=3 WHERE module_id=4 AND order_index=3;
UPDATE lessons SET level_label='Level 4', track='JAVA CONTROL FLOW', title='Runic Key Match', briefing='A magic vault compares the rune on Pip''s key with the door lock. In Java, String values must be compared with equals before the vault opens.', hint='Call equals on keyType instead of using == for String content.', goal='Use String.equals to accept the Gold key and reject other keys.', xp_reward=55, order_index=4 WHERE module_id=4 AND order_index=4;
UPDATE lessons SET level_label='Level 5', track='JAVA CONTROL FLOW', title='Elemental Guard', briefing='An elemental barrier changes between Fire, Water, and Earth. Pip checks each element in order and casts the matching counter-spell, with a shield as the final fallback.', hint='Chain else if branches between the first if and the final else.', goal='Select a counter-spell with a three-way conditional chain.', xp_reward=60, order_index=5 WHERE module_id=4 AND order_index=5;
UPDATE lessons SET level_label='Level 6', track='JAVA CONTROL FLOW', title='Double Lock Sentinel', briefing='A heavy drawbridge has two powered levers. Pip can lower it only when both side levers are on at the same time.', hint='The && operator is true only when leverA and leverB are both true.', goal='Require two conditions together with logical AND.', xp_reward=60, order_index=6 WHERE module_id=4 AND order_index=6;
UPDATE lessons SET level_label='Level 7', track='JAVA CONTROL FLOW', title='Emergency Exit', briefing='Pip finds an escape door. A master key card or knowledge of the secret phrase is enough, so either successful condition can unlock the exit.', hint='The || operator succeeds when at least one condition is true.', goal='Open the escape door with logical OR.', xp_reward=65, order_index=7 WHERE module_id=4 AND order_index=7;
UPDATE lessons SET level_label='Level 8', track='JAVA CONTROL FLOW', title='Guard Duty', briefing='At a checkpoint, Pip first checks whether the guard is awake. Only an awake guard leads to the second check for a valid pass.', hint='Place the pass check inside the guard-awake if block.', goal='Use a nested if to protect the checkpoint entry.', xp_reward=70, order_index=8 WHERE module_id=4 AND order_index=8;
UPDATE lessons SET level_label='Level 9', track='JAVA CONTROL FLOW', title='The Trap Evaluator', briefing='Pip crosses a trap grid where a tile is safe only when its lamp is off and his energy remains below 100.', hint='Combine !isLit with energyLevel < 100 using &&.', goal='Evaluate negation and a numeric condition together.', xp_reward=75, order_index=9 WHERE module_id=4 AND order_index=9;
UPDATE lessons SET level_label='Level 10', track='JAVA CONTROL FLOW', title='Control Flow Boss Arena', briefing='The Logic Warden shifts phases based on health, rage, and element. Pip must combine branches, String equality, and logical operators to choose the correct combat counter-action.', hint='Check the boss conditions from most specific to the final fallback action.', goal='Synthesize Java control flow to defeat the Logic Warden.', xp_reward=100, order_index=10 WHERE module_id=4 AND order_index=10;

-- Insert any missing relative levels without creating duplicates on re-runs.
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 1', 'JAVA CONTROL FLOW', 'The Pressure Plate', 'Pip must step on a weight plate. The gate opens only if the measured weight is sufficient, so he checks one condition before moving forward.', 'Use if to run openGate only when weight is at least 10.', 'Use a single if statement to open the gate when the weight is sufficient.', 40, 1, 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=1);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 2', 'JAVA CONTROL FLOW', 'The Fork in the Path', 'Pip reaches a split bridge. If the left path is clear he takes it; otherwise, he crosses the right rope bridge.', 'Use else for the path that runs when the first condition is false.', 'Choose between the left and right bridge with if and else.', 45, 1, 2 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=2);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 3', 'JAVA CONTROL FLOW', 'Health Inspection', 'Before entering toxic mist, Pip checks his shield points. Strong protection lets him cross; otherwise, he drinks a potion first.', 'Compare shieldPoints with 50 inside the condition.', 'Branch on a numeric shield threshold before entering the mist.', 50, 1, 3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=3);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 4', 'JAVA CONTROL FLOW', 'Runic Key Match', 'A magic vault compares the rune on Pip''s key with the door lock. In Java, String values must be compared with equals before the vault opens.', 'Call equals on keyType instead of using == for String content.', 'Use String.equals to accept the Gold key and reject other keys.', 55, 1, 4 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=4);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 5', 'JAVA CONTROL FLOW', 'Elemental Guard', 'An elemental barrier changes between Fire, Water, and Earth. Pip checks each element in order and casts the matching counter-spell, with a shield as the final fallback.', 'Chain else if branches between the first if and the final else.', 'Select a counter-spell with a three-way conditional chain.', 60, 1, 5 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=5);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 6', 'JAVA CONTROL FLOW', 'Double Lock Sentinel', 'A heavy drawbridge has two powered levers. Pip can lower it only when both side levers are on at the same time.', 'The && operator is true only when leverA and leverB are both true.', 'Require two conditions together with logical AND.', 60, 1, 6 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=6);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 7', 'JAVA CONTROL FLOW', 'Emergency Exit', 'Pip finds an escape door. A master key card or knowledge of the secret phrase is enough, so either successful condition can unlock the exit.', 'The || operator succeeds when at least one condition is true.', 'Open the escape door with logical OR.', 65, 1, 7 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=7);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 8', 'JAVA CONTROL FLOW', 'Guard Duty', 'At a checkpoint, Pip first checks whether the guard is awake. Only an awake guard leads to the second check for a valid pass.', 'Place the pass check inside the guard-awake if block.', 'Use a nested if to protect the checkpoint entry.', 70, 1, 8 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=8);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 9', 'JAVA CONTROL FLOW', 'The Trap Evaluator', 'Pip crosses a trap grid where a tile is safe only when its lamp is off and his energy remains below 100.', 'Combine !isLit with energyLevel < 100 using &&.', 'Evaluate negation and a numeric condition together.', 75, 1, 9 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=9);
INSERT INTO lessons (module_id, level_label, track, title, briefing, hint, goal, xp_reward, target_tiles, order_index)
SELECT 4, 'Level 10', 'JAVA CONTROL FLOW', 'Control Flow Boss Arena', 'The Logic Warden shifts phases based on health, rage, and element. Pip must combine branches, String equality, and logical operators to choose the correct combat counter-action.', 'Check the boss conditions from most specific to the final fallback action.', 'Synthesize Java control flow to defeat the Logic Warden.', 100, 1, 10 FROM dual WHERE NOT EXISTS (SELECT 1 FROM lessons WHERE module_id=4 AND order_index=10);

SET @level1_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=1 LIMIT 1);
SET @level2_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=2 LIMIT 1);
SET @level3_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=3 LIMIT 1);
SET @level4_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=4 LIMIT 1);
SET @level5_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=5 LIMIT 1);
SET @level6_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=6 LIMIT 1);
SET @level7_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=7 LIMIT 1);
SET @level8_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=8 LIMIT 1);
SET @level9_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=9 LIMIT 1);
SET @level10_id = (SELECT id FROM lessons WHERE module_id=4 AND order_index=10 LIMIT 1);

DELETE FROM guided_steps WHERE lesson_id IN (@level1_id,@level2_id,@level3_id,@level4_id,@level5_id,@level6_id,@level7_id,@level8_id,@level9_id,@level10_id);

INSERT INTO guided_steps (lesson_id, step_order, prompt, correct_snippet, distractor_1, distractor_2, distractor_3) VALUES
(@level1_id,1,'Pip must step on the pressure plate. Which if statement opens the gate only when weight is sufficient?','if (weight >= 10) { openGate(); }','if (weight > 10) { openGate(); }','if (weight = 10) { openGate(); }','if (weight >= 10) openGate();'),
(@level2_id,1,'Pip reaches a split bridge. Which if-else branch chooses the clear left path or the right rope bridge?','if (isLeftPathClear) { moveLeft(); } else { moveRight(); }','if (isLeftPathClear) { moveRight(); } else { moveLeft(); }','if (isLeftPathClear) moveLeft();','else (isLeftPathClear) { moveRight(); }'),
(@level3_id,1,'Pip checks his shield before toxic mist. Which branch crosses when shieldPoints is above 50 and drinks a potion otherwise?','if (shieldPoints > 50) { crossMist(); } else { drinkPotion(); }','if (shieldPoints >= 50) { drinkPotion(); } else { crossMist(); }','if (shieldPoints < 50) { crossMist(); }','if (shieldPoints = 50) { drinkPotion(); }'),
(@level4_id,1,'Which Java condition matches Pip''s Gold rune with String.equals before unlocking the vault?','if (keyType.equals("Gold")) { unlockVault(); } else { rejectKey(); }','if (keyType == "Gold") { unlockVault(); }','if (keyType.equals(Gold)) { unlockVault(); }','if (keyType = "Gold") { unlockVault(); }'),
(@level5_id,1,'Which chain selects the counter-spell for Fire, Water, or Earth?','if (element.equals("Fire")) { castWater(); } else if (element.equals("Water")) { castLightning(); } else { castShield(); }','if (element == "Fire") { castWater(); } else { castShield(); }','else if (element.equals("Water")) { castLightning(); }','if (element.equals("Fire")) castWater(); else castLightning();'),
(@level6_id,1,'Which condition lowers the drawbridge only when both powered levers are on?','if (leverA && leverB) { lowerBridge(); }','if (leverA || leverB) { lowerBridge(); }','if (leverA & leverB) { lowerBridge(); }','if (leverA && !leverB) { lowerBridge(); }'),
(@level7_id,1,'Which condition opens the emergency exit when either the key card or passcode is available?','if (hasMasterKey || knowsPasscode) { escape(); }','if (hasMasterKey && knowsPasscode) { escape(); }','if (hasMasterKey | knowsPasscode) { escape(); }','if (hasMasterKey || !knowsPasscode) { escape(); }'),
(@level8_id,1,'Which nested if checks that the guard is awake before checking Pip''s pass?','if (isGuardAwake) { if (hasPass) { passCheckpoint(); } }','if (hasPass) { if (isGuardAwake) { passCheckpoint(); } }','if (isGuardAwake && hasPass) { passCheckpoint(); }','if (isGuardAwake) { passCheckpoint(); }'),
(@level9_id,1,'Which condition steps safely only when the tile is unlit and energy is below 100?','if (!isLit && energyLevel < 100) { stepSafely(); }','if (isLit && energyLevel < 100) { stepSafely(); }','if (!isLit || energyLevel < 100) { stepSafely(); }','if (isLit && energyLevel > 100) { stepSafely(); }'),
(@level10_id,1,'Which control-flow block evaluates boss health, rage, and element to choose the combat counter?','if (bossHealth < 30 && isEnraged) { castShield(); } else if (element.equals("Fire")) { castWater(); } else { strike(); }','if (bossHealth < 30 || isEnraged) { castShield(); }','if (element == "Fire" && bossHealth > 30) { castWater(); }','if (bossHealth = 30) { strike(); }');
