-- ============================================================
-- ISLAND 6: STRINGS AND DECISIONS  (Chapter 9 + Chapter 10)
-- 20 levels. Lesson ids 179-198, module_id 6.
-- Levels 1-12  = Chapter 9 (String Handling Methods)
-- Levels 13-20 = Chapter 10 (Decision Control Structures)
-- ============================================================

-- 1) The lessons table has a foreign key to lesson_modules, so module 6 must exist first.
--    (Copy the column list from your own module 5 row. Example only, adjust the columns to match your table:)
-- INSERT INTO `lesson_modules` (`id`, `title`, ...) VALUES (6, 'Strings and Decisions', ...);

-- If a run stops with "#1406 Data too long for column ...", check the column sizes with
--   SHOW COLUMNS FROM `lessons`;
-- and widen the short ones (keep NOT NULL if your table has it), for example:
-- ALTER TABLE `lessons` MODIFY `required_code_label` VARCHAR(255), MODIFY `required_code_pattern` VARCHAR(500), MODIFY `goal` VARCHAR(500), MODIFY `solution_code` VARCHAR(500);

-- 2) Clear any existing Island 6 rows so re-running this file never hits
--    "Duplicate entry '6-1' for key 'uq_lessons_module_order'".
--    First look at what is there:
--      SELECT id, module_id, order_index, title FROM lessons WHERE module_id = 6 OR id >= 179;
-- Removes the old Island 6 snippets, including any old rows that sit on ids 179-198
-- under a different module_id (those would otherwise cause a primary-key error).
DELETE FROM `lessons` WHERE `module_id` = 6 OR `id` BETWEEN 179 AND 198;

-- OPTIONAL: if players already have saved progress for the OLD lessons 179-198, the new
-- levels would show as already completed. Clear it with your progress table's real name, e.g.:
-- DELETE FROM `user_progress` WHERE `lesson_id` BETWEEN 179 AND 198;

-- 3) The lessons
INSERT INTO `lessons` (`id`, `module_id`, `level_label`, `track`, `title`, `briefing`, `hint`, `goal`, `xp_reward`, `target_tiles`, `order_index`, `is_active`, `created_at`, `min_moves`, `min_says`, `min_jumps`, `required_code_label`, `required_code_pattern`, `background_image`, `subtitle`, `description`, `grid_cols`, `grid_rows`, `mechanics_config`, `total_tiles`, `ground_fraction`, `initial_tile`, `flag_tile`, `solution_code`, `line_breakdown`) VALUES
(179, 6, 'Level 1', 'STRINGS AND DECISIONS', 'The Letter Locker', 'Pip reaches Crossroads Isle, where every locker opens with a single letter. A string is a sequence of characters, and string manipulation is the basis of many algorithms and utilities, such as input validation and text analysis. The charAt(anIndex) method returns the character at the position anIndex. Positions start counting at 0, so in "SEPTEMBER" the character at index 3 is T.

Declare a String named myString set to "SEPTEMBER", then store the character at index 3 in a char named location.', 'Index 3 is the fourth letter, because counting starts at 0.', 'String myString = "SEPTEMBER"; char location = myString.charAt(3);', 50, 8, 1, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; char location = myString.charAt(3);', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+char\\s+location\\s+=\\s+myString\\.charAt\\(\\s*3\\s*\\);', '/assets/landscapes/oakheart1.png', 'charAt()', 'Pip reaches Crossroads Isle, where every locker opens with a single letter. A string is a sequence of characters, and string manipulation is the basis of many algorithms and utilities, such as input validation and text analysis. The charAt(anIndex) method returns the character at the position anIndex. Positions start counting at 0, so in "SEPTEMBER" the character at index 3 is T.

Declare a String named myString set to "SEPTEMBER", then store the character at index 3 in a char named location.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; char location = myString.charAt(3);', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "Declares a String variable and stores the word in it."}, {"part": "char location", "explanation": "A char variable, because charAt() returns a single character."}, {"part": "myString.charAt(3)", "explanation": "Returns the character at index 3, which is T."}, {"part": ";", "explanation": "Ends the statement."}]'),
(180, 6, 'Level 2', 'STRINGS AND DECISIONS', 'The Word Measure', 'A scribe measures every word that enters the isle. The length() method counts the number of characters in a string and returns the length of myString as an int. Notice that length() has parentheses, because it is a method. "SEPTEMBER" has 9 characters.

Declare a String named myString set to "SEPTEMBER", then store its length in an int named size.', 'length() needs parentheses after it.', 'String myString = "SEPTEMBER"; int size = myString.length();', 50, 8, 2, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; int size = myString.length();', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+int\\s+size\\s+=\\s+myString\\.length\\(\\s*\\s*\\);', '/assets/landscapes/oakheart2.png', 'length()', 'A scribe measures every word that enters the isle. The length() method counts the number of characters in a string and returns the length of myString as an int. Notice that length() has parentheses, because it is a method. "SEPTEMBER" has 9 characters.

Declare a String named myString set to "SEPTEMBER", then store its length in an int named size.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; int size = myString.length();', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The string to measure."}, {"part": "int size", "explanation": "An int variable, because length() returns a whole number."}, {"part": "myString.length()", "explanation": "Counts the characters in myString, which gives 9."}, {"part": ";", "explanation": "Ends the statement."}]'),
(181, 6, 'Level 3', 'STRINGS AND DECISIONS', 'The Exact Match', 'Two guards compare passwords. The equals(aString) method returns true if aString exactly equals myString, and the resulting value is a boolean. Exactly means that uppercase and lowercase letters must match too, so "Java" and "java" are not equal.

Declare string1 as "Java" and string3 as "java", then store string1.equals(string3) in a boolean named same.', 'Call equals on string1 and put string3 inside the parentheses.', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equals(string3);', 50, 8, 3, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String string1 = "Java"; String string3 = "java"; boolean same = string1.equals(string3);', 'String\\s+string1\\s+=\\s+"Java";\\s+String\\s+string3\\s+=\\s+"java";\\s+boolean\\s+same\\s+=\\s+string1\\.equals\\(\\s*string3\\s*\\);', '/assets/landscapes/oakheart3.png', 'equals()', 'Two guards compare passwords. The equals(aString) method returns true if aString exactly equals myString, and the resulting value is a boolean. Exactly means that uppercase and lowercase letters must match too, so "Java" and "java" are not equal.

Declare string1 as "Java" and string3 as "java", then store string1.equals(string3) in a boolean named same.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equals(string3);', '[{"part": "String string1 = \\"Java\\"; String string3 = \\"java\\";", "explanation": "The two strings to compare."}, {"part": "boolean same", "explanation": "A boolean variable, because equals() returns true or false."}, {"part": "string1.equals(string3)", "explanation": "Checks whether the two strings match exactly. Here it is false because of the case."}, {"part": ";", "explanation": "Ends the statement."}]'),
(182, 6, 'Level 4', 'STRINGS AND DECISIONS', 'The Case Mirror', 'A mirror treats big and small letters as the same. The equalsIgnoreCase(aString) method is similar to equals but ignores case, so "Java" and "java" count as equal.

Declare string1 as "Java" and string3 as "java", then store string1.equalsIgnoreCase(string3) in a boolean named same.', 'The method name has a capital I and a capital C.', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equalsIgnoreCase(string3);', 50, 8, 4, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'String\\s+string1\\s+=\\s+"Java";\\s+String\\s+string3\\s+=\\s+"java";\\s+boolean\\s+same\\s+=\\s+string1\\.equalsIgnoreCase\\(\\s*string3\\s*\\);', '/assets/landscapes/oakheart4.png', 'equalsIgnoreCase()', 'A mirror treats big and small letters as the same. The equalsIgnoreCase(aString) method is similar to equals but ignores case, so "Java" and "java" count as equal.

Declare string1 as "Java" and string3 as "java", then store string1.equalsIgnoreCase(string3) in a boolean named same.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equalsIgnoreCase(string3);', '[{"part": "String string1 = \\"Java\\"; String string3 = \\"java\\";", "explanation": "The same two strings as before."}, {"part": "boolean same", "explanation": "Holds true or false."}, {"part": "string1.equalsIgnoreCase(string3)", "explanation": "Compares the strings while ignoring uppercase and lowercase, so the result is true."}, {"part": ";", "explanation": "Ends the statement."}]'),
(183, 6, 'Level 5', 'STRINGS AND DECISIONS', 'The First Finder', 'A seeker hunts for a letter inside a word. The indexOf(aCharacter) method searches for aCharacter and returns the index of its first occurrence within myString as an int. A failed search returns -1. There is also indexOf(aCharacter, beginIndex), which starts the search at beginIndex. In "SEPTEMBER" the first E is at index 1.

Declare a String named myString set to "SEPTEMBER", then store the index of the first \'E\' in an int named first.', 'A char goes in single quotes: \'E\'.', 'String myString = "SEPTEMBER"; int first = myString.indexOf(\'E\');', 50, 8, 5, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; int first = myString.indexOf(\'E\');', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+int\\s+first\\s+=\\s+myString\\.indexOf\\(\\s*\'E\'\\s*\\);', '/assets/landscapes/oakheart1.png', 'indexOf() With a Character', 'A seeker hunts for a letter inside a word. The indexOf(aCharacter) method searches for aCharacter and returns the index of its first occurrence within myString as an int. A failed search returns -1. There is also indexOf(aCharacter, beginIndex), which starts the search at beginIndex. In "SEPTEMBER" the first E is at index 1.

Declare a String named myString set to "SEPTEMBER", then store the index of the first \'E\' in an int named first.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; int first = myString.indexOf(\'E\');', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The string to search."}, {"part": "int first", "explanation": "An int variable, because indexOf() returns an index."}, {"part": "myString.indexOf(\'E\')", "explanation": "Finds the first E and returns its index, which is 1."}, {"part": ";", "explanation": "Ends the statement."}]'),
(184, 6, 'Level 6', 'STRINGS AND DECISIONS', 'The Missing Word', 'indexOf also works with a whole piece of text. The indexOf(aSubString) method returns the first occurrence of aSubString in myString, or, in its absence, returns -1. There is also indexOf(aSubString, beginIndex), which begins the search at beginIndex. In "SEPTEMBER", the substring "EM" is found at index 4, but "XYZ" is not there at all.

Declare a String named myString set to "SEPTEMBER", then store the result of searching for "XYZ" in an int named missing.', 'A substring goes in double quotes. The result will be -1.', 'String myString = "SEPTEMBER"; int missing = myString.indexOf("XYZ");', 50, 8, 6, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; int missing = myString.indexOf("XYZ");', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+int\\s+missing\\s+=\\s+myString\\.indexOf\\(\\s*"XYZ"\\s*\\);', '/assets/landscapes/oakheart2.png', 'indexOf() With a Substring', 'indexOf also works with a whole piece of text. The indexOf(aSubString) method returns the first occurrence of aSubString in myString, or, in its absence, returns -1. There is also indexOf(aSubString, beginIndex), which begins the search at beginIndex. In "SEPTEMBER", the substring "EM" is found at index 4, but "XYZ" is not there at all.

Declare a String named myString set to "SEPTEMBER", then store the result of searching for "XYZ" in an int named missing.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; int missing = myString.indexOf("XYZ");', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The string to search."}, {"part": "int missing", "explanation": "Holds the index that indexOf() returns."}, {"part": "myString.indexOf(\\"XYZ\\")", "explanation": "Searches for the text XYZ. It is absent, so the result is -1."}, {"part": ";", "explanation": "Ends the statement."}]'),
(185, 6, 'Level 7', 'STRINGS AND DECISIONS', 'The Last Finder', 'The seeker now searches from the other end. The lastIndexOf() method is similar to indexOf() but finds the last occurrence of a character or string. A failed search also returns -1. In "SEPTEMBER" the last E is at index 7.

Declare a String named myString set to "SEPTEMBER", then store the index of the last \'E\' in an int named last.', 'Use lastIndexOf with the character in single quotes.', 'String myString = "SEPTEMBER"; int last = myString.lastIndexOf(\'E\');', 50, 8, 7, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; int last = myString.lastIndexOf(\'E\');', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+int\\s+last\\s+=\\s+myString\\.lastIndexOf\\(\\s*\'E\'\\s*\\);', '/assets/landscapes/oakheart3.png', 'lastIndexOf()', 'The seeker now searches from the other end. The lastIndexOf() method is similar to indexOf() but finds the last occurrence of a character or string. A failed search also returns -1. In "SEPTEMBER" the last E is at index 7.

Declare a String named myString set to "SEPTEMBER", then store the index of the last \'E\' in an int named last.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; int last = myString.lastIndexOf(\'E\');', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The string to search."}, {"part": "int last", "explanation": "Holds the index that is returned."}, {"part": "myString.lastIndexOf(\'E\')", "explanation": "Finds the last E in the string, at index 7."}, {"part": ";", "explanation": "Ends the statement."}]'),
(186, 6, 'Level 8', 'STRINGS AND DECISIONS', 'The Swap Shop', 'A shopkeeper swaps one letter for another all through a word. The replace(oldChar, newChar) method replaces oldChar with newChar and returns the new String. Replacing every E in "SEPTEMBER" with A gives "SAPTAMBAR".

Declare a String named myString set to "SEPTEMBER", then store the result of replacing \'E\' with \'A\' in a String named result.', 'Two chars separated by a comma: replace(\'E\', \'A\')', 'String myString = "SEPTEMBER"; String result = myString.replace(\'E\', \'A\');', 50, 8, 8, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; String result = myString.replace(\'E\', \'A\');', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+String\\s+result\\s+=\\s+myString\\.replace\\(\\s*\'E\',\\s*\'A\'\\s*\\);', '/assets/landscapes/oakheart4.png', 'replace()', 'A shopkeeper swaps one letter for another all through a word. The replace(oldChar, newChar) method replaces oldChar with newChar and returns the new String. Replacing every E in "SEPTEMBER" with A gives "SAPTAMBAR".

Declare a String named myString set to "SEPTEMBER", then store the result of replacing \'E\' with \'A\' in a String named result.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; String result = myString.replace(\'E\', \'A\');', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The original string."}, {"part": "String result", "explanation": "replace() returns a new String, so it is stored in a String variable."}, {"part": "myString.replace(\'E\', \'A\')", "explanation": "Replaces every E with A."}, {"part": ";", "explanation": "Ends the statement."}]'),
(187, 6, 'Level 9', 'STRINGS AND DECISIONS', 'The Slicing Blade', 'A blade slices a piece out of a word. The substring(beginIndex, endIndex) method extracts a substring starting from beginIndex. The character at endIndex is not included, so substring(0, 3) takes the characters at index 0, 1 and 2. For "SEPTEMBER" that gives "SEP".

Declare a String named myString set to "SEPTEMBER", then store the characters from index 0 up to index 3 in a String named part.', 'substring(0, 3) stops just before index 3.', 'String myString = "SEPTEMBER"; String part = myString.substring(0, 3);', 50, 8, 9, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String myString = "SEPTEMBER"; String part = myString.substring(0, 3);', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+String\\s+part\\s+=\\s+myString\\.substring\\(\\s*0,\\s*3\\s*\\);', '/assets/landscapes/oakheart1.png', 'substring()', 'A blade slices a piece out of a word. The substring(beginIndex, endIndex) method extracts a substring starting from beginIndex. The character at endIndex is not included, so substring(0, 3) takes the characters at index 0, 1 and 2. For "SEPTEMBER" that gives "SEP".

Declare a String named myString set to "SEPTEMBER", then store the characters from index 0 up to index 3 in a String named part.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; String part = myString.substring(0, 3);', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The original string."}, {"part": "String part", "explanation": "substring() returns a String."}, {"part": "myString.substring(0, 3)", "explanation": "Starts at index 0 and stops before index 3, giving SEP."}, {"part": ";", "explanation": "Ends the statement."}]'),
(188, 6, 'Level 10', 'STRINGS AND DECISIONS', 'The Case Forge', 'A forge reshapes the letters of a word. The toLowerCase() method converts all characters in myString into lowercase, and toUpperCase() converts them all into uppercase. Both return a new String. "September" becomes "september" and "SEPTEMBER".

Declare a String named myString set to "September", then store its lowercase form in lower and its uppercase form in upper.', 'Both method names use a capital letter in the middle: toLowerCase and toUpperCase.', 'String myString = "September"; String lower = myString.toLowerCase(); String upper = myString.toUpperCase();', 50, 8, 10, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'String\\s+myString\\s+=\\s+"September";\\s+String\\s+lower\\s+=\\s+myString\\.toLowerCase\\(\\s*\\s*\\);\\s+String\\s+upper\\s+=\\s+myString\\.toUpperCase\\(\\s*\\s*\\);', '/assets/landscapes/oakheart2.png', 'toLowerCase() and toUpperCase()', 'A forge reshapes the letters of a word. The toLowerCase() method converts all characters in myString into lowercase, and toUpperCase() converts them all into uppercase. Both return a new String. "September" becomes "september" and "SEPTEMBER".

Declare a String named myString set to "September", then store its lowercase form in lower and its uppercase form in upper.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "September"; String lower = myString.toLowerCase(); String upper = myString.toUpperCase();', '[{"part": "String myString = \\"September\\";", "explanation": "The original string."}, {"part": "String lower = myString.toLowerCase();", "explanation": "Converts every character to lowercase."}, {"part": "String upper = myString.toUpperCase();", "explanation": "Converts every character to uppercase."}]'),
(189, 6, 'Level 11', 'STRINGS AND DECISIONS', 'The Start and End Gates', 'Two gates check how a word begins and how it ends. The startsWith() method returns true if the string begins with the string specified, and endsWith() returns true if the string ends with it. "SEPTEMBER" starts with "SEP" and ends with "BER".

Declare a String named myString set to "SEPTEMBER", then store startsWith("SEP") in a boolean named begins and endsWith("BER") in a boolean named ends.', 'Both methods return a boolean.', 'String myString = "SEPTEMBER"; boolean begins = myString.startsWith("SEP"); boolean ends = myString.endsWith("BER");', 50, 8, 11, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'String\\s+myString\\s+=\\s+"SEPTEMBER";\\s+boolean\\s+begins\\s+=\\s+myString\\.startsWith\\(\\s*"SEP"\\s*\\);\\s+boolean\\s+ends\\s+=\\s+myString\\.endsWith\\(\\s*"BER"\\s*\\);', '/assets/landscapes/oakheart3.png', 'startsWith() and endsWith()', 'Two gates check how a word begins and how it ends. The startsWith() method returns true if the string begins with the string specified, and endsWith() returns true if the string ends with it. "SEPTEMBER" starts with "SEP" and ends with "BER".

Declare a String named myString set to "SEPTEMBER", then store startsWith("SEP") in a boolean named begins and endsWith("BER") in a boolean named ends.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String myString = "SEPTEMBER"; boolean begins = myString.startsWith("SEP"); boolean ends = myString.endsWith("BER");', '[{"part": "String myString = \\"SEPTEMBER\\";", "explanation": "The string to check."}, {"part": "boolean begins = myString.startsWith(\\"SEP\\");", "explanation": "true, because the string begins with SEP."}, {"part": "boolean ends = myString.endsWith(\\"BER\\");", "explanation": "true, because the string ends with BER."}]'),
(190, 6, 'Level 12', 'STRINGS AND DECISIONS', 'The Trimming Garden', 'A gardener clips the loose edges off every word. The trim() method trims leading and trailing spaces in myString and returns the result. Spaces in the middle of the text are left alone.

Declare a String named raw set to "  hello  " with two spaces on each side, then store the trimmed text in a String named clean.', 'Call trim() on raw. It takes no arguments.', 'String raw = "  hello  "; String clean = raw.trim();', 50, 8, 12, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: String raw = "  hello  "; String clean = raw.trim();', 'String\\s+raw\\s+=\\s+"\\s+hello\\s+";\\s+String\\s+clean\\s+=\\s+raw\\.trim\\(\\s*\\s*\\);', '/assets/landscapes/oakheart4.png', 'trim()', 'A gardener clips the loose edges off every word. The trim() method trims leading and trailing spaces in myString and returns the result. Spaces in the middle of the text are left alone.

Declare a String named raw set to "  hello  " with two spaces on each side, then store the trimmed text in a String named clean.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'String raw = "  hello  "; String clean = raw.trim();', '[{"part": "String raw = \\"  hello  \\";", "explanation": "A string with spaces at both ends."}, {"part": "String clean", "explanation": "trim() returns a new String."}, {"part": "raw.trim()", "explanation": "Removes the leading and trailing spaces, giving hello."}, {"part": ";", "explanation": "Ends the statement."}]'),
(191, 6, 'Level 13', 'STRINGS AND DECISIONS', 'The Fork in the Road', 'Pip arrives at a fork in the road. Decision control structures are Java statements that let us select and execute specific blocks of code while skipping others. The if statement runs its block if and only if a boolean expression is true. The coding guidelines say the expression must evaluate to true or false, that the statements inside should be indented, and that they should always be placed inside brackets { }.

Declare an int named grade set to 68. If grade is greater than 60, print Congratulations!', 'if ( condition ) { statement; }', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); }', 60, 8, 13, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); }', 'int\\s+grade\\s+=\\s+68;\\s+if\\s*\\(\\s*grade\\s+>\\s+60\\s*\\)\\s*\\{\\s*System\\.out\\.println\\(\\s*"Congratulations!"\\s*\\);\\s*\\}', '/assets/landscapes/oakheart1.png', 'The if Statement', 'Pip arrives at a fork in the road. Decision control structures are Java statements that let us select and execute specific blocks of code while skipping others. The if statement runs its block if and only if a boolean expression is true. The coding guidelines say the expression must evaluate to true or false, that the statements inside should be indented, and that they should always be placed inside brackets { }.

Declare an int named grade set to 68. If grade is greater than 60, print Congratulations!', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); }', '[{"part": "int grade = 68;", "explanation": "The value that will be tested."}, {"part": "if (grade > 60)", "explanation": "The boolean expression. It is true here, because 68 is greater than 60."}, {"part": "{ System.out.println(\\"Congratulations!\\"); }", "explanation": "The block that runs only when the condition is true."}]'),
(192, 6, 'Level 14', 'STRINGS AND DECISIONS', 'The Two Paths', 'The road splits in two. The if-else statement runs one block when the condition is true and a different block when it is false. The guidelines say to always place the statements of an if or if-else block inside brackets { } to avoid confusion.

Declare an int named grade set to 68. If grade is greater than 60, print Congratulations!, otherwise print Sorry you failed.', 'Put else after the closing brace of the if block.', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); } else { System.out.println("Sorry you failed"); }', 60, 8, 14, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'int\\s+grade\\s+=\\s+68;\\s+if\\s*\\(\\s*grade\\s+>\\s+60\\s*\\)\\s*\\{\\s*System\\.out\\.println\\(\\s*"Congratulations!"\\s*\\);\\s*\\}\\s*else\\s*\\{\\s*System\\.out\\.println\\(\\s*"Sorry\\s+you\\s+failed"\\s*\\);\\s*\\}', '/assets/landscapes/oakheart2.png', 'The if-else Statement', 'The road splits in two. The if-else statement runs one block when the condition is true and a different block when it is false. The guidelines say to always place the statements of an if or if-else block inside brackets { } to avoid confusion.

Declare an int named grade set to 68. If grade is greater than 60, print Congratulations!, otherwise print Sorry you failed.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); } else { System.out.println("Sorry you failed"); }', '[{"part": "if (grade > 60) { ... }", "explanation": "Runs when the condition is true."}, {"part": "else", "explanation": "Introduces the block that runs when the condition is false."}, {"part": "{ System.out.println(\\"Sorry you failed\\"); }", "explanation": "Printed when grade is 60 or less."}]'),
(193, 6, 'Level 15', 'STRINGS AND DECISIONS', 'The Double Equals', 'A guard checks whether a number is zero, and a common error waits here. Using = instead of == for comparison is wrong: a single = assigns a value, while == compares two values. Also, the condition itself must evaluate to a boolean, so writing if( number ) with an int does not work.

Declare an int named number set to 0. If number is equal to 0, print Zero.', 'Two equals signs: ==', 'int number = 0; if (number == 0) { System.out.println("Zero"); }', 60, 8, 15, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int number = 0; if (number == 0) { System.out.println("Zero"); }', 'int\\s+number\\s+=\\s+0;\\s+if\\s*\\(\\s*number\\s+==\\s+0\\s*\\)\\s*\\{\\s*System\\.out\\.println\\(\\s*"Zero"\\s*\\);\\s*\\}', '/assets/landscapes/oakheart3.png', 'Comparing With ==', 'A guard checks whether a number is zero, and a common error waits here. Using = instead of == for comparison is wrong: a single = assigns a value, while == compares two values. Also, the condition itself must evaluate to a boolean, so writing if( number ) with an int does not work.

Declare an int named number set to 0. If number is equal to 0, print Zero.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int number = 0; if (number == 0) { System.out.println("Zero"); }', '[{"part": "int number = 0;", "explanation": "The value that will be tested."}, {"part": "number == 0", "explanation": "The == operator compares the two values and gives a boolean."}, {"part": "{ System.out.println(\\"Zero\\"); }", "explanation": "Runs only when the comparison is true."}]'),
(194, 6, 'Level 16', 'STRINGS AND DECISIONS', 'The Cascade', 'The path now branches many times. The else-clause of an if-else can hold another if-else, which lets us cascade conditions to make more complex selections. You can have many else if blocks, and the final else is optional. As soon as one condition is true, the program runs that block and skips the rest. Writing elseif as one word is a common mistake, so keep the two words apart.

Declare an int named grade set to 68. If grade is above 90 print Very good!, else if it is above 60 print Good job!, otherwise print Sorry you failed.', 'if (...) { } else if (...) { } else { }', 'int grade = 68; if (grade > 90) { System.out.println("Very good!"); } else if (grade > 60) { System.out.println("Good job!"); } else { System.out.println("Sorry you failed"); }', 60, 8, 16, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'int\\s+grade\\s+=\\s+68;\\s+if\\s*\\(grade\\s+>\\s+90\\)\\s*\\{\\s*System\\.out\\.println\\("Very\\s+good!"\\);\\s*\\}\\s*else\\s+if\\s*\\(grade\\s+>\\s+60\\)\\s*\\{\\s*System\\.out\\.println\\("Good\\s+job!"\\);\\s*\\}\\s*else\\s*\\{\\s*System\\.out\\.println\\("Sorry\\s+you\\s+failed"\\);\\s*\\}', '/assets/landscapes/oakheart4.png', 'The if-else-if Statement', 'The path now branches many times. The else-clause of an if-else can hold another if-else, which lets us cascade conditions to make more complex selections. You can have many else if blocks, and the final else is optional. As soon as one condition is true, the program runs that block and skips the rest. Writing elseif as one word is a common mistake, so keep the two words apart.

Declare an int named grade set to 68. If grade is above 90 print Very good!, else if it is above 60 print Good job!, otherwise print Sorry you failed.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 68; if (grade > 90) { System.out.println("Very good!"); } else if (grade > 60) { System.out.println("Good job!"); } else { System.out.println("Sorry you failed"); }', '[{"part": "if (grade > 90) { ... }", "explanation": "Checked first. It is false for 68, so Java moves on."}, {"part": "else if (grade > 60) { ... }", "explanation": "Checked next. It is true for 68, so Good job! is printed and the rest is skipped."}, {"part": "else { ... }", "explanation": "Runs only if every earlier condition was false."}]'),
(195, 6, 'Level 17', 'STRINGS AND DECISIONS', 'The Range Gate', 'A gate only opens for a score inside a range. An if statement can make decisions based on ranges of values or conditions. To test that a value is between two limits, join two conditions with the && operator, and put each condition in its own parentheses. Both must be true for the block to run.

Declare a double named grade set to 85.0. If grade is at least 90 print Excellent!, else if grade is below 90 and at least 80 print Good job!', 'else if ((grade < 90) && (grade >= 80))', 'double grade = 85.0; if (grade >= 90) { System.out.println("Excellent!"); } else if ((grade < 90) && (grade >= 80)) { System.out.println("Good job!"); }', 60, 8, 17, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'double\\s+grade\\s+=\\s+85\\.0;\\s+if\\s*\\(grade\\s+>=\\s+90\\)\\s*\\{\\s*System\\.out\\.println\\("Excellent!"\\);\\s*\\}\\s*else\\s+if\\s*\\(\\(grade\\s+<\\s+90\\)\\s*&&\\s*\\(grade\\s+>=\\s+80\\)\\)\\s*\\{\\s*System\\.out\\.println\\("Good\\s+job!"\\);\\s*\\}', '/assets/landscapes/oakheart1.png', 'Conditions With &&', 'A gate only opens for a score inside a range. An if statement can make decisions based on ranges of values or conditions. To test that a value is between two limits, join two conditions with the && operator, and put each condition in its own parentheses. Both must be true for the block to run.

Declare a double named grade set to 85.0. If grade is at least 90 print Excellent!, else if grade is below 90 and at least 80 print Good job!', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'double grade = 85.0; if (grade >= 90) { System.out.println("Excellent!"); } else if ((grade < 90) && (grade >= 80)) { System.out.println("Good job!"); }', '[{"part": "double grade = 85.0;", "explanation": "The value that will be tested."}, {"part": "if (grade >= 90) { ... }", "explanation": "False for 85.0, so Java checks the next condition."}, {"part": "else if ((grade < 90) && (grade >= 80))", "explanation": "Both parts are true for 85.0, so the block runs. && needs both sides true."}, {"part": "{ System.out.println(\\"Good job!\\"); }", "explanation": "Printed because the range check passed."}]'),
(196, 6, 'Level 18', 'STRINGS AND DECISIONS', 'The Switchboard', 'Pip finds a switchboard with a lever for each value. The switch statement is another way to branch on multiple outcomes. The switch expression is an integer or character expression, and each case selector is a unique integer or character constant. Java jumps to the matching case and runs statements from there until it meets a break, so every case should end with break. Unlike an if block, the statements of a case do not need curly braces.

Declare an int named grade set to 100. Write a switch on grade with one case 100 that prints Excellent! and then breaks.', 'switch (grade) { case 100: statement; break; }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; }', 60, 8, 18, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution: int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; }', 'int\\s+grade\\s+=\\s+100;\\s+switch\\s*\\(\\s*grade\\s*\\)\\s*\\{\\s*case\\s+100:\\s+System\\.out\\.println\\(\\s*"Excellent!"\\s*\\);\\s+break;\\s*\\}', '/assets/landscapes/oakheart2.png', 'The switch Statement', 'Pip finds a switchboard with a lever for each value. The switch statement is another way to branch on multiple outcomes. The switch expression is an integer or character expression, and each case selector is a unique integer or character constant. Java jumps to the matching case and runs statements from there until it meets a break, so every case should end with break. Unlike an if block, the statements of a case do not need curly braces.

Declare an int named grade set to 100. Write a switch on grade with one case 100 that prints Excellent! and then breaks.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; }', '[{"part": "switch (grade)", "explanation": "Evaluates grade and jumps to the matching case."}, {"part": "case 100:", "explanation": "The case selector. The colon starts the statements for this case."}, {"part": "System.out.println(\\"Excellent!\\");", "explanation": "Runs because grade is 100."}, {"part": "break;", "explanation": "Stops Java from running the statements of the cases after this one."}]'),
(197, 6, 'Level 19', 'STRINGS AND DECISIONS', 'The Default Door', 'What if no lever matches? If none of the cases are satisfied, the default block is executed. The default part is optional, and a switch can have no default block at all. It is written with the word default followed by a colon, and it usually goes last.

Declare an int named grade set to 100. Write a switch on grade with case 100 printing Excellent! and breaking, and a default that prints Sorry, you failed.', 'default: comes after the last case.', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; default: System.out.println("Sorry, you failed."); }', 60, 8, 19, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'int\\s+grade\\s+=\\s+100;\\s+switch\\s*\\(\\s*grade\\s*\\)\\s*\\{\\s*case\\s+100:\\s+System\\.out\\.println\\(\\s*"Excellent!"\\s*\\);\\s+break;\\s+default:\\s+System\\.out\\.println\\(\\s*"Sorry,\\s*you\\s+failed\\."\\s*\\);\\s*\\}', '/assets/landscapes/oakheart3.png', 'switch With default', 'What if no lever matches? If none of the cases are satisfied, the default block is executed. The default part is optional, and a switch can have no default block at all. It is written with the word default followed by a colon, and it usually goes last.

Declare an int named grade set to 100. Write a switch on grade with case 100 printing Excellent! and breaking, and a default that prints Sorry, you failed.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; default: System.out.println("Sorry, you failed."); }', '[{"part": "case 100: ... break;", "explanation": "Runs when grade is 100."}, {"part": "default:", "explanation": "The fallback block. It runs when no case selector matches."}, {"part": "System.out.println(\\"Sorry, you failed.\\");", "explanation": "Printed for any grade that is not 100."}]'),
(198, 6, 'Level 20', 'STRINGS AND DECISIONS', 'The Grand Crossroads', 'At the Grand Crossroads every road meets. When a case is matched, Java runs its statements and also the statements of the cases that follow, unless a break stops it. That is why each case ends with break. Deciding between an if statement and a switch statement is a judgment call: a switch decides on a single integer or character value, and each case value must be unique.

Declare an int named grade set to 100. Write a switch on grade with case 100 printing Excellent!, case 90 printing Good job!, case 80 printing Study harder!, each followed by break, and a default printing Sorry, you failed.', 'Three cases, each ending in break, then a default.', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; case 90: System.out.println("Good job!"); break; case 80: System.out.println("Study harder!"); break; default: System.out.println("Sorry, you failed."); }', 100, 8, 20, 1, '2026-10-10 08:00:00', 0, 0, 0, 'Use the exact solution shown in the goal.', 'int\\s+grade\\s+=\\s+100;\\s+switch\\s*\\(grade\\)\\s*\\{\\s*case\\s+100:\\s+System\\.out\\.println\\("Excellent!"\\);\\s+break;\\s+case\\s+90:\\s+System\\.out\\.println\\("Good\\s+job!"\\);\\s+break;\\s+case\\s+80:\\s+System\\.out\\.println\\("Study\\s+harder!"\\);\\s+break;\\s+default:\\s+System\\.out\\.println\\("Sorry,\\s*you\\s+failed\\."\\);\\s*\\}', '/assets/landscapes/oakheart4.png', 'A Full switch Statement', 'At the Grand Crossroads every road meets. When a case is matched, Java runs its statements and also the statements of the cases that follow, unless a break stops it. That is why each case ends with break. Deciding between an if statement and a switch statement is a judgment call: a switch decides on a single integer or character value, and each case value must be unique.

Declare an int named grade set to 100. Write a switch on grade with case 100 printing Excellent!, case 90 printing Good job!, case 80 printing Study harder!, each followed by break, and a default printing Sorry, you failed.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; case 90: System.out.println("Good job!"); break; case 80: System.out.println("Study harder!"); break; default: System.out.println("Sorry, you failed."); }', '[{"part": "switch (grade)", "explanation": "Picks the case that matches the value of grade."}, {"part": "case 100: ... break;", "explanation": "Prints Excellent! and stops."}, {"part": "case 90: ... break;", "explanation": "Prints Good job! and stops."}, {"part": "case 80: ... break;", "explanation": "Prints Study harder! and stops."}, {"part": "default: ...", "explanation": "Runs when none of the cases match."}]');

-- 4) Guided-mode multiple choice (one step per lesson, like Islands 3 to 5).
--    Rows are cleared first so re-running this file never hits uq_guided_lesson_step.
DELETE FROM `guided_steps` WHERE `lesson_id` BETWEEN 179 AND 198;

INSERT INTO `guided_steps` (`lesson_id`, `step_order`, `prompt`, `correct_snippet`, `distractor_1`, `distractor_2`, `distractor_3`) VALUES
(179, 1, 'Which code stores the character at index 3 of "SEPTEMBER" in a char named location?', 'String myString = "SEPTEMBER"; char location = myString.charAt(3);', 'String myString = "SEPTEMBER"; char location = myString.charAt[3];', 'String myString = "SEPTEMBER"; char location = myString.charAt("3");', 'String myString = "SEPTEMBER"; String location = myString.charAt(3);'),
(180, 1, 'Which code stores the number of characters of myString in an int named size?', 'String myString = "SEPTEMBER"; int size = myString.length();', 'String myString = "SEPTEMBER"; int size = myString.length;', 'String myString = "SEPTEMBER"; int size = myString.size();', 'String myString = "SEPTEMBER"; String size = myString.length();'),
(181, 1, 'Which code stores whether string1 exactly equals string3 in a boolean named same?', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equals(string3);', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equal(string3);', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equals();', 'String string1 = "Java"; String string3 = "java"; int same = string1.equals(string3);'),
(182, 1, 'Which code compares string1 and string3 while ignoring case?', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equalsIgnoreCase(string3);', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equalsignorecase(string3);', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.equals(string3);', 'String string1 = "Java"; String string3 = "java"; boolean same = string1.ignoreCase(string3);'),
(183, 1, 'Which code stores the index of the first E in "SEPTEMBER" in an int named first?', 'String myString = "SEPTEMBER"; int first = myString.indexOf(\'E\');', 'String myString = "SEPTEMBER"; int first = myString.lastIndexOf(\'E\');', 'String myString = "SEPTEMBER"; int first = myString.indexOf(E);', 'String myString = "SEPTEMBER"; int first = myString.indexof(\'E\');'),
(184, 1, 'Which code searches myString for the text "XYZ" and stores the index in an int named missing?', 'String myString = "SEPTEMBER"; int missing = myString.indexOf("XYZ");', 'String myString = "SEPTEMBER"; int missing = myString.indexOf("XYZ")', 'String myString = "SEPTEMBER"; boolean missing = myString.indexOf("XYZ");', 'String myString = "SEPTEMBER"; int missing = myString.indexOf(XYZ);'),
(185, 1, 'Which code stores the index of the last E in "SEPTEMBER" in an int named last?', 'String myString = "SEPTEMBER"; int last = myString.lastIndexOf(\'E\');', 'String myString = "SEPTEMBER"; int last = myString.indexOf(\'E\');', 'String myString = "SEPTEMBER"; int last = myString.lastindexOf(\'E\');', 'String myString = "SEPTEMBER"; int last = myString.lastIndexOf();'),
(186, 1, 'Which code replaces every E in myString with A and stores the new String in result?', 'String myString = "SEPTEMBER"; String result = myString.replace(\'E\', \'A\');', 'String myString = "SEPTEMBER"; String result = myString.replace(\'E\');', 'String myString = "SEPTEMBER"; String result = myString.replace(\'E\' \'A\');', 'String myString = "SEPTEMBER"; char result = myString.replace(\'E\', \'A\');'),
(187, 1, 'Which code stores the first three characters of myString in a String named part?', 'String myString = "SEPTEMBER"; String part = myString.substring(0, 3);', 'String myString = "SEPTEMBER"; String part = myString.substring(3, 0);', 'String myString = "SEPTEMBER"; String part = myString.substring("SEP");', 'String myString = "SEPTEMBER"; String part = myString.substr(0, 3);'),
(188, 1, 'Which code stores the lowercase form of myString in lower and the uppercase form in upper?', 'String myString = "September"; String lower = myString.toLowerCase(); String upper = myString.toUpperCase();', 'String myString = "September"; String lower = myString.toUpperCase(); String upper = myString.toLowerCase();', 'String myString = "September"; String lower = myString.lower(); String upper = myString.upper();', 'String myString = "September"; String lower = myString.toLowerCase(); String upper = myString.toUppercase();'),
(189, 1, 'Which code checks whether myString starts with "SEP" and ends with "BER"?', 'String myString = "SEPTEMBER"; boolean begins = myString.startsWith("SEP"); boolean ends = myString.endsWith("BER");', 'String myString = "SEPTEMBER"; boolean begins = myString.endsWith("SEP"); boolean ends = myString.startsWith("BER");', 'String myString = "SEPTEMBER"; boolean begins = myString.startsWith("SEP"); boolean ends = myString.endWith("BER");', 'String myString = "SEPTEMBER"; boolean begins = myString.startsWith("SEP"); String ends = myString.endsWith("BER");'),
(190, 1, 'Which code removes the leading and trailing spaces from raw and stores the result in clean?', 'String raw = "  hello  "; String clean = raw.trim();', 'String raw = "  hello  "; String clean = raw.trim;', 'String raw = "  hello  "; String clean = raw.cut();', 'String raw = "  hello  "; String clean = trim(raw);'),
(191, 1, 'Which code prints Congratulations! only when grade is greater than 60?', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); }', 'int grade = 68; if grade > 60 { System.out.println("Congratulations!"); }', 'int grade = 68; if (grade = 60) { System.out.println("Congratulations!"); }', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!") }'),
(192, 1, 'Which code prints Congratulations! when grade is above 60 and Sorry you failed otherwise?', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); } else { System.out.println("Sorry you failed"); }', 'int grade = 68; if (grade > 60) { System.out.println("Sorry you failed"); } else { System.out.println("Congratulations!"); }', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); } else if { System.out.println("Sorry you failed"); }', 'int grade = 68; if (grade > 60) { System.out.println("Congratulations!"); } else { System.out.println("Sorry you failed");'),
(193, 1, 'Which code correctly tests whether number is equal to 0?', 'int number = 0; if (number == 0) { System.out.println("Zero"); }', 'int number = 0; if (number = 0) { System.out.println("Zero"); }', 'int number = 0; if (number) { System.out.println("Zero"); }', 'int number = 0; if (number === 0) { System.out.println("Zero"); }'),
(194, 1, 'Which code prints Very good! above 90, Good job! above 60 and Sorry you failed otherwise?', 'int grade = 68; if (grade > 90) { System.out.println("Very good!"); } else if (grade > 60) { System.out.println("Good job!"); } else { System.out.println("Sorry you failed"); }', 'int grade = 68; if (grade > 90) { System.out.println("Very good!"); } elseif (grade > 60) { System.out.println("Good job!"); } else { System.out.println("Sorry you failed"); }', 'int grade = 68; if (grade > 90) { System.out.println("Very good!"); } else (grade > 60) { System.out.println("Good job!"); } else { System.out.println("Sorry you failed"); }', 'int grade = 68; if (grade > 60) { System.out.println("Very good!"); } else if (grade > 90) { System.out.println("Good job!"); } else { System.out.println("Sorry you failed"); }'),
(195, 1, 'Which code prints Good job! only when grade is below 90 and at least 80?', 'double grade = 85.0; if (grade >= 90) { System.out.println("Excellent!"); } else if ((grade < 90) && (grade >= 80)) { System.out.println("Good job!"); }', 'double grade = 85.0; if (grade >= 90) { System.out.println("Excellent!"); } else if ((grade < 90) and (grade >= 80)) { System.out.println("Good job!"); }', 'double grade = 85.0; if (grade >= 90) { System.out.println("Excellent!"); } else if ((grade < 90) && (grade >= 80) { System.out.println("Good job!"); }', 'double grade = 85.0; if (grade >= 90) { System.out.println("Excellent!"); } else if ((grade < 90) || (grade >= 80)) { System.out.println("Good job!"); }'),
(196, 1, 'Which code uses a switch on grade with a case 100 that prints Excellent! and breaks?', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; }', 'int grade = 100; switch (grade) { case 100; System.out.println("Excellent!"); break; }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break }', 'int grade = 100; switch grade { case 100: System.out.println("Excellent!"); break; }'),
(197, 1, 'Which switch prints Excellent! for 100 and Sorry, you failed. for any other grade?', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; default: System.out.println("Sorry, you failed."); }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; else: System.out.println("Sorry, you failed."); }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; default System.out.println("Sorry, you failed."); }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; case default: System.out.println("Sorry, you failed."); }'),
(198, 1, 'Which switch ends every case with break so that matching one case does not run the next?', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; case 90: System.out.println("Good job!"); break; case 80: System.out.println("Study harder!"); break; default: System.out.println("Sorry, you failed."); }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); case 90: System.out.println("Good job!"); break; case 80: System.out.println("Study harder!"); break; default: System.out.println("Sorry, you failed."); }', 'int grade = 100; switch (grade) { case 100: System.out.println("Excellent!"); break; case 100: System.out.println("Good job!"); break; case 80: System.out.println("Study harder!"); break; default: System.out.println("Sorry, you failed."); }', 'int grade = 100; switch (grade) { case "100": System.out.println("Excellent!"); break; case 90: System.out.println("Good job!"); break; case 80: System.out.println("Study harder!"); break; default: System.out.println("Sorry, you failed."); }');

ALTER TABLE `lessons` AUTO_INCREMENT=199;
