-- ============================================================
-- ISLAND 4: VARIABLES AND OPERATORS  (Chapter 5 + Chapter 6)
-- 20 levels. Lesson ids 139-158, module_id 4.
-- Levels 1-8  = Chapter 5 (Variables)
-- Levels 9-20 = Chapter 6 (Operators)
-- ============================================================

-- 1) The lessons table has a foreign key to lesson_modules, so module 4 must exist first.
--    (Your lessons dump does not include lesson_modules, so copy the column list from
--     your own module 3 row. Example only, adjust the columns to match your table:)
-- INSERT INTO `lesson_modules` (`id`, `title`, ...) VALUES (4, 'Variables and Operators', ...);

-- 2) Clear any existing Island 4 rows so re-running this file never hits
--    "Duplicate entry '4-1' for key 'uq_lessons_module_order'".
--    First look at what is there:
--      SELECT id, module_id, order_index, title FROM lessons WHERE module_id = 4 OR id >= 139;
-- Removes the old Island 4 snippets, including any old rows that sit on ids 139-158
-- under a different module_id (those would otherwise cause a primary-key error).
DELETE FROM `lessons` WHERE `module_id` = 4 OR `id` BETWEEN 139 AND 158;

-- OPTIONAL: if players already have saved progress for the OLD lessons 139-158, the new
-- levels would show as already completed. Clear it with your progress table's real name, e.g.:
-- DELETE FROM `user_progress` WHERE `lesson_id` BETWEEN 139 AND 158;

-- 3) The lessons
INSERT INTO `lessons` (`id`, `module_id`, `level_label`, `track`, `title`, `briefing`, `hint`, `goal`, `xp_reward`, `target_tiles`, `order_index`, `is_active`, `created_at`, `min_moves`, `min_says`, `min_jumps`, `required_code_label`, `required_code_pattern`, `background_image`, `subtitle`, `description`, `grid_cols`, `grid_rows`, `mechanics_config`, `total_tiles`, `ground_fraction`, `initial_tile`, `flag_tile`, `solution_code`, `line_breakdown`) VALUES
(139, 4, 'Level 1', 'VARIABLES AND OPERATORS', 'The Variable Vault', 'Pip reaches Variable Vault on Datum Isle. A variable is an item of data used to store the state of objects. Every variable has a data type and a name, and the type says what kind of value it can hold. To declare and initialize one, write: <data type> <name> = initial value;

The vault door wants Pip\'s starting health. Declare an int named lives and initialize it to 3.', 'Data type first, then the name, then = and the value, ending with a semicolon.', 'int lives = 3;', 50, 8, 1, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int lives = 3;', 'int\\s+lives\\s+=\\s+3;', '/assets/landscapes/oakheart1.png', 'Declaring a Variable', 'Pip reaches Variable Vault on Datum Isle. A variable is an item of data used to store the state of objects. Every variable has a data type and a name, and the type says what kind of value it can hold. To declare and initialize one, write: <data type> <name> = initial value;

The vault door wants Pip\'s starting health. Declare an int named lives and initialize it to 3.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int lives = 3;', '[{"part": "int", "explanation": "The data type. It tells Java this variable holds a whole number."}, {"part": "lives", "explanation": "The variable name. It should describe the data it stores."}, {"part": "=", "explanation": "The assignment operator stores the value on the right in the variable."}, {"part": "3", "explanation": "The initial value stored in lives."}, {"part": ";", "explanation": "Ends the declaration statement."}]'),
(140, 4, 'Level 2', 'VARIABLES AND OPERATORS', 'The Split Spell', 'A variable does not have to be given a value the moment it is declared. First you declare a data type with a variable name, then you assign a value on a later line. A char holds a single character, written between single quotes.

Declare a char named option, then assign \'C\' to it on the next statement.', 'Declare: char option; Then assign: option = \'C\';', 'char option; option = \'C\';', 50, 8, 2, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: char option; option = \'C\';', 'char\\s+option;\\s+option\\s+=\\s+\'C\';', '/assets/landscapes/oakheart2.png', 'Declare, Then Assign', 'A variable does not have to be given a value the moment it is declared. First you declare a data type with a variable name, then you assign a value on a later line. A char holds a single character, written between single quotes.

Declare a char named option, then assign \'C\' to it on the next statement.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'char option; option = \'C\';', '[{"part": "char option;", "explanation": "Declares a char variable named option without giving it a value yet."}, {"part": "option", "explanation": "Refers to the variable that was already declared."}, {"part": "=", "explanation": "Assigns the value on the right to the variable."}, {"part": "\'C\'", "explanation": "A char literal. Single quotes mark exactly one character."}, {"part": ";", "explanation": "Each statement ends with a semicolon."}]'),
(141, 4, 'Level 3', 'VARIABLES AND OPERATORS', 'The Grade Ledger', 'The ledger records a grade with a decimal point. The double data type stores floating-point numbers. The coding guidelines say it is always good to initialize your variables as you declare them, and to use descriptive names, so a variable holding a student\'s grade should be called grade and not some random letters.

Declare a double named grade and initialize it to 0.0.', 'double grade = 0.0;', 'double grade = 0.0;', 50, 8, 3, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: double grade = 0.0;', 'double\\s+grade\\s+=\\s+0\\.0;', '/assets/landscapes/oakheart3.png', 'Initializing a double', 'The ledger records a grade with a decimal point. The double data type stores floating-point numbers. The coding guidelines say it is always good to initialize your variables as you declare them, and to use descriptive names, so a variable holding a student\'s grade should be called grade and not some random letters.

Declare a double named grade and initialize it to 0.0.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'double grade = 0.0;', '[{"part": "double", "explanation": "The data type for numbers with a fractional part."}, {"part": "grade", "explanation": "A descriptive variable name, as the coding guidelines recommend."}, {"part": "=", "explanation": "Assigns the initial value."}, {"part": "0.0", "explanation": "A double literal."}, {"part": ";", "explanation": "Ends the declaration."}]'),
(142, 4, 'Level 4', 'VARIABLES AND OPERATORS', 'One Line, One Variable', 'A scribe warns Pip about a messy habit. The coding guidelines say to declare one variable per line of code. So three variables should be written as three separate declarations, not packed into one line with commas.

Declare exam as 0, quiz as 10 and grade as 0, each as a double on its own statement.', 'Three separate declarations, each starting with double.', 'double exam = 0; double quiz = 10; double grade = 0;', 50, 8, 4, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: double exam = 0; double quiz = 10; double grade = 0;', 'double\\s+exam\\s+=\\s+0;\\s+double\\s+quiz\\s+=\\s+10;\\s+double\\s+grade\\s+=\\s+0;', '/assets/landscapes/oakheart4.png', 'Coding Guideline: One Per Line', 'A scribe warns Pip about a messy habit. The coding guidelines say to declare one variable per line of code. So three variables should be written as three separate declarations, not packed into one line with commas.

Declare exam as 0, quiz as 10 and grade as 0, each as a double on its own statement.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'double exam = 0; double quiz = 10; double grade = 0;', '[{"part": "double exam = 0;", "explanation": "First variable, declared and initialized by itself."}, {"part": "double quiz = 10;", "explanation": "Second variable on its own statement."}, {"part": "double grade = 0;", "explanation": "Third variable on its own statement. One declaration per line is easier to read than double exam=0, quiz=10, grade=0;"}]'),
(143, 4, 'Level 5', 'VARIABLES AND OPERATORS', 'The Truth Switch', 'A stone switch can only be on or off. The boolean data type holds the values true or false. The guide declares one named result, and a variable can be declared first and assigned later.

Declare a boolean named result, then assign true to it.', 'boolean result; result = true;', 'boolean result; result = true;', 50, 8, 5, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: boolean result; result = true;', 'boolean\\s+result;\\s+result\\s+=\\s+true;', '/assets/landscapes/oakheart1.png', 'Boolean Variables', 'A stone switch can only be on or off. The boolean data type holds the values true or false. The guide declares one named result, and a variable can be declared first and assigned later.

Declare a boolean named result, then assign true to it.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'boolean result; result = true;', '[{"part": "boolean result;", "explanation": "Declares a boolean variable named result."}, {"part": "result", "explanation": "Refers to the declared variable."}, {"part": "=", "explanation": "Assigns a value."}, {"part": "true", "explanation": "A boolean literal. It is lowercase with no quotation marks."}, {"part": ";", "explanation": "Ends the statement."}]'),
(144, 4, 'Level 6', 'VARIABLES AND OPERATORS', 'The Echo Chamber', 'In the Echo Chamber, Pip\'s voice repeats whatever variable he shouts. To output the value of a variable, use System.out.println() or System.out.print(). In the sample program, int value = 10 is printed with System.out.println(value), which shows 10 on screen.

Declare int value = 10 and print it with System.out.println.', 'Put the variable name inside the parentheses, with no quotes.', 'int value = 10; System.out.println(value);', 50, 8, 6, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int value = 10; System.out.println(value);', 'int\\s+value\\s+=\\s+10;\\s+System\\.out\\.println\\(value\\);', '/assets/landscapes/oakheart2.png', 'Outputting Variable Data', 'In the Echo Chamber, Pip\'s voice repeats whatever variable he shouts. To output the value of a variable, use System.out.println() or System.out.print(). In the sample program, int value = 10 is printed with System.out.println(value), which shows 10 on screen.

Declare int value = 10 and print it with System.out.println.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int value = 10; System.out.println(value);', '[{"part": "int value = 10;", "explanation": "Declares and initializes the variable that will be printed."}, {"part": "System.out.println", "explanation": "The command that prints a value and then adds a newline."}, {"part": "(value)", "explanation": "The variable name goes inside the parentheses. Without quotes, Java prints the stored value, not the word value."}, {"part": ";", "explanation": "Ends the print statement."}]'),
(145, 4, 'Level 7', 'VARIABLES AND OPERATORS', 'The Joined Message', 'The echo can carry words and a variable together. Text in double quotes can be joined to a variable with the + operator. In the guide, the program prints The value of x=A.

Declare char x = \'A\' and print the text "The value of x=" joined to x.', 'Use + between the quoted text and x.', 'char x = \'A\'; System.out.println("The value of x=" + x);', 50, 8, 7, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: char x = \'A\'; System.out.println("The value of x=" + x);', 'char\\s+x\\s+=\\s+\'A\';\\s+System\\.out\\.println\\("The\\s+value\\s+of\\s+x="\\s+\\+\\s+x\\);', '/assets/landscapes/oakheart3.png', 'Printing Text and a Variable', 'The echo can carry words and a variable together. Text in double quotes can be joined to a variable with the + operator. In the guide, the program prints The value of x=A.

Declare char x = \'A\' and print the text "The value of x=" joined to x.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'char x = \'A\'; System.out.println("The value of x=" + x);', '[{"part": "char x = \'A\';", "explanation": "Declares and initializes a char variable."}, {"part": "System.out.println(", "explanation": "Starts the print command."}, {"part": "\\"The value of x=\\"", "explanation": "A String literal that is printed as-is."}, {"part": "+ x", "explanation": "The + joins the text with the value stored in x."}, {"part": ");", "explanation": "Closes the command and ends the statement."}]'),
(146, 4, 'Level 8', 'VARIABLES AND OPERATORS', 'Print vs. Println', 'Two echo stones look alike but behave differently. System.out.println() adds a newline at the end of the data it prints, while System.out.print() does not. Two print calls with "Hello " and "world!" show Hello world on a single line.

Use System.out.print twice so the words Hello and world! appear on the same line.', 'Use print, not println. Keep the space inside the first string.', 'System.out.print("Hello "); System.out.print("world!");', 50, 8, 8, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: System.out.print("Hello "); System.out.print("world!");', 'System\\.out\\.print\\("Hello\\s+"\\);\\s+System\\.out\\.print\\("world!"\\);', '/assets/landscapes/oakheart4.png', 'print() Versus println()', 'Two echo stones look alike but behave differently. System.out.println() adds a newline at the end of the data it prints, while System.out.print() does not. Two print calls with "Hello " and "world!" show Hello world on a single line.

Use System.out.print twice so the words Hello and world! appear on the same line.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'System.out.print("Hello "); System.out.print("world!");', '[{"part": "System.out.print(\\"Hello \\");", "explanation": "Prints Hello and a space, and stays on the same line."}, {"part": "System.out.print(\\"world!\\");", "explanation": "Prints world! right after it, so the output reads Hello world!"}, {"part": "print vs println", "explanation": "print() adds no newline. println() would have put the words on two lines."}]'),
(147, 4, 'Level 9', 'VARIABLES AND OPERATORS', 'The Adding Bridge', 'Pip enters the Operator Ruins. Java has arithmetic operators: + adds, - subtracts, * multiplies, / divides and % gives the remainder. Using op1 + op2 adds the two operands.

In the sample program, i is 37 and j is 42, and i + j is 79.

Store the sum of 37 and 42 in an int named sum.', 'int sum = 37 + 42;', 'int sum = 37 + 42;', 60, 8, 9, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int sum = 37 + 42;', 'int\\s+sum\\s+=\\s+37\\s+\\+\\s+42;', '/assets/landscapes/oakheart1.png', 'Arithmetic: Addition', 'Pip enters the Operator Ruins. Java has arithmetic operators: + adds, - subtracts, * multiplies, / divides and % gives the remainder. Using op1 + op2 adds the two operands.

In the sample program, i is 37 and j is 42, and i + j is 79.

Store the sum of 37 and 42 in an int named sum.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int sum = 37 + 42;', '[{"part": "int sum", "explanation": "Declares an int variable that will hold the result."}, {"part": "=", "explanation": "Stores the result of the expression on the right."}, {"part": "37 + 42", "explanation": "The + operator adds its two operands, giving 79."}, {"part": ";", "explanation": "Ends the statement."}]'),
(148, 4, 'Level 10', 'VARIABLES AND OPERATORS', 'The Leftover Stones', 'The % operator computes the remainder of dividing op1 by op2. In the guide, i % j with i = 37 and j = 42 gives 37, because 42 does not fit into 37 at all. With int operands, i / j gives 0 because the fractional part is dropped.

Declare int i = 37 and int j = 42, then store i % j in an int named remainder.', 'Use the variables i and j, not the numbers directly.', 'int i = 37; int j = 42; int remainder = i % j;', 60, 8, 10, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 37; int j = 42; int remainder = i % j;', 'int\\s+i\\s+=\\s+37;\\s+int\\s+j\\s+=\\s+42;\\s+int\\s+remainder\\s+=\\s+i\\s+%\\s+j;', '/assets/landscapes/oakheart2.png', 'Arithmetic: Remainder', 'The % operator computes the remainder of dividing op1 by op2. In the guide, i % j with i = 37 and j = 42 gives 37, because 42 does not fit into 37 at all. With int operands, i / j gives 0 because the fractional part is dropped.

Declare int i = 37 and int j = 42, then store i % j in an int named remainder.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 37; int j = 42; int remainder = i % j;', '[{"part": "int i = 37; int j = 42;", "explanation": "The two operands, stored in variables."}, {"part": "int remainder", "explanation": "The variable that will hold the result."}, {"part": "i % j", "explanation": "The % operator gives the remainder of i divided by j. Here it is 37."}, {"part": ";", "explanation": "Ends the statement."}]'),
(149, 4, 'Level 11', 'VARIABLES AND OPERATORS', 'The Mixed Bridge', 'When an integer and a floating-point number are used together in one arithmetic operation, the integer is implicitly converted to a floating-point number first, so the result is a floating-point number. In the guide, j + y with j = 42 and y = 7.22 gives 49.22.

Store 42 + 7.22 in a double named total.', 'The result has a decimal part, so it needs a double.', 'double total = 42 + 7.22;', 60, 8, 11, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: double total = 42 + 7.22;', 'double\\s+total\\s+=\\s+42\\s+\\+\\s+7\\.22;', '/assets/landscapes/oakheart3.png', 'Mixing int and double', 'When an integer and a floating-point number are used together in one arithmetic operation, the integer is implicitly converted to a floating-point number first, so the result is a floating-point number. In the guide, j + y with j = 42 and y = 7.22 gives 49.22.

Store 42 + 7.22 in a double named total.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'double total = 42 + 7.22;', '[{"part": "double total", "explanation": "A double is needed because mixing int and double produces a floating-point result."}, {"part": "=", "explanation": "Stores the result."}, {"part": "42 + 7.22", "explanation": "The int 42 is converted to a double before the addition, giving 49.22."}, {"part": ";", "explanation": "Ends the statement."}]'),
(150, 4, 'Level 12', 'VARIABLES AND OPERATORS', 'The Climbing Counter', 'Java has the unary increment operator ++ and decrement operator --. They add or subtract 1 from a variable. When ++ is placed before the operand, the variable is incremented first and the new value is used in the expression.

In the guide, with i = 10 and j = 3, k = (++j) + i gives 4 + 10 = 14.

Declare i = 10, j = 3 and k = 0, then store ++j + i in k.', 'Write k = ++j + i; after the three declarations.', 'int i = 10; int j = 3; int k = 0; k = ++j + i;', 60, 8, 12, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 10; int j = 3; int k = 0; k = ++j + i;', 'int\\s+i\\s+=\\s+10;\\s+int\\s+j\\s+=\\s+3;\\s+int\\s+k\\s+=\\s+0;\\s+k\\s+=\\s+\\+\\+j\\s+\\+\\s+i;', '/assets/landscapes/oakheart4.png', 'Pre-Increment', 'Java has the unary increment operator ++ and decrement operator --. They add or subtract 1 from a variable. When ++ is placed before the operand, the variable is incremented first and the new value is used in the expression.

In the guide, with i = 10 and j = 3, k = (++j) + i gives 4 + 10 = 14.

Declare i = 10, j = 3 and k = 0, then store ++j + i in k.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 10; int j = 3; int k = 0; k = ++j + i;', '[{"part": "int i = 10; int j = 3; int k = 0;", "explanation": "The three starting variables."}, {"part": "k =", "explanation": "Stores the result in k."}, {"part": "++j", "explanation": "Pre-increment. j becomes 4 first, then 4 is used."}, {"part": "+ i", "explanation": "Adds i, which is 10, so k becomes 14."}, {"part": ";", "explanation": "Ends the statement."}]'),
(151, 4, 'Level 13', 'VARIABLES AND OPERATORS', 'The Delayed Step', 'When the increment operator is placed after the operand, the old value is used in the expression and the variable is incremented afterwards. In the guide, k = (j++) + i with j = 3 and i = 10 gives 3 + 10 = 13, and j becomes 4 afterwards.

The guide also says count++ is equivalent to count = count + 1.

Declare int count = 0, then increase it by 1 with the ++ operator.', 'Write count++; on its own statement.', 'int count = 0; count++;', 60, 8, 13, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int count = 0; count++;', 'int\\s+count\\s+=\\s+0;\\s+count\\+\\+;', '/assets/landscapes/oakheart1.png', 'Post-Increment', 'When the increment operator is placed after the operand, the old value is used in the expression and the variable is incremented afterwards. In the guide, k = (j++) + i with j = 3 and i = 10 gives 3 + 10 = 13, and j becomes 4 afterwards.

The guide also says count++ is equivalent to count = count + 1.

Declare int count = 0, then increase it by 1 with the ++ operator.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int count = 0; count++;', '[{"part": "int count = 0;", "explanation": "Declares the counter and starts it at 0."}, {"part": "count++", "explanation": "The post-increment operator adds 1 to count. It is equivalent to count = count + 1."}, {"part": ";", "explanation": "Ends the statement."}]'),
(152, 4, 'Level 14', 'VARIABLES AND OPERATORS', 'The Weighing Scale', 'Relational operators compare two values and produce a boolean result, true or false. The operators are >, >=, <, <=, == and !=. In the guide, j and k are both 42, so k == j is true.

Declare int j = 42 and int k = 42, then store the result of j == k in a boolean named same.', 'Use == to compare. A single = would assign.', 'int j = 42; int k = 42; boolean same = j == k;', 60, 8, 14, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int j = 42; int k = 42; boolean same = j == k;', 'int\\s+j\\s+=\\s+42;\\s+int\\s+k\\s+=\\s+42;\\s+boolean\\s+same\\s+=\\s+j\\s+==\\s+k;', '/assets/landscapes/oakheart2.png', 'Relational Operators', 'Relational operators compare two values and produce a boolean result, true or false. The operators are >, >=, <, <=, == and !=. In the guide, j and k are both 42, so k == j is true.

Declare int j = 42 and int k = 42, then store the result of j == k in a boolean named same.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int j = 42; int k = 42; boolean same = j == k;', '[{"part": "int j = 42; int k = 42;", "explanation": "Two equal values."}, {"part": "boolean same", "explanation": "A relational expression produces a boolean, so the result goes in a boolean."}, {"part": "j == k", "explanation": "The equality operator. It is true because both values are 42."}, {"part": ";", "explanation": "Ends the statement."}]'),
(153, 4, 'Level 15', 'VARIABLES AND OPERATORS', 'The Short-Circuit Gate', 'The && operator is true only when both operands are true. It supports short-circuit evaluation: if the first expression is false, the second is never evaluated. The & operator always evaluates both.

In the guide, with i = 0 and j = 10, (i > 10) && (j++ > 9) leaves j at 10 because j++ is skipped.

Declare i = 0, j = 10 and a boolean test, then assign (i > 10) && (j++ > 9) to test.', 'Declare boolean test = false; first, then assign.', 'int i = 0; int j = 10; boolean test = false; test = (i > 10) && (j++ > 9);', 60, 8, 15, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 0; int j = 10; boolean test = false; test = (i > 10) && (j++ > 9);', 'int\\s+i\\s+=\\s+0;\\s+int\\s+j\\s+=\\s+10;\\s+boolean\\s+test\\s+=\\s+false;\\s+test\\s+=\\s+\\(i\\s+>\\s+10\\)\\s+&&\\s+\\(j\\+\\+\\s+>\\s+9\\);', '/assets/landscapes/oakheart3.png', 'Logical AND (&&)', 'The && operator is true only when both operands are true. It supports short-circuit evaluation: if the first expression is false, the second is never evaluated. The & operator always evaluates both.

In the guide, with i = 0 and j = 10, (i > 10) && (j++ > 9) leaves j at 10 because j++ is skipped.

Declare i = 0, j = 10 and a boolean test, then assign (i > 10) && (j++ > 9) to test.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 0; int j = 10; boolean test = false; test = (i > 10) && (j++ > 9);', '[{"part": "int i = 0; int j = 10; boolean test = false;", "explanation": "The starting values."}, {"part": "(i > 10)", "explanation": "False, because i is 0."}, {"part": "&&", "explanation": "Short-circuit AND. Since the left side is false, the right side is never evaluated."}, {"part": "(j++ > 9)", "explanation": "Skipped, so j stays 10."}, {"part": ";", "explanation": "Ends the statement."}]'),
(154, 4, 'Level 16', 'VARIABLES AND OPERATORS', 'The Either Door', 'The || operator is true when at least one operand is true. It also short-circuits: if the first expression is true, the second is never evaluated. The | operator always evaluates both.

In the guide, with i = 0 and j = 10, (i < 10) || (j++ > 9) is true and j stays 10.

Declare i = 0, j = 10 and a boolean test, then assign (i < 10) || (j++ > 9) to test.', 'Same shape as the AND level, with || and i < 10.', 'int i = 0; int j = 10; boolean test = false; test = (i < 10) || (j++ > 9);', 60, 8, 16, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int i = 0; int j = 10; boolean test = false; test = (i < 10) || (j++ > 9);', 'int\\s+i\\s+=\\s+0;\\s+int\\s+j\\s+=\\s+10;\\s+boolean\\s+test\\s+=\\s+false;\\s+test\\s+=\\s+\\(i\\s+<\\s+10\\)\\s+\\|\\|\\s+\\(j\\+\\+\\s+>\\s+9\\);', '/assets/landscapes/oakheart4.png', 'Logical OR (||)', 'The || operator is true when at least one operand is true. It also short-circuits: if the first expression is true, the second is never evaluated. The | operator always evaluates both.

In the guide, with i = 0 and j = 10, (i < 10) || (j++ > 9) is true and j stays 10.

Declare i = 0, j = 10 and a boolean test, then assign (i < 10) || (j++ > 9) to test.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int i = 0; int j = 10; boolean test = false; test = (i < 10) || (j++ > 9);', '[{"part": "int i = 0; int j = 10; boolean test = false;", "explanation": "The starting values."}, {"part": "(i < 10)", "explanation": "True, because i is 0."}, {"part": "||", "explanation": "Short-circuit OR. The left side is true, so the right side is never evaluated."}, {"part": "(j++ > 9)", "explanation": "Skipped, so j stays 10."}, {"part": ";", "explanation": "Ends the statement."}]'),
(155, 4, 'Level 17', 'VARIABLES AND OPERATORS', 'The Exclusive Choice', 'The ^ operator is true if and only if one operand is true and the other is false. Both operands are always evaluated. In the guide, true ^ true is false, and true ^ false is true.

Declare boolean val1 = true and boolean val2 = false, then store val1 ^ val2 in a boolean named xor.', 'The two values are different, so the result is true.', 'boolean val1 = true; boolean val2 = false; boolean xor = val1 ^ val2;', 60, 8, 17, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: boolean val1 = true; boolean val2 = false; boolean xor = val1 ^ val2;', 'boolean\\s+val1\\s+=\\s+true;\\s+boolean\\s+val2\\s+=\\s+false;\\s+boolean\\s+xor\\s+=\\s+val1\\s+\\^\\s+val2;', '/assets/landscapes/oakheart1.png', 'Exclusive OR (^)', 'The ^ operator is true if and only if one operand is true and the other is false. Both operands are always evaluated. In the guide, true ^ true is false, and true ^ false is true.

Declare boolean val1 = true and boolean val2 = false, then store val1 ^ val2 in a boolean named xor.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'boolean val1 = true; boolean val2 = false; boolean xor = val1 ^ val2;', '[{"part": "boolean val1 = true; boolean val2 = false;", "explanation": "Two different boolean values."}, {"part": "boolean xor", "explanation": "Holds the result."}, {"part": "val1 ^ val2", "explanation": "Exclusive OR. It is true here because exactly one operand is true."}, {"part": ";", "explanation": "Ends the statement."}]'),
(156, 4, 'Level 18', 'VARIABLES AND OPERATORS', 'The Mirror of Truth', 'The ! operator takes one operand and flips it: !true is false and !false is true.

Declare boolean val1 = true, then store !val1 in a boolean named flipped.', 'Put ! directly before the variable name.', 'boolean val1 = true; boolean flipped = !val1;', 60, 8, 18, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: boolean val1 = true; boolean flipped = !val1;', 'boolean\\s+val1\\s+=\\s+true;\\s+boolean\\s+flipped\\s+=\\s+!val1;', '/assets/landscapes/oakheart2.png', 'Logical NOT (!)', 'The ! operator takes one operand and flips it: !true is false and !false is true.

Declare boolean val1 = true, then store !val1 in a boolean named flipped.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'boolean val1 = true; boolean flipped = !val1;', '[{"part": "boolean val1 = true;", "explanation": "The value that will be flipped."}, {"part": "boolean flipped", "explanation": "Holds the result."}, {"part": "!val1", "explanation": "Logical NOT. It turns true into false."}, {"part": ";", "explanation": "Ends the statement."}]'),
(157, 4, 'Level 19', 'VARIABLES AND OPERATORS', 'The Verdict Stone', 'The conditional operator ?: is a ternary operator with three parts: exp1 ? exp2 : exp3. If exp1 is true, exp2 is the result, otherwise exp3 is. In the guide, a grade of 80 gives "Passed" when the test is grade >= 60.

Declare int grade = 80, then store (grade >= 60) ? "Passed" : "Fail" in a String named status.', 'Condition ? valueIfTrue : valueIfFalse', 'int grade = 80; String status = (grade >= 60) ? "Passed" : "Fail";', 60, 8, 19, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int grade = 80; String status = (grade >= 60) ? "Passed" : "Fail";', 'int\\s+grade\\s+=\\s+80;\\s+String\\s+status\\s+=\\s+\\(grade\\s+>=\\s+60\\)\\s+\\?\\s+"Passed"\\s+:\\s+"Fail";', '/assets/landscapes/oakheart3.png', 'Conditional Operator (?:)', 'The conditional operator ?: is a ternary operator with three parts: exp1 ? exp2 : exp3. If exp1 is true, exp2 is the result, otherwise exp3 is. In the guide, a grade of 80 gives "Passed" when the test is grade >= 60.

Declare int grade = 80, then store (grade >= 60) ? "Passed" : "Fail" in a String named status.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int grade = 80; String status = (grade >= 60) ? "Passed" : "Fail";', '[{"part": "int grade = 80;", "explanation": "The value being tested."}, {"part": "String status", "explanation": "Holds the text result."}, {"part": "(grade >= 60)", "explanation": "The boolean condition. It is true because 80 is at least 60."}, {"part": "? \\"Passed\\"", "explanation": "Chosen when the condition is true."}, {"part": ": \\"Fail\\"", "explanation": "Chosen when the condition is false."}, {"part": ";", "explanation": "Ends the statement."}]'),
(158, 4, 'Level 20', 'VARIABLES AND OPERATORS', 'The Order of Operations', 'At the end of the ruins, a final puzzle is carved: 6%2*5+4/2+88-10. Operator precedence tells the compiler the order of evaluation, so the expression is the same as ((6%2)*5)+(4/2)+88-10. The coding guideline says to keep expressions simple and use parentheses to avoid confusion.

Store ((6 % 2) * 5) + (4 / 2) + 88 - 10 in an int named result.', 'Copy the parenthesized form from the briefing.', 'int result = ((6 % 2) * 5) + (4 / 2) + 88 - 10;', 100, 8, 20, 1, '2026-10-09 08:00:00', 0, 0, 0, 'Use the exact solution: int result = ((6 % 2) * 5) + (4 / 2) + 88 - 10;', 'int\\s+result\\s+=\\s+\\(\\(6\\s+%\\s+2\\)\\s+\\*\\s+5\\)\\s+\\+\\s+\\(4\\s+/\\s+2\\)\\s+\\+\\s+88\\s+-\\s+10;', '/assets/landscapes/oakheart4.png', 'Operator Precedence', 'At the end of the ruins, a final puzzle is carved: 6%2*5+4/2+88-10. Operator precedence tells the compiler the order of evaluation, so the expression is the same as ((6%2)*5)+(4/2)+88-10. The coding guideline says to keep expressions simple and use parentheses to avoid confusion.

Store ((6 % 2) * 5) + (4 / 2) + 88 - 10 in an int named result.', 10, 1, '{"tile_elevations": {}}', 10, 0.78000000, 1, 8, 'int result = ((6 % 2) * 5) + (4 / 2) + 88 - 10;', '[{"part": "int result", "explanation": "Holds the final value, which is 80."}, {"part": "(6 % 2)", "explanation": "Evaluated first, giving 0."}, {"part": "* 5", "explanation": "0 * 5 is 0."}, {"part": "(4 / 2)", "explanation": "Integer division gives 2."}, {"part": "+ 88 - 10", "explanation": "0 + 2 + 88 - 10 = 80."}, {"part": ";", "explanation": "Ends the statement."}]');

-- 4) Guided-mode multiple choice (one step per lesson, like Island 3).
--    Rows are cleared first so re-running this file never hits uq_guided_lesson_step.
DELETE FROM `guided_steps` WHERE `lesson_id` BETWEEN 139 AND 158;

INSERT INTO `guided_steps` (`lesson_id`, `step_order`, `prompt`, `correct_snippet`, `distractor_1`, `distractor_2`, `distractor_3`) VALUES
(139, 1, 'Which Java statement declares an int named lives and initializes it to 3?', 'int lives = 3;', 'int lives = "3";', 'int lives = 3', 'lives int = 3;'),
(140, 1, 'Which code declares a char named option and then assigns \'C\' to it?', 'char option; option = \'C\';', 'char option; option = "C";', 'char option; option == \'C\';', 'char option; option = \'C\''),
(141, 1, 'Which statement declares a double named grade and initializes it to 0.0?', 'double grade = 0.0;', 'double grade = "0.0";', 'double grade == 0.0;', 'double grade = 0.0'),
(142, 1, 'Which code follows the guideline of declaring one variable per line?', 'double exam = 0; double quiz = 10; double grade = 0;', 'double exam = 0, quiz = 10, grade = 0;', 'double exam = 0; quiz = 10; grade = 0;', 'double exam = 0; double quiz = 10; double grade = 0'),
(143, 1, 'Which code declares a boolean named result and then assigns true to it?', 'boolean result; result = true;', 'boolean result; result = "true";', 'boolean result; result = True;', 'bool result; result = true;'),
(144, 1, 'Which code prints the value stored in the int variable value?', 'int value = 10; System.out.println(value);', 'int value = 10; System.out.println("value");', 'int value = 10; System.out.println(value)', 'int value = 10; system.out.println(value);'),
(145, 1, 'Which code prints The value of x=A by joining text with a char variable?', 'char x = \'A\'; System.out.println("The value of x=" + x);', 'char x = \'A\'; System.out.println("The value of x=" + "x");', 'char x = \'A\'; System.out.println("The value of x=", x);', 'char x = "A"; System.out.println("The value of x=" + x);'),
(146, 1, 'Which code prints Hello world! on a single line?', 'System.out.print("Hello "); System.out.print("world!");', 'System.out.println("Hello "); System.out.println("world!");', 'System.out.println("Hello "); System.out.print("world!");', 'System.out.print("Hello ") System.out.print("world!");'),
(147, 1, 'Which statement stores the sum of 37 and 42 in an int named sum?', 'int sum = 37 + 42;', 'int sum = 37 - 42;', 'int sum = "37 + 42";', 'int sum = 37 + 42'),
(148, 1, 'Which code stores the remainder of i divided by j?', 'int i = 37; int j = 42; int remainder = i % j;', 'int i = 37; int j = 42; int remainder = i / j;', 'int i = 37; int j = 42; int remainder = i * j;', 'int i = 37; int j = 42; int remainder = i % j'),
(149, 1, 'Which statement stores 42 + 7.22 in a double named total?', 'double total = 42 + 7.22;', 'int total = 42 + 7.22;', 'double total = 42 - 7.22;', 'double total = "42 + 7.22";'),
(150, 1, 'Which code uses pre-increment so that k becomes 14?', 'int i = 10; int j = 3; int k = 0; k = ++j + i;', 'int i = 10; int j = 3; int k = 0; k = j++ + i;', 'int i = 10; int j = 3; int k = 0; k = --j + i;', 'int i = 10; int j = 3; int k = 0; k = ++j - i;'),
(151, 1, 'Which code declares count as 0 and then increases it by 1?', 'int count = 0; count++;', 'int count = 0; count--;', 'int count = 0; count+1;', 'int count = 0; count++'),
(152, 1, 'Which code stores whether j and k are equal in a boolean named same?', 'int j = 42; int k = 42; boolean same = j == k;', 'int j = 42; int k = 42; boolean same = j = k;', 'int j = 42; int k = 42; boolean same = j != k;', 'int j = 42; int k = 42; int same = j == k;'),
(153, 1, 'Which code uses short-circuit AND so that j++ is never evaluated?', 'int i = 0; int j = 10; boolean test = false; test = (i > 10) && (j++ > 9);', 'int i = 0; int j = 10; boolean test = false; test = (i > 10) & (j++ > 9);', 'int i = 0; int j = 10; boolean test = false; test = (i > 10) || (j++ > 9);', 'int i = 0; int j = 10; boolean test = false; test = (i > 10) && (j++ > 9)'),
(154, 1, 'Which code uses short-circuit OR so that j++ is never evaluated?', 'int i = 0; int j = 10; boolean test = false; test = (i < 10) || (j++ > 9);', 'int i = 0; int j = 10; boolean test = false; test = (i < 10) | (j++ > 9);', 'int i = 0; int j = 10; boolean test = false; test = (i < 10) && (j++ > 9);', 'int i = 0; int j = 10; boolean test = false; test = (i > 10) || (j++ > 9);'),
(155, 1, 'Which code stores the exclusive OR of val1 and val2 in a boolean named xor?', 'boolean val1 = true; boolean val2 = false; boolean xor = val1 ^ val2;', 'boolean val1 = true; boolean val2 = false; boolean xor = val1 && val2;', 'boolean val1 = true; boolean val2 = false; boolean xor = val1 || val2;', 'boolean val1 = true; boolean val2 = false; boolean xor = val1 ^^ val2;'),
(156, 1, 'Which code stores the logical NOT of val1 in a boolean named flipped?', 'boolean val1 = true; boolean flipped = !val1;', 'boolean val1 = true; boolean flipped = val1!;', 'boolean val1 = true; boolean flipped = val1;', 'boolean val1 = true; boolean flipped = ~val1;'),
(157, 1, 'Which code uses the conditional operator to store Passed when grade is at least 60?', 'int grade = 80; String status = (grade >= 60) ? "Passed" : "Fail";', 'int grade = 80; String status = (grade >= 60) ? "Fail" : "Passed";', 'int grade = 80; String status = (grade >= 60) ? "Passed" ; "Fail";', 'int grade = 80; String status = (grade >= 60) ? Passed : Fail;'),
(158, 1, 'Which statement adds parentheses to match operator precedence for 6%2*5+4/2+88-10?', 'int result = ((6 % 2) * 5) + (4 / 2) + 88 - 10;', 'int result = (6 % (2 * 5)) + (4 / 2) + 88 - 10;', 'int result = ((6 % 2) * 5) + (4 / 2) + 88 + 10;', 'int result = ((6 % 2) * 5) + (4 / 2) + 88 - 10');

ALTER TABLE `lessons` AUTO_INCREMENT=159;
