-- Island 4 gameplay-safe guided snippets for the Express/MySQL runtime.
-- The client executor exposes moveRight(number), jump(number), and say(value).
-- Safe to re-run: replaces the ten module 4 guided steps.
USE codequest;

SET @l1 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=1 LIMIT 1);
SET @l2 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=2 LIMIT 1);
SET @l3 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=3 LIMIT 1);
SET @l4 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=4 LIMIT 1);
SET @l5 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=5 LIMIT 1);
SET @l6 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=6 LIMIT 1);
SET @l7 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=7 LIMIT 1);
SET @l8 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=8 LIMIT 1);
SET @l9 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=9 LIMIT 1);
SET @l10 = (SELECT id FROM lessons WHERE module_id=4 AND order_index=10 LIMIT 1);

UPDATE lessons SET briefing='Pip steps on a pressure plate with a measured weight of 12. Store the measurement, check whether it reaches the 10-unit threshold, and move right when the gate accepts it.', hint='Declare weight before the if check. Use moveRight(1), the movement method available to Pip.', goal='Use one if condition to test the plate and move Pip through the gate.' WHERE id=@l1;
UPDATE lessons SET briefing='Pip reaches a split bridge. Store whether the left path is clear, then walk across the clear route or jump over the gap when it is blocked.', hint='Declare isPathClear before branching, then use moveRight(1) or jump(1).', goal='Choose a movement action with if and else.' WHERE id=@l2;
UPDATE lessons SET briefing='Pip counts the tiles to a gap. When fewer than three tiles remain he jumps; otherwise, he keeps moving right across the platform.', hint='Declare tilesToGap before comparing it with 3.', goal='Use a numeric if-else check to choose jump or movement.' WHERE id=@l3;
UPDATE lessons SET briefing='Pip reaches a switch-controlled gate. He records whether it is open, then moves through it or stops by saying that the gate is closed.', hint='Declare isGateOpen and use an if-else branch. The runtime uses say() as Pip''s visible stop/status action.', goal='Branch on a boolean switch state.' WHERE id=@l4;
UPDATE lessons SET briefing='Pip encounters three obstacle types on the platform: obstacle 1 needs a jump, obstacle 2 needs a short move, and every other value means he should wait and report the blockage.', hint='Declare obstacle before the if, else if, else chain.', goal='Select a platform action with multiple conditional branches.' WHERE id=@l5;
UPDATE lessons SET briefing='A locked gate blocks Pip. He can move through only when he has the key and the gate switch is open at the same time.', hint='Declare hasKey and isGateOpen, then combine them with &&.', goal='Require two true conditions before moving.' WHERE id=@l6;
UPDATE lessons SET briefing='Pip can cross the broken bridge when he can jump over it or when the bridge has already lowered. Either safe route is enough to move forward.', hint='Declare canJump and isBridgeDown, then combine them with ||.', goal='Allow either of two safe conditions to trigger movement.' WHERE id=@l7;
UPDATE lessons SET briefing='At a guarded checkpoint, Pip first checks whether the guard is awake. Only then does he check for a key before moving into the next platform.', hint='Nest the hasKey check inside the isPathClear check.', goal='Use a nested if to protect the checkpoint route.' WHERE id=@l8;
UPDATE lessons SET briefing='Pip approaches a trap tile. It is safe only when the path is clear and the spike switch is not active, so both checks must pass before he moves.', hint='Declare isPathClear and hasSpikes, then use !hasSpikes with &&.', goal='Combine a boolean negation with a second condition.' WHERE id=@l9;
UPDATE lessons SET briefing='The Logic Warden guards the exit flag. Pip checks the boss state and elemental phase, then chooses a jump, a move, or a visible status message to finish the platform route.', hint='Declare bossHealth, isEnraged, and element before the branches. Compare strings with === in this runtime.', goal='Synthesize branches and logical checks into a final platform action.' WHERE id=@l10;

DELETE FROM guided_steps WHERE lesson_id IN (@l1,@l2,@l3,@l4,@l5,@l6,@l7,@l8,@l9,@l10);
INSERT INTO guided_steps (lesson_id, step_order, prompt, correct_snippet, distractor_1, distractor_2, distractor_3) VALUES
(@l1,1,'Step on the pressure plate. Which complete conditional stores the weight and moves Pip when it is sufficient?','let weight = 12; if (weight >= 10) { moveRight(1); }','let weight = "12"; if (weight >= 10) { moveRight(1); }','if (weight >= 10) { moveRight(); }','if (weight >= 10) { moveLeft(1); }'),
(@l2,1,'At the fork, which complete conditional walks the clear path or jumps over the gap?','let isPathClear = true; if (isPathClear) { moveRight(1); } else { jump(1); }','let isPathClear = true; if (isPathClear) { jump(1); } else { moveRight(1); }','if (isPathClear) { moveRight(); } else { jump(); }','let isPathClear = "true"; if (isPathClear) { moveRight(1); }'),
(@l3,1,'Which numeric conditional makes Pip jump when fewer than three tiles remain and move otherwise?','let tilesToGap = 2; if (tilesToGap < 3) { jump(1); } else { moveRight(1); }','let tilesToGap = 5; if (tilesToGap < 3) { moveRight(1); } else { jump(1); }','if (tilesToGap < 3) { jump(); } else { moveRight(); }','let tilesToGap = "2"; if (tilesToGap < 3) { jump(1); }'),
(@l4,1,'Which boolean branch moves through an open gate and reports when it is closed?','let isGateOpen = true; if (isGateOpen) { moveRight(1); } else { say("Gate closed"); }','let isGateOpen = "true"; if (isGateOpen) { moveRight(1); }','if (isGateOpen) { moveRight(); } else { stop(); }','let isGateOpen = false; if (isGateOpen) { moveRight(1); }'),
(@l5,1,'Which chain chooses jump for obstacle 1, movement for obstacle 2, and a status message otherwise?','let obstacle = 1; if (obstacle === 1) { jump(1); } else if (obstacle === 2) { moveRight(1); } else { say("Wait"); }','let obstacle = 1; if (obstacle = 1) { jump(1); } else { moveRight(1); }','if (obstacle === 1) { jump(); } else if (obstacle === 2) { moveRight(); }','let obstacle = "1"; if (obstacle === 1) { jump(1); }'),
(@l6,1,'Which AND condition moves Pip only when he has the key and the gate is open?','let hasKey = true; let isGateOpen = true; if (hasKey && isGateOpen) { moveRight(1); }','let hasKey = true; let isGateOpen = false; if (hasKey || isGateOpen) { moveRight(1); }','if (hasKey && isGateOpen) { moveRight(); }','let hasKey = "true"; let isGateOpen = true; if (hasKey && isGateOpen) { moveRight(1); }'),
(@l7,1,'Which OR condition moves Pip when he can jump or the bridge is already down?','let canJump = true; let isBridgeDown = false; if (canJump || isBridgeDown) { moveRight(1); }','let canJump = false; let isBridgeDown = false; if (canJump && isBridgeDown) { moveRight(1); }','if (canJump || isBridgeDown) { moveRight(); }','let canJump = "true"; let isBridgeDown = false; if (canJump || isBridgeDown) { moveRight(1); }'),
(@l8,1,'Which nested conditional checks the path first, then checks Pip''s key before moving?','let isPathClear = true; let hasKey = true; if (isPathClear) { if (hasKey) { moveRight(1); } }','if (hasKey) { if (isPathClear) { moveRight(); } }','let isPathClear = true; if (isPathClear && hasKey) { moveRight(1); }','let isPathClear = false; let hasKey = true; if (isPathClear) { moveRight(1); }'),
(@l9,1,'Which condition moves Pip only when the path is clear and spikes are not active?','let isPathClear = true; let hasSpikes = false; if (isPathClear && !hasSpikes) { moveRight(1); }','let isPathClear = true; let hasSpikes = true; if (isPathClear && !hasSpikes) { moveRight(1); }','if (isPathClear || !hasSpikes) { moveRight(); }','let isPathClear = "true"; let hasSpikes = false; if (isPathClear && !hasSpikes) { moveRight(1); }'),
(@l10,1,'Which final branch checks the Logic Warden state and element before choosing a platform action?','let bossHealth = 20; let isEnraged = true; let element = "Fire"; if (bossHealth < 30 && isEnraged) { jump(1); } else if (element === "Fire") { moveRight(1); } else { say("Warden blocked"); }','let bossHealth = 20; let isEnraged = true; let element = "Fire"; if (bossHealth < 30 || isEnraged) { jump(1); }','if (element == "Fire") { moveRight(); } else { jump(); }','let bossHealth = "20"; let isEnraged = true; let element = Fire; if (bossHealth < 30 && isEnraged) { jump(1); }');
